import { inferSurfaceContext, type SectionVariant } from '../registry';
const STACK = { desktop: 'multi-columna', tablet: '2 columnas', mobile: '1 columna' };
function variant(v: Omit<SectionVariant, 'nicheId' | 'sourceTemplateId' | 'schemaVersion' | 'surfaceContext'> & { surfaceContext?: SectionVariant['surfaceContext'] }): SectionVariant { return { nicheId: 'carpinteria', sourceTemplateId: 'carpinteria-configurador', schemaVersion: '1.0.0', layoutContract: { containment: v.sectionType === 'header' ? 'document' : 'section', overflow: v.sectionType === 'header' ? 'visible' : 'clip' }, ...v, surfaceContext: v.surfaceContext ?? inferSurfaceContext(v) } as SectionVariant; }
function simple(id: string, type: SectionVariant['sectionType'], name: string, fields: string[], outputs: string[], required = false, surfaceContext?: SectionVariant['surfaceContext']) { return variant({ id, sectionType: type, name, description: 'Bloque modular del configurador conectado a catálogos editables y relaciones estables.', requiredFields: fields, optionalFields: [], collectionLimits: [], themeTokenCoverage: ['brandPrimary', 'surface', 'text', 'border'], responsiveContract: STACK, navigationOutputs: outputs, requiredCompanions: [], conflicts: [], assetSlots: [], required, fixed: required, surfaceContext }); }
export const CARPINTERIA_CONFIGURADOR_VARIANTS: SectionVariant[] = [
  variant({ id: 'cc-header-01', sectionType: 'header', name: 'Cabecera de producto', description: 'Marca compacta, navegación y acceso directo al configurador.', requiredFields: ['business.name', 'navigation.items'], optionalFields: ['business.logo'], collectionLimits: [], themeTokenCoverage: ['surface', 'text', 'brandPrimary'], responsiveContract: { desktop: 'marca · nav · CTA', tablet: 'marca · CTA · drawer', mobile: 'marca · drawer' }, navigationOutputs: ['/'], requiredCompanions: ['footer'], conflicts: [], assetSlots: [{ key: 'logo', ratio: 'libre', minWidth: 240, minHeight: 80, required: false }], required: true, fixed: true }),
  variant({ id: 'cc-hero-01', sectionType: 'hero', name: 'Hero con selector interactivo', description: 'Copy y simulación de la primera decisión del brief, sin almacenar un estado paralelo.', requiredFields: ['content.hero.title', 'collections.tipos-proyecto'], optionalFields: ['content.hero.image'], collectionLimits: [{ collection: 'tipos-proyecto', min: 1, max: 8 }], themeTokenCoverage: ['heroBackground', 'brandPrimary', 'surface'], responsiveContract: { desktop: 'copy · selector', tablet: 'copy → selector', mobile: 'flujo vertical' }, navigationOutputs: ['#inicio', '/configura-tu-proyecto'], requiredCompanions: [], conflicts: [], assetSlots: [{ key: 'hero', ratio: '4:3', minWidth: 1600, minHeight: 1200, required: false }], required: true, fixed: false }),
  simple('cc-tipos-01', 'benefits', 'Tipos configurables', ['collections.tipos-proyecto'], ['#tipos', '/tipos', '/tipos/{slug}']), simple('cc-pasos-01', 'process', 'Secuencia del trabajo', ['collections.fases-proceso'], ['#como-funciona', '/como-trabajamos'], false, 'dark'),
  simple('cc-inspiracion-01', 'gallery', 'Direcciones visuales', ['collections.estilos'], ['#inspiracion', '/estilos', '/estilos/{slug}']), simple('cc-servicios-01', 'services', 'Servicios vinculados', ['collections.servicios-configurador'], ['#servicios', '/servicios/{slug}']),
  simple('cc-faq-01', 'faq', 'Preguntas del configurador', ['collections.preguntas-carpinteria'], ['#preguntas', '/preguntas']), simple('cc-final-01', 'finalCta', 'Acceso al configurador', ['content.finalCta'], ['#configurar', '/configura-tu-proyecto'], false, 'brand'),
  variant({ id: 'cc-footer-01', sectionType: 'footer', name: 'Pie modular', description: 'Navegación, contacto y firma legal.', requiredFields: ['business.legalName', 'content.legal'], optionalFields: [], collectionLimits: [], themeTokenCoverage: ['surfaceInverse', 'textInverse'], responsiveContract: STACK, navigationOutputs: ['/privacidad', '/cookies'], requiredCompanions: ['header'], conflicts: [], assetSlots: [], required: true, fixed: true }),
  ...([
    ['cc-page-configura-01', 'contact', 'Configurador completo', '/configura-tu-proyecto', ['forms']], ['cc-page-servicios-01', 'services', 'Servicios', '/servicios', ['collections.servicios-configurador']],
    ['cc-page-tipos-01', 'benefits', 'Tipos', '/tipos', ['collections.tipos-proyecto']], ['cc-page-estilos-01', 'gallery', 'Estilos', '/estilos', ['collections.estilos']],
    ['cc-page-materiales-01', 'plans', 'Materiales', '/materiales', ['collections.materiales']], ['cc-page-acabados-01', 'plans', 'Acabados', '/acabados', ['collections.acabados']],
    ['cc-page-proceso-01', 'process', 'Método', '/como-trabajamos', ['collections.fases-proceso']], ['cc-page-proyectos-01', 'gallery', 'Proyectos', '/proyectos', ['collections.proyectos-configurador']],
    ['cc-page-faq-01', 'faq', 'Preguntas', '/preguntas', ['collections.preguntas-carpinteria']], ['cc-page-legal-01', 'contact', 'Documento legal', '/aviso-legal', ['content.legal']],
  ] as const).map(([id, type, name, route, fields]) => simple(id, type as SectionVariant['sectionType'], name, [...fields], [route], true)),
];
