import { inferSurfaceContext, type SectionVariant } from '../registry';
const STACK = { desktop: 'multi-columna', tablet: '2 columnas', mobile: '1 columna' };
function variant(v: Omit<SectionVariant, 'nicheId' | 'sourceTemplateId' | 'schemaVersion' | 'surfaceContext'> & { surfaceContext?: SectionVariant['surfaceContext'] }): SectionVariant { return { nicheId: 'carpinteria', sourceTemplateId: 'carpinteria-taller', schemaVersion: '1.0.0', layoutContract: { containment: v.sectionType === 'header' ? 'document' : 'section', overflow: v.sectionType === 'header' ? 'visible' : 'clip' }, ...v, surfaceContext: v.surfaceContext ?? inferSurfaceContext(v) } as SectionVariant; }
function simple(id: string, type: SectionVariant['sectionType'], name: string, fields: string[], outputs: string[], required = false, surfaceContext?: SectionVariant['surfaceContext']) { return variant({ id, sectionType: type, name, description: 'Bloque narrativo del taller conectado al editor genérico.', requiredFields: fields, optionalFields: [], collectionLimits: [], themeTokenCoverage: ['brandPrimary', 'surface', 'text', 'border'], responsiveContract: STACK, navigationOutputs: outputs, requiredCompanions: [], conflicts: [], assetSlots: [], required, fixed: required, surfaceContext }); }
export const CARPINTERIA_TALLER_VARIANTS: SectionVariant[] = [
  variant({ id: 'ct-header-01', sectionType: 'header', name: 'Cabecera oscura de taller', description: 'Marca, navegación y teléfono sobre superficie inversa.', requiredFields: ['business.name', 'navigation.items'], optionalFields: ['business.logo'], collectionLimits: [], themeTokenCoverage: ['surfaceInverse', 'textInverse'], responsiveContract: { desktop: 'marca · nav · teléfono', tablet: 'marca · teléfono · drawer', mobile: 'marca · drawer' }, navigationOutputs: ['/'], requiredCompanions: ['footer'], conflicts: [], assetSlots: [{ key: 'logo', ratio: 'libre', minWidth: 240, minHeight: 80, required: false }], required: true, fixed: true }),
  variant({ id: 'ct-hero-01', sectionType: 'hero', name: 'Hero cinematográfico de oficio', description: 'Fotografía envolvente, titular editorial y banda de principios.', requiredFields: ['content.hero.title'], optionalFields: ['content.hero.image'], collectionLimits: [], themeTokenCoverage: ['surfaceInverse', 'textInverse', 'accent'], responsiveContract: { desktop: 'imagen de fondo + copy + banda', tablet: 'copy + banda', mobile: 'flujo vertical' }, navigationOutputs: ['#inicio'], requiredCompanions: [], conflicts: [], assetSlots: [{ key: 'hero', ratio: '16:9', minWidth: 1920, minHeight: 1080, required: false }], required: true, fixed: false }),
  simple('ct-manifiesto-01', 'benefits', 'Manifiesto del taller', ['business.name'], ['#taller', '/nuestro-taller']), simple('ct-servicios-01', 'services', 'Servicios de taller', ['collections.servicios-carpinteria'], ['#servicios', '/servicios/{slug}']), simple('ct-proceso-01', 'process', 'Proceso documentado', ['collections.fases-proceso'], ['#proceso', '/el-proceso'], false, 'dark'), simple('ct-historias-01', 'gallery', 'Historias del taller', ['collections.historias-taller'], ['#historias', '/historias/{slug}']), simple('ct-valores-01', 'benefits', 'Valores demostrables', ['collections.valores-taller'], ['#valores', '/valores']), simple('ct-final-01', 'finalCta', 'Contacto editorial', ['content.finalCta'], ['#contacto', '/contacto'], false, 'alternative'),
  variant({ id: 'ct-footer-01', sectionType: 'footer', name: 'Pie de taller', description: 'Marca, navegación, dirección y documentos legales.', requiredFields: ['business.legalName', 'content.legal'], optionalFields: [], collectionLimits: [], themeTokenCoverage: ['surfaceInverse', 'textInverse'], responsiveContract: STACK, navigationOutputs: ['/privacidad', '/cookies'], requiredCompanions: ['header'], conflicts: [], assetSlots: [], required: true, fixed: true }),
  ...([
    ['ct-page-taller-01', 'team', 'Nuestro taller', '/nuestro-taller', ['business.name']], ['ct-page-servicios-01', 'services', 'Servicios', '/servicios', ['collections.servicios-carpinteria']], ['ct-page-proceso-01', 'process', 'Proceso', '/el-proceso', ['collections.fases-proceso']], ['ct-page-materiales-01', 'plans', 'Materiales', '/materiales', ['collections.materiales']], ['ct-page-historias-01', 'gallery', 'Historias', '/historias', ['collections.historias-taller']], ['ct-page-galeria-01', 'gallery', 'Galería', '/galeria', ['collections.galeria-taller']], ['ct-page-equipo-01', 'team', 'Equipo', '/equipo', ['collections.equipo-taller']], ['ct-page-valores-01', 'benefits', 'Valores', '/valores', ['collections.valores-taller']], ['ct-page-faq-01', 'faq', 'Preguntas', '/preguntas', ['collections.preguntas-carpinteria']], ['ct-page-contacto-01', 'contact', 'Contacto', '/contacto', ['forms']], ['ct-page-legal-01', 'contact', 'Documento legal', '/aviso-legal', ['content.legal']], ['ct-page-categorias-01', 'benefits', 'Detalle de categoría', '/categorias/{slug}', ['collections.categorias-proyecto']], ['ct-page-proyectos-01', 'gallery', 'Detalle de proyecto', '/proyectos/{slug}', ['collections.proyectos']],
  ] as const).map(([id, type, name, route, fields]) => simple(id, type as SectionVariant['sectionType'], name, [...fields], [route], true)),
];
