/**
 * Contratos de las variantes de «Casa Tranquila · Hogar».
 *
 * Los slots de imagen se declaran opcionales: la template no empaqueta
 * fotografía de demostración, pero cada hueco sigue siendo visible y
 * gestionable desde Recursos visuales.
 */

import { inferSurfaceContext, type SectionVariant } from '../registry';

const NICHE = 'control-de-plagas';
const TEMPLATE = 'plagas-hogar';

function variant(
  v: Omit<SectionVariant, 'nicheId' | 'schemaVersion' | 'sourceTemplateId' | 'surfaceContext'> & {
    schemaVersion?: string;
    sourceTemplateId?: string;
    surfaceContext?: SectionVariant['surfaceContext'];
  },
): SectionVariant {
  return {
    nicheId: NICHE,
    sourceTemplateId: v.sourceTemplateId ?? TEMPLATE,
    schemaVersion: v.schemaVersion ?? '1.0.0',
    layoutContract: {
      containment: v.sectionType === 'header' ? 'document' : 'section',
      overflow: v.sectionType === 'header' ? 'visible' : 'clip',
    },
    surfaceContext: v.surfaceContext ?? inferSurfaceContext(v),
    ...v,
  } as SectionVariant;
}

const STACK = { desktop: 'multi-columna', tablet: '2 columnas', mobile: '1 columna' };

export const PLAGAS_HOGAR_VARIANTS: SectionVariant[] = [
  variant({
    id: 'hg-header-01',
    sectionType: 'header',
    name: 'Cabecera doméstica',
    description: 'Marca cálida, navegación amplia y una única llamada a solicitar revisión. Sin barra de urgencias.',
    requiredFields: ['business.name', 'navigation.items', 'navigation.primaryCta'],
    optionalFields: ['business.logo'],
    collectionLimits: [{ collection: 'navigation.items', min: 3, max: 12 }],
    themeTokenCoverage: ['brandPrimary', 'surface', 'border', 'text'],
    responsiveContract: { desktop: 'logo · nav · CTA', tablet: 'logo · CTA', mobile: 'drawer' },
    navigationOutputs: ['/'],
    requiredCompanions: ['footer'],
    conflicts: [],
    assetSlots: [{ key: 'logo', ratio: 'libre', minWidth: 240, minHeight: 80, required: false }],
    required: true,
    fixed: true,
  }),
  variant({
    id: 'hg-hero-01',
    sectionType: 'hero',
    name: 'Hero sereno con valores',
    description: 'Copy tranquilo, valoración opcional y fila de valores del servicio. Sin mensajes de urgencia.',
    requiredFields: ['content.hero.title', 'content.hero.paragraph', 'content.hero.primaryCta'],
    optionalFields: ['content.hero.image', 'content.hero.ratingBadge', 'content.hero.note'],
    collectionLimits: [{ collection: 'content.hero.microBenefits', min: 2, max: 4 }],
    themeTokenCoverage: ['brandPrimary', 'heroBackground', 'text', 'textMuted'],
    responsiveContract: { desktop: '2 columnas + banda', tablet: '2 columnas', mobile: 'copy → media → banda' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'hero', ratio: '4:3', minWidth: 1600, minHeight: 1200, required: false }],
    required: true,
    fixed: false,
  }),
  variant({
    id: 'hg-senales-01',
    sectionType: 'services',
    name: 'Problemas frecuentes con sus señales',
    description: 'Tarjetas de reconocimiento a partir del catálogo editable, con las señales habituales de cada caso.',
    requiredFields: ['collections.@catalog'],
    optionalFields: [],
    collectionLimits: [{ collection: '@catalog', min: 0, max: 24 }],
    collectionItemFields: { '@catalog': ['nombre', 'slug', 'resumen'] },
    themeTokenCoverage: ['brandPrimary', 'accent', 'surface', 'radiusCard'],
    responsiveContract: { desktop: '3 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#senales', '@catalog', '@catalogItem'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'plagas.imagen', ratio: '4:3', minWidth: 1200, minHeight: 900, required: false }],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'hg-proceso-01',
    sectionType: 'process',
    name: 'Proceso en tres pasos',
    description: 'Recorrido corto y explicativo, de la primera consulta a la decisión informada.',
    requiredFields: ['content.processSteps'],
    optionalFields: ['content.headings.process'],
    collectionLimits: [{ collection: 'content.processSteps', min: 2, max: 5 }],
    themeTokenCoverage: ['brandPrimary', 'surface', 'border'],
    responsiveContract: { desktop: '3 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#proceso'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'hg-estaciones-01',
    sectionType: 'benefits',
    name: 'Prevención estacional con pestañas',
    description: 'Un panel por estación con qué vigilar, qué hacer y las plagas más activas, todo configurable.',
    requiredFields: ['collections.@seasons'],
    optionalFields: ['collections.@catalog'],
    collectionLimits: [{ collection: '@seasons', min: 0, max: 12 }],
    collectionItemFields: { '@seasons': ['titulo', 'resumen'] },
    themeTokenCoverage: ['brandPrimary', 'surfaceAlt', 'border'],
    responsiveContract: { desktop: 'pestañas + panel', tablet: 'pestañas + panel', mobile: 'pestañas scrollables' },
    navigationOutputs: ['#prevencion', '@seasons'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'prevencion-estacional.imagen', ratio: '3:2', minWidth: 1200, minHeight: 800, required: false }],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'hg-tratamientos-01',
    sectionType: 'services',
    name: 'Tratamientos domésticos',
    description: 'Servicios con lo que incluye cada uno, del menos al más invasivo.',
    requiredFields: ['services'],
    optionalFields: ['content.headings.services'],
    collectionLimits: [{ collection: 'services', min: 2, max: 8 }],
    themeTokenCoverage: ['brandPrimary', 'accent', 'surface'],
    responsiveContract: STACK,
    navigationOutputs: ['#tratamientos', '@services', '@servicesItem'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'service', ratio: '4:3', minWidth: 1200, minHeight: 900, required: false }],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'hg-plan-01',
    sectionType: 'plans',
    name: 'Comparativa puntual frente a mantenimiento',
    description:
      'Fila comparable con zonas alineadas: cabecera, precio, contenido y acción quedan a la misma altura en todas las tarjetas.',
    requiredFields: ['collections.@plans'],
    optionalFields: ['content.pricingNote', 'content.headings.plans'],
    collectionLimits: [{ collection: '@plans', min: 0, max: 6 }],
    collectionItemFields: { '@plans': ['nombre'] },
    themeTokenCoverage: ['brandPrimary', 'surface', 'surfaceHighlight'],
    responsiveContract: { desktop: '3 columnas alineadas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#plan', '@plans'],
    requiredCompanions: [],
    conflicts: ['packages'],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'hg-consejos-01',
    sectionType: 'gallery',
    name: 'Consejos para el hogar',
    description: 'Contenido educativo con categoría y resumen. Estado vacío diseñado.',
    requiredFields: ['collections.@articles'],
    optionalFields: [],
    collectionLimits: [{ collection: '@articles', min: 0, max: 30 }],
    collectionItemFields: { '@articles': ['titulo', 'resumen'] },
    themeTokenCoverage: ['surface', 'radiusImage', 'brandPrimary'],
    responsiveContract: STACK,
    navigationOutputs: ['#consejos', '@articles', '@articlesItem'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'consejos.imagen', ratio: '3:2', minWidth: 1200, minHeight: 800, required: false }],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'hg-testimonials-01',
    sectionType: 'testimonials',
    name: 'Opiniones de familias',
    description: 'Valoraciones con la firma alineada al pie de cada tarjeta.',
    requiredFields: ['testimonials'],
    optionalFields: ['content.headings.testimonials'],
    collectionLimits: [{ collection: 'testimonials', min: 1, max: 8 }],
    themeTokenCoverage: ['brandPrimary', 'star', 'surface'],
    responsiveContract: STACK,
    navigationOutputs: ['#opiniones'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'hg-faq-01',
    sectionType: 'faq',
    name: 'Preguntas frecuentes con contacto',
    description: 'Bloque partido: encabezado con llamada telefónica y acordeón accesible.',
    requiredFields: ['faqs'],
    optionalFields: ['business.phone'],
    collectionLimits: [{ collection: 'faqs', min: 3, max: 16 }],
    themeTokenCoverage: ['border', 'surface', 'brandPrimary'],
    responsiveContract: { desktop: '38/62', tablet: 'apilado', mobile: 'apilado' },
    navigationOutputs: ['#faq', '@faq'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'hg-finalcta-01',
    sectionType: 'finalCta',
    name: 'Cierre con revisión sin compromiso',
    description: 'Banda suave con la llamada principal y el teléfono, sin lenguaje de urgencia.',
    requiredFields: ['content.finalCta'],
    optionalFields: ['business.phone'],
    collectionLimits: [],
    themeTokenCoverage: ['brandPrimary', 'surfaceHighlight', 'text'],
    responsiveContract: { desktop: 'horizontal', tablet: 'horizontal', mobile: 'apilado' },
    navigationOutputs: ['#revision', '@contact'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'hg-footer-01',
    sectionType: 'footer',
    name: 'Pie claro con zonas y horario',
    description: 'Cuatro columnas sobre superficie clara y franja legal con las tres políticas.',
    requiredFields: ['business.legalName', 'content.legal', 'business.openingHours'],
    optionalFields: ['collections.@serviceAreas', 'contact.socialLinks'],
    collectionLimits: [],
    themeTokenCoverage: ['surfaceAlt', 'text', 'brandPrimary'],
    responsiveContract: STACK,
    navigationOutputs: ['@legalNotice', '/privacidad', '/cookies'],
    requiredCompanions: ['header'],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: true,
  }),

  ...(
    [
      ['hg-page-hogar-01', 'benefits', 'Página de hogar protegido', '@about', ['content.benefits']],
      ['hg-page-problemas-01', 'services', 'Página de problemas frecuentes', '@catalog', ['collections.@catalog']],
      ['hg-page-prevencion-01', 'benefits', 'Página de prevención estacional', '@seasons', ['collections.@seasons']],
      ['hg-page-tratamientos-01', 'services', 'Página de tratamientos', '@services', ['services']],
      ['hg-page-plan-01', 'plans', 'Página del plan de mantenimiento', '@plans', ['collections.@plans']],
      ['hg-page-consejos-01', 'gallery', 'Página de consejos', '@articles', ['collections.@articles']],
      ['hg-page-sector-01', 'benefits', 'Detalle de tipo de vivienda', '@segmentsItem', ['collections.@segments']],
      ['hg-page-nosotros-01', 'benefits', 'Página sobre nosotros', '@about', ['content.benefits']],
      ['hg-page-faq-01', 'faq', 'Página de preguntas frecuentes', '@faq', ['faqs']],
      ['hg-page-revision-01', 'contact', 'Página de solicitud de revisión', '@contact', ['forms']],
      ['hg-page-legal-01', 'contact', 'Página legal', '@legalNotice', ['content.legal']],
    ] as const
  ).map(([id, sectionType, name, route, requiredFields]) =>
    variant({
      id,
      sectionType: sectionType as SectionVariant['sectionType'],
      name,
      description: 'Portada de sección, contenido propio, estados vacíos diseñados y llamada a la acción.',
      requiredFields: [...requiredFields],
      optionalFields: [],
      collectionLimits: [],
      themeTokenCoverage: ['surface', 'text', 'brandPrimary'],
      responsiveContract: { desktop: '2 columnas', tablet: '1 columna', mobile: '1 columna' },
      navigationOutputs: [route],
      requiredCompanions: [],
      conflicts: [],
      assetSlots: [],
      required: true,
      fixed: true,
    }),
  ),
];
