/**
 * Contratos de las variantes del nicho de control de plagas.
 *
 * El Creador Web valida contra esto antes de permitir combinar bloques, así que
 * cada variante declara qué datos necesita, qué colecciones consume, qué slots
 * de imagen publica y cómo se comporta en cada anchura.
 */

import { inferSurfaceContext, type SectionVariant } from '../registry';

const NICHE = 'control-de-plagas';
const TEMPLATE = 'plagas-respuesta-rapida';

function variant(
  v: Omit<SectionVariant, 'nicheId' | 'schemaVersion' | 'sourceTemplateId' | 'surfaceContext'> & {
    schemaVersion?: string;
    sourceTemplateId?: string;
    surfaceContext?: SectionVariant['surfaceContext'];
  },
): SectionVariant {
  return {
    nicheId: NICHE,
    sourceTemplateId: v.sourceTemplateId ?? TEMPLATE,
    schemaVersion: v.schemaVersion ?? '1.0.0',
    layoutContract: {
      containment: v.sectionType === 'header' ? 'document' : 'section',
      overflow: v.sectionType === 'header' ? 'visible' : 'clip',
    },
    surfaceContext: v.surfaceContext ?? inferSurfaceContext(v),
    ...v,
  } as SectionVariant;
}

const STACK = { desktop: 'multi-columna', tablet: '2 columnas', mobile: '1 columna' };

export const PLAGAS_RESPUESTA_RAPIDA_VARIANTS: SectionVariant[] = [
  variant({
    id: 'pr-header-01',
    sectionType: 'header',
    name: 'Cabecera con urgencias y contacto directo',
    description: 'Barra superior con zona, disponibilidad, teléfono y WhatsApp, más navegación y CTA de inspección.',
    requiredFields: ['business.name', 'business.phone', 'navigation.items', 'navigation.primaryCta'],
    optionalFields: ['business.whatsapp', 'business.logo', 'business.openingHours'],
    collectionLimits: [{ collection: 'navigation.items', min: 3, max: 10 }],
    themeTokenCoverage: ['brandPrimary', 'surface', 'surfaceInverse', 'border', 'whatsapp'],
    responsiveContract: { desktop: 'barra + logo · nav · CTA', tablet: 'logo · acciones', mobile: 'drawer' },
    navigationOutputs: ['/'],
    requiredCompanions: ['footer'],
    conflicts: [],
    assetSlots: [{ key: 'logo', ratio: 'libre', minWidth: 240, minHeight: 80, required: false }],
    required: true,
    fixed: true,
  }),
  variant({
    id: 'pr-hero-01',
    sectionType: 'hero',
    name: 'Hero de urgencia con cobertura',
    description: 'Copy de rapidez y garantía, doble CTA, valoración y tarjeta de zonas con tiempo de respuesta.',
    requiredFields: ['content.hero.title', 'content.hero.paragraph', 'content.hero.primaryCta'],
    optionalFields: ['content.hero.image', 'content.hero.ratingBadge', 'content.hero.note'],
    collectionLimits: [
      { collection: 'content.hero.microBenefits', min: 2, max: 4 },
      { collection: '@serviceAreas', min: 0, max: 40 },
    ],
    collectionItemFields: { '@serviceAreas': ['nombre', 'respuesta'] },
    themeTokenCoverage: ['brandPrimary', 'accent', 'heroBackground', 'text', 'textMuted'],
    responsiveContract: { desktop: '2 columnas + banda', tablet: '2 columnas', mobile: 'copy → media → banda' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'hero', ratio: '4:3', minWidth: 1800, minHeight: 1350, required: false }],
    required: true,
    fixed: false,
  }),
  variant({
    id: 'pr-trust-01',
    sectionType: 'benefits',
    name: 'Indicadores de confianza',
    description: 'Fila de ventajas con icono, título y explicación breve. Alturas igualadas por contrato de tarjeta.',
    requiredFields: ['content.benefits'],
    optionalFields: ['content.headings.benefits'],
    collectionLimits: [{ collection: 'content.benefits', min: 3, max: 6 }],
    themeTokenCoverage: ['brandPrimary', 'accent', 'surface', 'border'],
    responsiveContract: { desktop: '5 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#confianza'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pr-plagas-01',
    sectionType: 'services',
    name: 'Catálogo de tipos de plaga',
    description: 'Rejilla de plagas con icono, señales y acceso a la ficha. El catálogo es una colección editable.',
    requiredFields: ['collections.@catalog'],
    optionalFields: [],
    collectionLimits: [{ collection: '@catalog', min: 0, max: 24 }],
    collectionItemFields: { '@catalog': ['nombre', 'slug', 'resumen'] },
    themeTokenCoverage: ['brandPrimary', 'accent', 'surface', 'radiusCard'],
    responsiveContract: { desktop: '3 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#plagas', '@catalog', '@catalogItem'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'plagas.imagen', ratio: '4:3', minWidth: 1200, minHeight: 900, required: false }],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pr-services-01',
    sectionType: 'services',
    name: 'Servicios con inclusiones',
    description: 'Tarjetas de servicio con icono, descripción, lista de inclusiones y acceso a la ficha.',
    requiredFields: ['services'],
    optionalFields: ['content.headings.services'],
    collectionLimits: [{ collection: 'services', min: 3, max: 8 }],
    themeTokenCoverage: ['brandPrimary', 'accent', 'surfaceAlt', 'border'],
    responsiveContract: { desktop: '3 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#servicios', '@services', '@servicesItem'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'service', ratio: '4:3', minWidth: 1200, minHeight: 900, required: false }],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pr-process-01',
    sectionType: 'process',
    name: 'Proceso numerado de intervención',
    description: 'Pasos con numeración e icono, del primer contacto a la revisión de confirmación.',
    requiredFields: ['content.processSteps'],
    optionalFields: ['content.headings.process'],
    collectionLimits: [{ collection: 'content.processSteps', min: 3, max: 6 }],
    themeTokenCoverage: ['brandPrimary', 'surface', 'textMuted'],
    responsiveContract: { desktop: '4 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#proceso'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pr-sectores-01',
    sectionType: 'benefits',
    name: 'Sectores atendidos',
    description: 'Tarjetas por tipo de cliente con sus necesidades específicas y acceso al detalle.',
    requiredFields: ['collections.@segments'],
    optionalFields: [],
    collectionLimits: [{ collection: '@segments', min: 0, max: 16 }],
    collectionItemFields: { '@segments': ['nombre', 'resumen'] },
    themeTokenCoverage: ['brandPrimary', 'surface', 'border'],
    responsiveContract: { desktop: '3 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#sectores', '@segments', '@segmentsItem'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'sectores.imagen', ratio: '3:2', minWidth: 1200, minHeight: 800, required: false }],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pr-zonas-01',
    sectionType: 'contact',
    name: 'Zonas de cobertura con tiempo de respuesta',
    description: 'Bloque partido con copy y listado de localidades; las destacadas se marcan visualmente.',
    requiredFields: ['collections.@serviceAreas', 'business.serviceArea'],
    optionalFields: ['business.phone'],
    collectionLimits: [{ collection: '@serviceAreas', min: 0, max: 40 }],
    collectionItemFields: { '@serviceAreas': ['nombre'] },
    themeTokenCoverage: ['brandPrimary', 'surfaceAlt', 'border'],
    responsiveContract: { desktop: '40/60', tablet: 'apilado', mobile: 'apilado' },
    navigationOutputs: ['#zonas', '@serviceAreas'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pr-trabajos-01',
    sectionType: 'gallery',
    name: 'Trabajos realizados',
    description: 'Casos con situación de partida, intervención y resultado. Estado vacío diseñado.',
    requiredFields: ['collections.@cases'],
    optionalFields: ['content.headings.gallery'],
    collectionLimits: [{ collection: '@cases', min: 0, max: 30 }],
    collectionItemFields: { '@cases': ['titulo'] },
    themeTokenCoverage: ['surface', 'radiusImage', 'brandPrimary'],
    responsiveContract: { desktop: '2 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#trabajos', '@cases'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [
      { key: 'trabajos.imagen', ratio: '4:3', minWidth: 1200, minHeight: 900, required: false },
      { key: 'trabajos.antes', ratio: '1:1', minWidth: 900, minHeight: 900, required: false },
      { key: 'trabajos.despues', ratio: '1:1', minWidth: 900, minHeight: 900, required: false },
    ],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pr-testimonials-01',
    sectionType: 'testimonials',
    name: 'Opiniones en rejilla',
    description: 'Reseñas con valoración y autor, con la firma alineada al pie de cada tarjeta.',
    requiredFields: ['testimonials'],
    optionalFields: ['content.headings.testimonials'],
    collectionLimits: [{ collection: 'testimonials', min: 1, max: 8 }],
    themeTokenCoverage: ['brandPrimary', 'star', 'surface'],
    responsiveContract: STACK,
    navigationOutputs: ['#opiniones'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pr-faq-01',
    sectionType: 'faq',
    name: 'Preguntas frecuentes con contacto',
    description: 'Bloque partido: encabezado con llamada telefónica y acordeón accesible.',
    requiredFields: ['faqs'],
    optionalFields: ['business.phone'],
    collectionLimits: [{ collection: 'faqs', min: 3, max: 14 }],
    themeTokenCoverage: ['border', 'surface', 'brandPrimary'],
    responsiveContract: { desktop: '38/62', tablet: 'apilado', mobile: 'apilado' },
    navigationOutputs: ['#faq', '@faq'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pr-finalcta-01',
    sectionType: 'finalCta',
    name: 'Cierre con presupuesto',
    description: 'Banda de contraste con doble llamada: solicitud y teléfono directo.',
    requiredFields: ['content.finalCta'],
    optionalFields: ['business.phone'],
    collectionLimits: [],
    themeTokenCoverage: ['brandPrimary', 'brandPrimaryContrast', 'surfaceInverse'],
    responsiveContract: { desktop: 'horizontal', tablet: 'horizontal', mobile: 'apilado' },
    navigationOutputs: ['#presupuesto'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pr-footer-01',
    sectionType: 'footer',
    name: 'Pie con plagas, navegación y horario',
    description: 'Cuatro columnas sobre superficie inversa y franja legal con las tres políticas.',
    requiredFields: ['business.legalName', 'content.legal', 'business.openingHours'],
    optionalFields: ['collections.@catalog', 'contact.socialLinks'],
    collectionLimits: [],
    themeTokenCoverage: ['surfaceInverse', 'textInverse', 'brandPrimary'],
    responsiveContract: STACK,
    navigationOutputs: ['@legalNotice', '/privacidad', '/cookies'],
    requiredCompanions: ['header'],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: true,
  }),

  /* ------------------------------ Páginas ------------------------------- */
  ...(
    [
      ['pr-page-servicios-01', 'services', 'Página de servicios', '@services', ['services']],
      ['pr-page-plagas-01', 'services', 'Página de tipos de plaga', '@catalog', ['collections.@catalog']],
      ['pr-page-sectores-01', 'benefits', 'Página de sectores', '@segments', ['collections.@segments']],
      ['pr-page-zonas-01', 'contact', 'Página de zonas de cobertura', '@serviceAreas', ['collections.@serviceAreas']],
      ['pr-page-trabajos-01', 'gallery', 'Página de trabajos realizados', '@cases', ['collections.@cases']],
      ['pr-page-consejos-01', 'gallery', 'Detalle de consejo preventivo', '@articlesItem', ['collections.@articles']],
      ['pr-page-nosotros-01', 'benefits', 'Página sobre nosotros', '@about', ['content.benefits']],
      ['pr-page-faq-01', 'faq', 'Página de preguntas frecuentes', '@faq', ['faqs']],
      ['pr-page-contacto-01', 'contact', 'Página de contacto', '@contact', ['forms']],
      ['pr-page-legal-01', 'contact', 'Página legal', '@legalNotice', ['content.legal']],
    ] as const
  ).map(([id, sectionType, name, route, requiredFields]) =>
    variant({
      id,
      sectionType: sectionType as SectionVariant['sectionType'],
      name,
      description: 'Portada de sección, contenido específico, estados vacíos diseñados y llamada a la acción.',
      requiredFields: [...requiredFields],
      optionalFields: [],
      collectionLimits: [],
      themeTokenCoverage: ['surface', 'text', 'brandPrimary'],
      responsiveContract: { desktop: '2 columnas', tablet: '1 columna', mobile: '1 columna' },
      navigationOutputs: [route],
      requiredCompanions: [],
      conflicts: [],
      assetSlots: [],
      required: true,
      fixed: true,
    }),
  ),
];
