/**
 * Contratos de las variantes de «Gestión Integral · Corporativa».
 *
 * Los slots de imagen se declaran opcionales: la template no empaqueta
 * fotografía de demostración, pero cada hueco sigue siendo visible y
 * gestionable desde Recursos visuales.
 */

import { inferSurfaceContext, type SectionVariant } from '../registry';

const NICHE = 'control-de-plagas';
const TEMPLATE = 'plagas-corporativa';

function variant(
  v: Omit<SectionVariant, 'nicheId' | 'schemaVersion' | 'sourceTemplateId' | 'surfaceContext'> & {
    schemaVersion?: string;
    sourceTemplateId?: string;
    surfaceContext?: SectionVariant['surfaceContext'];
  },
): SectionVariant {
  return {
    nicheId: NICHE,
    sourceTemplateId: v.sourceTemplateId ?? TEMPLATE,
    schemaVersion: v.schemaVersion ?? '1.0.0',
    layoutContract: {
      containment: v.sectionType === 'header' ? 'document' : 'section',
      overflow: v.sectionType === 'header' ? 'visible' : 'clip',
    },
    surfaceContext: v.surfaceContext ?? inferSurfaceContext(v),
    ...v,
  } as SectionVariant;
}

const STACK = { desktop: 'multi-columna', tablet: '2 columnas', mobile: '1 columna' };

export const PLAGAS_CORPORATIVA_VARIANTS: SectionVariant[] = [
  variant({
    id: 'co-header-01',
    sectionType: 'header',
    name: 'Cabecera técnica con descriptor',
    description: 'Marca con descriptor de actividad, navegación amplia, teléfono y CTA de propuesta.',
    requiredFields: ['business.name', 'navigation.items', 'navigation.primaryCta'],
    optionalFields: ['business.logo', 'business.phone'],
    collectionLimits: [{ collection: 'navigation.items', min: 3, max: 12 }],
    themeTokenCoverage: ['brandPrimary', 'surface', 'border', 'text'],
    responsiveContract: { desktop: 'marca · nav · acciones', tablet: 'marca · acciones', mobile: 'drawer' },
    navigationOutputs: ['/'],
    requiredCompanions: ['footer'],
    conflicts: [],
    assetSlots: [{ key: 'logo', ratio: 'libre', minWidth: 240, minHeight: 80, required: false }],
    required: true,
    fixed: true,
  }),
  variant({
    id: 'co-hero-01',
    sectionType: 'hero',
    name: 'Hero técnico con garantías y sectores',
    description: 'Copy de método y trazabilidad, doble CTA, fila de garantías y listado de sectores atendidos.',
    requiredFields: ['content.hero.title', 'content.hero.paragraph', 'content.hero.primaryCta'],
    optionalFields: ['content.hero.image', 'content.hero.note'],
    collectionLimits: [
      { collection: 'content.hero.microBenefits', min: 2, max: 4 },
      { collection: '@segments', min: 0, max: 16 },
    ],
    collectionItemFields: { '@segments': ['nombre'] },
    themeTokenCoverage: ['brandPrimary', 'heroBackground', 'text', 'textMuted'],
    responsiveContract: { desktop: '2 columnas + bandas', tablet: '2 columnas', mobile: 'copy → media → bandas' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'hero', ratio: '3:2', minWidth: 1800, minHeight: 1200, required: false }],
    required: true,
    fixed: false,
  }),
  variant({
    id: 'co-metodo-01',
    sectionType: 'process',
    name: 'Método en línea temporal',
    description: 'Fases del servicio con numeración continua; cada fase declara su entregable.',
    requiredFields: ['content.processSteps'],
    optionalFields: ['content.headings.process'],
    collectionLimits: [{ collection: 'content.processSteps', min: 3, max: 6 }],
    themeTokenCoverage: ['brandPrimary', 'surfaceAlt', 'borderStrong'],
    responsiveContract: { desktop: 'línea horizontal', tablet: '2 columnas', mobile: 'lista vertical' },
    navigationOutputs: ['#metodo', '@process'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'co-soluciones-01',
    sectionType: 'services',
    name: 'Soluciones con pestañas problema/sector',
    description: 'El mismo catálogo editable presentado por problema o por sector, sin duplicar contenido.',
    requiredFields: ['collections.@services'],
    optionalFields: ['collections.@segments', 'content.headings.services'],
    collectionLimits: [{ collection: '@services', min: 0, max: 20 }],
    collectionItemFields: { '@services': ['nombre', 'slug', 'resumen'] },
    themeTokenCoverage: ['brandPrimary', 'accent', 'surface', 'radiusCard'],
    responsiveContract: { desktop: '3 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#soluciones', '@services', '@servicesItem'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'soluciones.imagen', ratio: '4:3', minWidth: 1200, minHeight: 900, required: false }],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'co-sectores-01',
    sectionType: 'benefits',
    name: 'Sectores profesionales',
    description: 'Tarjetas por tipo de instalación con acceso a su metodología detallada.',
    requiredFields: ['collections.@segments'],
    optionalFields: [],
    collectionLimits: [{ collection: '@segments', min: 0, max: 16 }],
    collectionItemFields: { '@segments': ['nombre', 'resumen'] },
    themeTokenCoverage: ['brandPrimary', 'surface', 'border'],
    responsiveContract: { desktop: '3 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#sectores', '@segments', '@segmentsItem'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'sectores.imagen', ratio: '3:2', minWidth: 1200, minHeight: 800, required: false }],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'co-planes-01',
    sectionType: 'plans',
    name: 'Planes comparables con precio opcional',
    description:
      'Fila comparable con zonas alineadas: cabecera, precio, contenido y acción quedan a la misma altura en todas las tarjetas.',
    requiredFields: ['collections.@plans'],
    optionalFields: ['content.pricingNote', 'content.headings.plans'],
    collectionLimits: [{ collection: '@plans', min: 0, max: 6 }],
    collectionItemFields: { '@plans': ['nombre'] },
    themeTokenCoverage: ['brandPrimary', 'surface', 'surfaceHighlight', 'border'],
    responsiveContract: { desktop: '3 columnas alineadas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#planes', '@plans'],
    requiredCompanions: [],
    conflicts: ['packages'],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'co-diferencias-01',
    sectionType: 'benefits',
    name: 'Cómo trabajamos, partido',
    description: 'Bloque editorial con llamada a la acción junto a una rejilla de ventajas.',
    requiredFields: ['content.benefits'],
    optionalFields: ['content.headings.benefits'],
    collectionLimits: [{ collection: 'content.benefits', min: 2, max: 6 }],
    themeTokenCoverage: ['brandPrimary', 'surfaceAlt', 'border'],
    responsiveContract: { desktop: '40/60', tablet: 'apilado', mobile: 'apilado' },
    navigationOutputs: ['#diferencias'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'co-casos-01',
    sectionType: 'gallery',
    name: 'Casos de éxito',
    description: 'Referencias con sector, situación de partida y acceso al caso completo. Estado vacío diseñado.',
    requiredFields: ['collections.@cases'],
    optionalFields: ['content.headings.gallery'],
    collectionLimits: [{ collection: '@cases', min: 0, max: 30 }],
    collectionItemFields: { '@cases': ['titulo', 'problema'] },
    themeTokenCoverage: ['surface', 'radiusImage', 'brandPrimary'],
    responsiveContract: STACK,
    navigationOutputs: ['#casos', '@cases', '@casesItem'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [
      { key: 'casos-de-exito.imagen', ratio: '4:3', minWidth: 1200, minHeight: 900, required: false },
      { key: 'casos-de-exito.antes', ratio: '1:1', minWidth: 900, minHeight: 900, required: false },
      { key: 'casos-de-exito.despues', ratio: '1:1', minWidth: 900, minHeight: 900, required: false },
    ],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'co-testimonials-01',
    sectionType: 'testimonials',
    name: 'Referencias de clientes',
    description: 'Valoraciones con la firma alineada al pie de cada tarjeta.',
    requiredFields: ['testimonials'],
    optionalFields: ['content.headings.testimonials'],
    collectionLimits: [{ collection: 'testimonials', min: 1, max: 8 }],
    themeTokenCoverage: ['brandPrimary', 'star', 'surface'],
    responsiveContract: STACK,
    navigationOutputs: ['#referencias'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'co-faq-01',
    sectionType: 'faq',
    name: 'Preguntas frecuentes en acordeón',
    description: 'Acordeón accesible con varias respuestas abiertas a la vez.',
    requiredFields: ['faqs'],
    optionalFields: [],
    collectionLimits: [{ collection: 'faqs', min: 3, max: 16 }],
    themeTokenCoverage: ['border', 'surface', 'brandPrimary'],
    responsiveContract: { desktop: '1 columna ancha', tablet: '1 columna', mobile: '1 columna' },
    navigationOutputs: ['#faq', '@faq'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'co-finalcta-01',
    sectionType: 'finalCta',
    name: 'Cierre con propuesta',
    description: 'Banda de contraste con solicitud de propuesta y teléfono técnico.',
    requiredFields: ['content.finalCta'],
    optionalFields: ['business.phone'],
    collectionLimits: [],
    themeTokenCoverage: ['brandPrimary', 'surfaceInverse', 'textInverse'],
    responsiveContract: { desktop: 'horizontal', tablet: 'horizontal', mobile: 'apilado' },
    navigationOutputs: ['#propuesta', '@contact'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'co-footer-01',
    sectionType: 'footer',
    name: 'Pie con sectores y disponibilidad',
    description: 'Cuatro columnas sobre superficie inversa y franja legal con las tres políticas.',
    requiredFields: ['business.legalName', 'content.legal', 'business.openingHours'],
    optionalFields: ['collections.@segments', 'contact.socialLinks'],
    collectionLimits: [],
    themeTokenCoverage: ['surfaceInverse', 'textInverse', 'brandPrimary'],
    responsiveContract: STACK,
    navigationOutputs: ['@legalNotice', '/privacidad', '/cookies'],
    requiredCompanions: ['header'],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: true,
  }),

  ...(
    [
      ['co-page-soluciones-01', 'services', 'Página de soluciones', '@services', ['collections.@services']],
      ['co-page-sectores-01', 'benefits', 'Página de sectores profesionales', '@segments', ['collections.@segments']],
      ['co-page-proceso-01', 'process', 'Página del proceso de intervención', '@process', ['content.processSteps']],
      ['co-page-planes-01', 'plans', 'Página de planes de mantenimiento', '@plans', ['collections.@plans']],
      ['co-page-casos-01', 'gallery', 'Página de casos de éxito', '@cases', ['collections.@cases']],
      ['co-page-empresa-01', 'benefits', 'Página de empresa', '@about', ['content.benefits']],
      ['co-page-documentacion-01', 'contact', 'Página de documentación', '@documents', ['business.name']],
      ['co-page-plagas-01', 'services', 'Detalle técnico de plaga', '@catalogItem', ['collections.@catalog']],
      ['co-page-faq-01', 'faq', 'Página de preguntas frecuentes', '@faq', ['faqs']],
      ['co-page-propuesta-01', 'contact', 'Página de solicitud de propuesta', '@contact', ['forms']],
      ['co-page-legal-01', 'contact', 'Página legal', '@legalNotice', ['content.legal']],
    ] as const
  ).map(([id, sectionType, name, route, requiredFields]) =>
    variant({
      id,
      sectionType: sectionType as SectionVariant['sectionType'],
      name,
      description: 'Portada de sección, contenido propio, estados vacíos diseñados y llamada a la acción.',
      requiredFields: [...requiredFields],
      optionalFields: [],
      collectionLimits: [],
      themeTokenCoverage: ['surface', 'text', 'brandPrimary'],
      responsiveContract: { desktop: '2 columnas', tablet: '1 columna', mobile: '1 columna' },
      navigationOutputs: [route],
      requiredCompanions: [],
      conflicts: [],
      assetSlots: [],
      required: true,
      fixed: true,
    }),
  ),
];
