/**
 * Contratos de la segunda generación de familias visuales.
 *
 * Mismo criterio que en `profiles.ts`: cada variante declara **un único**
 * perfil, y por tanto solo puede componer webs de su familia. Lo que aportan
 * estas es variedad *dentro* de la familia —dos composiciones reales de hero y
 * de servicios— y las dos secciones que faltaban con calidad: resultados
 * (antes/después) y reserva propia.
 */

import type { SectionVariant } from '../registry';
import type { VariantMotion } from '../interactions';

type Spec = Omit<SectionVariant, 'nicheId' | 'schemaVersion' | 'layoutContract'> & {
  motion: VariantMotion;
  profile: 'premium' | 'minimal' | 'conventional';
};

export const PROFILE_B_MOTION: Record<string, VariantMotion> = {};
export const PROFILE_B_AFFINITY: Record<string, 'premium' | 'minimal' | 'conventional'> = {};

function declare(spec: Spec): SectionVariant {
  const { motion, profile, ...variant } = spec;
  PROFILE_B_MOTION[variant.id] = motion;
  PROFILE_B_AFFINITY[variant.id] = profile;
  return {
    ...variant,
    nicheId: 'compartida',
    schemaVersion: '1.0.0',
    layoutContract: { containment: 'section', overflow: 'clip' },
  };
}

/** Campos y límites que comparte cualquier sección de reserva. */
const BOOKING_FIELDS = ['booking', 'business.phone'];

export const PROFILE_B_VARIANTS: SectionVariant[] = [
  /* ============================= PREMIUM ================================= */
  declare({
    id: 'pf3-hero-02',
    profile: 'premium',
    sectionType: 'hero',
    sourceTemplateId: 'profile-premium',
    name: 'Hero editorial partido con panel invasor',
    description: 'La fotografía ocupa una columna a sangre y el texto vive en un panel oscuro que la invade.',
    requiredFields: ['content.hero.title', 'content.hero.paragraph', 'content.hero.image', 'content.hero.primaryCta'],
    optionalFields: ['business.tagline', 'content.hero.secondaryCta'],
    collectionLimits: [{ collection: 'content.hero.microBenefits', min: 0, max: 4 }],
    themeTokenCoverage: ['brandPrimary', 'surfaceInverse', 'textOnDark', 'fontDisplay', 'radiusImage'],
    surfaceContext: 'light',
    responsiveContract: { desktop: 'foto 58% + panel invasor', tablet: 'apilado', mobile: 'foto → panel' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: ['header'],
    conflicts: [],
    assetSlots: [{ key: 'hero', ratio: '4:3', minWidth: 1400, minHeight: 1000, required: true }],
    required: true,
    fixed: false,
    motion: { entry: 'rise', stagger: false, interactions: ['scroll-reveal', 'image-zoom', 'cta-micro'], tier: 'reference', entryAlternatives: ['reveal-up'] },
  }),
  declare({
    id: 'pf3-services-02',
    profile: 'premium',
    sectionType: 'services',
    sourceTemplateId: 'profile-premium',
    name: 'Servicios en fichas fotográficas de dos',
    description: 'Cada servicio ocupa media fila con fotografía grande, precio sobre la imagen e inclusiones debajo.',
    requiredFields: ['services'],
    optionalFields: ['content.headings.services'],
    collectionLimits: [{ collection: 'services', min: 2, max: 8 }],
    themeTokenCoverage: ['surfaceAlt', 'brandPrimary', 'fontDisplay', 'radiusImage'],
    surfaceContext: 'alternative',
    responsiveContract: { desktop: '2 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#servicios'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'service', ratio: '4:5', minWidth: 800, minHeight: 1000, required: false }],
    required: false,
    fixed: false,
    motion: { entry: 'blur-in', stagger: true, interactions: ['scroll-reveal', 'stagger', 'image-zoom'], tier: 'reference', entryAlternatives: ['reveal-up'] },
  }),
  declare({
    id: 'pf3-results-01',
    profile: 'premium',
    sectionType: 'transformations',
    sourceTemplateId: 'profile-premium',
    name: 'Resultados con comparación principal arrastrable',
    description: 'Una transformación manda a gran tamaño con tirador interactivo; las demás la acompañan debajo.',
    requiredFields: ['transformations'],
    optionalFields: ['content.headings.transformations'],
    collectionLimits: [{ collection: 'transformations', min: 1, max: 12 }],
    themeTokenCoverage: ['surfaceInverse', 'textOnDark', 'brandPrimary', 'fontDisplay', 'radiusImage'],
    surfaceContext: 'dark',
    responsiveContract: { desktop: 'principal + 3', tablet: 'principal + 2', mobile: 'apilado' },
    navigationOutputs: ['#resultados'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'transformation', ratio: '1:1', minWidth: 1000, minHeight: 1000, required: true }],
    required: false,
    fixed: false,
    motion: { entry: 'reveal-up', stagger: true, interactions: ['scroll-reveal', 'stagger', 'before-after'], tier: 'reference', entryAlternatives: ['blur-in'] },
  }),
  declare({
    id: 'pf3-booking-01',
    profile: 'premium',
    sectionType: 'booking',
    sourceTemplateId: 'profile-premium',
    name: 'Reserva editorial con datos del salón',
    description: 'Formulario a un lado y teléfono, dirección y horario al otro, sobre superficie alterna.',
    requiredFields: BOOKING_FIELDS,
    optionalFields: ['business.address', 'business.openingHours', 'content.headings.booking'],
    collectionLimits: [],
    themeTokenCoverage: ['surfaceAlt', 'brandPrimary', 'fontDisplay', 'border'],
    surfaceContext: 'alternative',
    responsiveContract: { desktop: '5/7', tablet: 'apilado', mobile: 'apilado' },
    navigationOutputs: ['#reserva'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: false, interactions: ['scroll-reveal', 'cta-micro'], tier: 'reference', entryAlternatives: ['rise'] },
  }),

  /* =========================== MINIMALISTA =============================== */
  declare({
    id: 'mn3-hero-02',
    profile: 'minimal',
    sectionType: 'hero',
    sourceTemplateId: 'profile-minimal',
    name: 'Hero de banda tipográfica',
    description: 'Titular ancho arriba y fotografía recortada en banda a todo lo ancho debajo; datos en filete.',
    requiredFields: ['content.hero.title', 'content.hero.paragraph', 'content.hero.primaryCta'],
    optionalFields: ['content.hero.image', 'content.hero.secondaryCta'],
    collectionLimits: [{ collection: 'content.hero.microBenefits', min: 0, max: 4 }],
    themeTokenCoverage: ['surface', 'border', 'textOnLight', 'textMutedOnLight'],
    surfaceContext: 'light',
    responsiveContract: { desktop: 'tipo + banda', tablet: 'tipo + banda', mobile: 'apilado' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: ['header'],
    conflicts: [],
    assetSlots: [{ key: 'hero', ratio: '21:9', minWidth: 1400, minHeight: 600, required: false }],
    required: true,
    fixed: false,
    motion: { entry: 'fade', stagger: false, interactions: ['scroll-reveal'], tier: 'reference', entryAlternatives: ['fade-down'] },
  }),
  declare({
    id: 'mn3-services-02',
    profile: 'minimal',
    sectionType: 'services',
    sourceTemplateId: 'profile-minimal',
    name: 'Servicios como índice con miniatura',
    description: 'Filas con miniatura cuadrada, nombre, resumen y precio alineado; separadas por filete.',
    requiredFields: ['services', 'navigation.primaryCta'],
    optionalFields: ['content.headings.services'],
    collectionLimits: [{ collection: 'services', min: 2, max: 12 }],
    themeTokenCoverage: ['surface', 'border', 'textOnLight', 'brandPrimary'],
    surfaceContext: 'light',
    responsiveContract: { desktop: 'miniatura · nombre · resumen · precio', tablet: 'miniatura · nombre · precio', mobile: 'apilado' },
    navigationOutputs: ['#servicios'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'service', ratio: '1:1', minWidth: 400, minHeight: 400, required: false }],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: true, interactions: ['scroll-reveal', 'stagger'], tier: 'reference', entryAlternatives: ['fade'] },
  }),
  declare({
    id: 'mn3-results-01',
    profile: 'minimal',
    sectionType: 'transformations',
    sourceTemplateId: 'profile-minimal',
    name: 'Resultados en rejilla estricta',
    description: 'Pares antes/después alineados en rejilla, con pie en filete y sin decoración.',
    requiredFields: ['transformations'],
    optionalFields: ['content.headings.transformations'],
    collectionLimits: [{ collection: 'transformations', min: 1, max: 12 }],
    themeTokenCoverage: ['surfaceAlt', 'border', 'textOnLight'],
    surfaceContext: 'alternative',
    responsiveContract: { desktop: '2 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#resultados'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'transformation', ratio: '1:1', minWidth: 800, minHeight: 800, required: true }],
    required: false,
    fixed: false,
    motion: { entry: 'fade', stagger: true, interactions: ['scroll-reveal', 'stagger', 'before-after'], tier: 'reference' },
  }),
  declare({
    id: 'mn3-booking-01',
    profile: 'minimal',
    sectionType: 'booking',
    sourceTemplateId: 'profile-minimal',
    name: 'Reserva como ficha de filetes',
    description: 'Enunciado y teléfono a un lado, formulario apilado sin tarjeta al otro.',
    requiredFields: BOOKING_FIELDS,
    optionalFields: ['content.headings.booking'],
    collectionLimits: [],
    themeTokenCoverage: ['surface', 'border', 'textOnLight'],
    surfaceContext: 'light',
    responsiveContract: { desktop: '4/8', tablet: 'apilado', mobile: 'apilado' },
    navigationOutputs: ['#reserva'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: false, interactions: ['scroll-reveal'], tier: 'reference' },
  }),

  /* =========================== CONVENCIONAL ============================== */
  declare({
    id: 'cv3-hero-02',
    profile: 'conventional',
    sectionType: 'hero',
    sourceTemplateId: 'profile-conventional',
    name: 'Hero con distintivo de valoración',
    description: 'Copy con ventajas marcadas y doble acción; fotografía recortada con la nota media flotando encima.',
    requiredFields: ['content.hero.title', 'content.hero.paragraph', 'content.hero.primaryCta'],
    optionalFields: ['business.tagline', 'content.hero.image', 'content.hero.secondaryCta', 'testimonials'],
    collectionLimits: [{ collection: 'content.hero.microBenefits', min: 0, max: 4 }],
    themeTokenCoverage: ['surface', 'brandPrimary', 'success', 'radiusCard', 'shadowFloat', 'star'],
    surfaceContext: 'light',
    responsiveContract: { desktop: '52/48', tablet: '50/50', mobile: 'copy → foto' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: ['header'],
    conflicts: [],
    assetSlots: [{ key: 'hero', ratio: '4:3', minWidth: 1000, minHeight: 750, required: false }],
    required: true,
    fixed: false,
    motion: { entry: 'slide-right', stagger: false, interactions: ['scroll-reveal', 'cta-micro'], tier: 'reference', entryAlternatives: ['fade-up', 'zoom-in'] },
  }),
  declare({
    id: 'cv3-services-02',
    profile: 'conventional',
    sectionType: 'services',
    sourceTemplateId: 'profile-conventional',
    name: 'Servicios en rejilla compacta de cinco',
    description: 'Cinco tarjetas estrechas con miniatura, precio y acción propia; densidad de catálogo.',
    requiredFields: ['services', 'navigation.primaryCta'],
    optionalFields: ['content.headings.services'],
    collectionLimits: [{ collection: 'services', min: 2, max: 10 }],
    themeTokenCoverage: ['surfaceAlt', 'brandPrimary', 'radiusCard', 'shadowCard'],
    surfaceContext: 'alternative',
    responsiveContract: { desktop: '5 columnas', tablet: '3 columnas', mobile: '2 columnas' },
    navigationOutputs: ['#servicios'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'service', ratio: '4:3', minWidth: 600, minHeight: 450, required: false }],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: true, interactions: ['scroll-reveal', 'stagger', 'card-hover', 'cta-micro'], tier: 'reference', entryAlternatives: ['zoom-in'] },
  }),
  declare({
    id: 'cv3-results-01',
    profile: 'conventional',
    sectionType: 'transformations',
    sourceTemplateId: 'profile-conventional',
    name: 'Resultados en tarjetas etiquetadas',
    description: 'Tres comparaciones en tarjeta con etiqueta antes/después visible y llamada a reservar debajo.',
    requiredFields: ['transformations', 'navigation.primaryCta'],
    optionalFields: ['content.headings.transformations'],
    collectionLimits: [{ collection: 'transformations', min: 1, max: 9 }],
    themeTokenCoverage: ['surface', 'brandPrimary', 'radiusCard', 'shadowCard'],
    surfaceContext: 'light',
    responsiveContract: { desktop: '3 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#resultados', '/galeria'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'transformation', ratio: '1:1', minWidth: 600, minHeight: 600, required: true }],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: true, interactions: ['scroll-reveal', 'stagger', 'card-hover', 'before-after'], tier: 'reference', entryAlternatives: ['zoom-in'] },
  }),
  declare({
    id: 'cv3-booking-01',
    profile: 'conventional',
    sectionType: 'booking',
    sourceTemplateId: 'profile-conventional',
    name: 'Reserva en tarjeta elevada con WhatsApp',
    description: 'Tarjeta blanca sobre superficie alterna: reclamo y contacto directo a un lado, formulario al otro.',
    requiredFields: BOOKING_FIELDS,
    optionalFields: ['business.whatsapp', 'content.headings.booking'],
    collectionLimits: [],
    themeTokenCoverage: ['surfaceAlt', 'brandPrimary', 'radiusCard', 'shadowFloat', 'whatsapp'],
    surfaceContext: 'alternative',
    responsiveContract: { desktop: 'tarjeta 4/8', tablet: 'apilado', mobile: 'apilado' },
    navigationOutputs: ['#reserva'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: false, interactions: ['scroll-reveal', 'cta-micro'], tier: 'reference', entryAlternatives: ['zoom-in'] },
  }),
  declare({
    id: 'pf3-benefits-01',
    profile: 'premium',
    sectionType: 'benefits',
    sourceTemplateId: 'profile-premium',
    name: 'Ventajas numeradas en filete',
    description: 'Cuatro garantías en filas numeradas, sin iconos ni tarjetas.',
    requiredFields: ['content.benefits'],
    optionalFields: [],
    collectionLimits: [{ collection: 'content.benefits', min: 2, max: 6 }],
    themeTokenCoverage: ['surface', 'border', 'fontDisplay', 'brandPrimary'],
    surfaceContext: 'light',
    responsiveContract: { desktop: '4 filas', tablet: '2 columnas', mobile: 'lista' },
    navigationOutputs: ['#ventajas'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: true, interactions: ['scroll-reveal', 'stagger'], tier: 'reference' },
  }),
  declare({
    id: 'mn3-benefits-01',
    profile: 'minimal',
    sectionType: 'benefits',
    sourceTemplateId: 'profile-minimal',
    name: 'Ventajas en fila de filetes',
    description: 'Fila de datos separada por filetes verticales, sin decoración.',
    requiredFields: ['content.benefits'],
    optionalFields: [],
    collectionLimits: [{ collection: 'content.benefits', min: 2, max: 6 }],
    themeTokenCoverage: ['surface', 'border', 'textMutedOnLight'],
    surfaceContext: 'light',
    responsiveContract: { desktop: 'fila', tablet: '2 columnas', mobile: 'lista' },
    navigationOutputs: ['#ventajas'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade', stagger: true, interactions: ['scroll-reveal', 'stagger'], tier: 'reference' },
  }),
  declare({
    id: 'cv3-benefits-01',
    profile: 'conventional',
    sectionType: 'benefits',
    sourceTemplateId: 'profile-conventional',
    name: 'Franja de confianza en color de marca',
    description: 'Garantías con marca de verificación sobre el color de marca.',
    requiredFields: ['content.benefits'],
    optionalFields: [],
    collectionLimits: [{ collection: 'content.benefits', min: 2, max: 6 }],
    themeTokenCoverage: ['brandPrimary', 'textOnBrand'],
    surfaceContext: 'brand',
    responsiveContract: { desktop: '4 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#ventajas'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: true, interactions: ['scroll-reveal', 'stagger'], tier: 'reference' },
  }),
];
