/**
 * Contratos de las tres familias visuales.
 *
 * Cada variante declara **un único** perfil. Es la regla que hace que Premium,
 * Minimalista y Convencional no se contaminen: una composición editorial a
 * sangre no entra en una web minimalista aunque técnicamente sea compatible.
 *
 * Son las variantes de referencia del catálogo: el generador las prefiere sobre
 * la biblioteca heredada porque son las únicas que garantizan tres direcciones
 * reconociblemente distintas.
 */

import type { SectionVariant } from '../registry';
import type { VariantMotion } from '../interactions';

type Spec = Omit<SectionVariant, 'nicheId' | 'schemaVersion' | 'layoutContract'> & {
  motion: VariantMotion;
  profile: 'premium' | 'minimal' | 'conventional';
};

/** Motion y perfil declarados, indexados por id de variante. */
export const PROFILE_VARIANT_MOTION: Record<string, VariantMotion> = {};
export const PROFILE_VARIANT_AFFINITY: Record<string, 'premium' | 'minimal' | 'conventional'> = {};

function declare(spec: Spec): SectionVariant {
  const { motion, profile, ...variant } = spec;
  PROFILE_VARIANT_MOTION[variant.id] = motion;
  PROFILE_VARIANT_AFFINITY[variant.id] = profile;
  return {
    ...variant,
    nicheId: 'compartida',
    schemaVersion: '1.0.0',
    layoutContract: {
      containment: variant.sectionType === 'header' ? 'document' : 'section',
      overflow: variant.sectionType === 'header' ? 'visible' : 'clip',
    },
  };
}

const NAV_LIMIT = { collection: 'navigation.items', min: 3, max: 8 };

/* ========================================================================== */
/*  PREMIUM                                                                   */
/* ========================================================================== */

const PREMIUM: SectionVariant[] = [
  declare({
    id: 'pf2-header-01',
    profile: 'premium',
    sectionType: 'header',
    sourceTemplateId: 'profile-premium',
    name: 'Cabecera translúcida sobre la fotografía',
    description: 'Se integra en el hero y se vuelve sólida al desplazarse. Marca centrada y navegación en versalitas.',
    requiredFields: ['business.name', 'navigation.items', 'navigation.primaryCta'],
    optionalFields: [],
    collectionLimits: [NAV_LIMIT],
    themeTokenCoverage: ['brandPrimary', 'surfaceInverse', 'textOnDark', 'textMutedOnDark'],
    surfaceContext: 'dark',
    responsiveContract: { desktop: 'marca · nav · CTA', tablet: 'marca · CTA', mobile: 'drawer' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: ['hero', 'footer'],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: true,
    motion: { entry: 'none', stagger: false, interactions: ['sticky-header', 'cta-micro'], tier: 'reference' },
  }),
  declare({
    id: 'pf2-hero-01',
    profile: 'premium',
    sectionType: 'hero',
    sourceTemplateId: 'profile-premium',
    name: 'Hero a sangre con velo en degradado',
    description:
      'La fotografía ocupa la pantalla completa; el titular en display vive sobre ella, con filete y marcas en la base.',
    requiredFields: ['content.hero.title', 'content.hero.paragraph', 'content.hero.image', 'content.hero.primaryCta'],
    optionalFields: ['business.tagline', 'content.hero.secondaryCta'],
    collectionLimits: [{ collection: 'content.hero.microBenefits', min: 0, max: 4 }],
    themeTokenCoverage: ['brandPrimary', 'surfaceInverse', 'textOnDark', 'textMutedOnDark', 'fontDisplay'],
    surfaceContext: 'image',
    responsiveContract: { desktop: 'imagen a sangre + copy abajo', tablet: 'igual, menor altura', mobile: 'copy sobre foto' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: ['header'],
    conflicts: [],
    assetSlots: [{ key: 'hero', ratio: '16:10', minWidth: 1800, minHeight: 1100, required: true }],
    required: true,
    fixed: false,
    motion: { entry: 'reveal-up', stagger: false, interactions: ['scroll-reveal', 'image-zoom'], tier: 'reference', entryAlternatives: ['blur-in', 'rise'] },
  }),
  declare({
    id: 'pf2-services-01',
    profile: 'premium',
    sectionType: 'services',
    sourceTemplateId: 'profile-premium',
    name: 'Servicios en filas editoriales alternadas',
    description: 'Cada servicio ocupa una fila con imagen a un lado y numeración grande; la alternancia rompe la lista.',
    requiredFields: ['services'],
    optionalFields: ['content.headings.services'],
    collectionLimits: [{ collection: 'services', min: 2, max: 8 }],
    themeTokenCoverage: ['brandPrimary', 'surface', 'surfaceAlt', 'fontDisplay', 'radiusImage'],
    surfaceContext: 'light',
    responsiveContract: { desktop: 'filas 6/5 alternadas', tablet: 'filas apiladas', mobile: '1 columna' },
    navigationOutputs: ['#servicios'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'service', ratio: '4:3', minWidth: 1000, minHeight: 750, required: false }],
    required: false,
    fixed: false,
    motion: { entry: 'blur-in', stagger: true, interactions: ['scroll-reveal', 'stagger', 'image-zoom'], tier: 'reference', entryAlternatives: ['reveal-up'] },
  }),
  declare({
    id: 'pf2-process-01',
    profile: 'premium',
    sectionType: 'process',
    sourceTemplateId: 'profile-premium',
    name: 'Proceso en escalera descendente',
    description: 'Cada paso baja un peldaño respecto al anterior; la numeración grande marca el recorrido.',
    requiredFields: ['content.processSteps'],
    optionalFields: ['content.headings.process'],
    collectionLimits: [{ collection: 'content.processSteps', min: 2, max: 6 }],
    themeTokenCoverage: ['surfaceAlt', 'brandPrimary', 'fontDisplay', 'textMutedOnLight'],
    surfaceContext: 'alternative',
    responsiveContract: { desktop: 'escalera', tablet: 'escalera corta', mobile: 'lista' },
    navigationOutputs: ['#proceso'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'reveal-up', stagger: true, interactions: ['scroll-reveal', 'stagger'], tier: 'reference', entryAlternatives: ['rise'] },
  }),
  declare({
    id: 'pf2-gallery-01',
    profile: 'premium',
    sectionType: 'gallery',
    sourceTemplateId: 'profile-premium',
    name: 'Mosaico irregular con pieza destacada',
    description: 'La primera imagen ocupa el doble de ancho; el resto forma un mosaico sin bordes.',
    requiredFields: ['gallery'],
    optionalFields: ['content.headings.gallery'],
    collectionLimits: [{ collection: 'gallery', min: 3, max: 30 }],
    themeTokenCoverage: ['surface', 'radiusImage', 'fontDisplay'],
    surfaceContext: 'light',
    responsiveContract: { desktop: 'mosaico 3 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#galeria'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'gallery', ratio: '4:3', minWidth: 900, minHeight: 675, required: true }],
    required: false,
    fixed: false,
    motion: { entry: 'fade', stagger: true, interactions: ['scroll-reveal', 'stagger', 'image-zoom'], tier: 'reference', entryAlternatives: ['blur-in'] },
  }),
  declare({
    id: 'pf2-quotes-01',
    profile: 'premium',
    sectionType: 'testimonials',
    sourceTemplateId: 'profile-premium',
    name: 'Cita principal a gran tamaño',
    description: 'Una reseña tratada como cita editorial sobre fondo oscuro, con dos secundarias debajo.',
    requiredFields: ['testimonials'],
    optionalFields: [],
    collectionLimits: [{ collection: 'testimonials', min: 1, max: 12 }],
    themeTokenCoverage: ['surfaceInverse', 'textOnDark', 'fontDisplay', 'brandPrimary'],
    surfaceContext: 'dark',
    responsiveContract: { desktop: 'cita + 2 columnas', tablet: 'cita + 2', mobile: 'apilado' },
    navigationOutputs: ['#opiniones'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'blur-in', stagger: true, interactions: ['scroll-reveal', 'stagger'], tier: 'reference', entryAlternatives: ['reveal-up'] },
  }),
  declare({
    id: 'pf2-faq-01',
    profile: 'premium',
    sectionType: 'faq',
    sourceTemplateId: 'profile-premium',
    name: 'Preguntas en dos columnas con enunciado',
    description: 'Título y contexto a la izquierda, acordeón de una sola respuesta abierta a la derecha.',
    requiredFields: ['faqs'],
    optionalFields: ['content.headings.faq'],
    collectionLimits: [{ collection: 'faqs', min: 2, max: 12 }],
    themeTokenCoverage: ['surface', 'border', 'fontDisplay', 'brandPrimary'],
    surfaceContext: 'light',
    responsiveContract: { desktop: '5/7', tablet: 'apilado', mobile: 'apilado' },
    navigationOutputs: ['#faq'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: false, interactions: ['scroll-reveal', 'accordion'], tier: 'reference' },
  }),
  declare({
    id: 'pf2-contact-01',
    profile: 'premium',
    sectionType: 'contact',
    sourceTemplateId: 'profile-premium',
    name: 'Contacto oscuro con datos tipográficos',
    description: 'Invitación a la izquierda y los datos del negocio como fichas de definición a la derecha.',
    requiredFields: ['business.phone'],
    optionalFields: ['business.email', 'business.address', 'business.openingHours', 'content.headings.contact'],
    collectionLimits: [],
    themeTokenCoverage: ['surfaceInverse', 'textOnDark', 'textMutedOnDark', 'brandPrimary'],
    surfaceContext: 'dark',
    responsiveContract: { desktop: '5/7', tablet: 'apilado', mobile: 'apilado' },
    navigationOutputs: ['#contacto'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'reveal-up', stagger: false, interactions: ['scroll-reveal', 'cta-micro'], tier: 'reference' },
  }),
  declare({
    id: 'pf2-final-01',
    profile: 'premium',
    sectionType: 'finalCta',
    sourceTemplateId: 'profile-premium',
    name: 'Cierre editorial sobre superficie oscura',
    description: 'Banda oscura con titular en display a la izquierda y una sola acción a la derecha.',
    requiredFields: ['content.finalCta'],
    optionalFields: [],
    collectionLimits: [],
    themeTokenCoverage: ['surfaceInverse', 'textOnDark', 'brandPrimary'],
    surfaceContext: 'dark',
    responsiveContract: { desktop: 'texto + acción', tablet: 'apilado', mobile: 'apilado' },
    navigationOutputs: [],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'rise', stagger: false, interactions: ['scroll-reveal', 'cta-micro'], tier: 'reference', entryAlternatives: ['reveal-up'] },
  }),
  declare({
    id: 'pf2-footer-01',
    profile: 'premium',
    sectionType: 'footer',
    sourceTemplateId: 'profile-premium',
    name: 'Pie editorial con marca grande',
    description: 'Marca a gran tamaño, tres columnas de datos y franja legal.',
    requiredFields: ['business.legalName', 'content.legal'],
    optionalFields: ['business.openingHours'],
    collectionLimits: [],
    themeTokenCoverage: ['surfaceInverseSoft', 'textOnDark', 'brandPrimary'],
    surfaceContext: 'dark',
    responsiveContract: { desktop: '3 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['/aviso-legal', '/privacidad', '/cookies'],
    requiredCompanions: ['header'],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: true,
    motion: { entry: 'none', stagger: false, interactions: [], tier: 'reference' },
  }),
];

/* ========================================================================== */
/*  MINIMALISTA                                                               */
/* ========================================================================== */

const MINIMAL: SectionVariant[] = [
  declare({
    id: 'mn2-header-01',
    profile: 'minimal',
    sectionType: 'header',
    sourceTemplateId: 'profile-minimal',
    name: 'Cabecera hairline compacta',
    description: 'Marca a la izquierda, navegación con subrayado al pasar y una acción en texto. Un solo filete.',
    requiredFields: ['business.name', 'navigation.items', 'navigation.primaryCta'],
    optionalFields: [],
    collectionLimits: [NAV_LIMIT],
    themeTokenCoverage: ['surface', 'border', 'textOnLight', 'brandPrimary'],
    surfaceContext: 'light',
    responsiveContract: { desktop: 'marca · nav · acción', tablet: 'marca · acción', mobile: 'drawer' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: ['footer'],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: true,
    motion: { entry: 'none', stagger: false, interactions: ['sticky-header'], tier: 'reference' },
  }),
  declare({
    id: 'mn2-hero-01',
    profile: 'minimal',
    sectionType: 'hero',
    sourceTemplateId: 'profile-minimal',
    name: 'Hero tipográfico con chip lateral',
    description:
      'Titular enorme en rejilla 7/4, imagen reducida a un chip desplazado y fila de datos separada por filetes.',
    requiredFields: ['content.hero.title', 'content.hero.paragraph', 'content.hero.primaryCta'],
    optionalFields: ['content.hero.image', 'content.hero.secondaryCta'],
    collectionLimits: [{ collection: 'content.hero.microBenefits', min: 0, max: 4 }],
    themeTokenCoverage: ['surface', 'border', 'textOnLight', 'textMutedOnLight'],
    surfaceContext: 'light',
    responsiveContract: { desktop: '7/4 asimétrico', tablet: 'apilado', mobile: '1 columna' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: ['header'],
    conflicts: [],
    assetSlots: [{ key: 'hero', ratio: '4:5', minWidth: 900, minHeight: 1100, required: false }],
    required: true,
    fixed: false,
    motion: { entry: 'fade', stagger: false, interactions: ['scroll-reveal'], tier: 'reference', entryAlternatives: ['fade-down'] },
  }),
  declare({
    id: 'mn2-services-01',
    profile: 'minimal',
    sectionType: 'services',
    sourceTemplateId: 'profile-minimal',
    name: 'Servicios como tabla con filetes',
    description: 'Filas separadas por hairline, precio alineado a la derecha y desplazamiento del texto al pasar.',
    requiredFields: ['services'],
    optionalFields: ['content.headings.services'],
    collectionLimits: [{ collection: 'services', min: 2, max: 12 }],
    themeTokenCoverage: ['surfaceAlt', 'border', 'textOnLight', 'brandPrimary'],
    surfaceContext: 'alternative',
    responsiveContract: { desktop: 'nombre · resumen · precio', tablet: 'nombre · precio', mobile: 'nombre · precio' },
    navigationOutputs: ['#servicios'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: true, interactions: ['scroll-reveal', 'stagger'], tier: 'reference', entryAlternatives: ['fade'] },
  }),
  declare({
    id: 'mn2-process-01',
    profile: 'minimal',
    sectionType: 'process',
    sourceTemplateId: 'profile-minimal',
    name: 'Proceso como línea numerada',
    description: 'Pasos en fila separados por filetes verticales; número pequeño, sin iconos ni tarjetas.',
    requiredFields: ['content.processSteps'],
    optionalFields: ['content.headings.process'],
    collectionLimits: [{ collection: 'content.processSteps', min: 2, max: 6 }],
    themeTokenCoverage: ['surface', 'border', 'textOnLight', 'textMutedOnLight'],
    surfaceContext: 'light',
    responsiveContract: { desktop: 'fila', tablet: '2 columnas', mobile: 'lista' },
    navigationOutputs: ['#proceso'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: true, interactions: ['scroll-reveal', 'stagger'], tier: 'reference', entryAlternatives: ['fade'] },
  }),
  declare({
    id: 'mn2-gallery-01',
    profile: 'minimal',
    sectionType: 'gallery',
    sourceTemplateId: 'profile-minimal',
    name: 'Rejilla regular sin pies',
    description: 'Cuatro columnas iguales, sin sombra, sin borde y sin texto: solo las imágenes.',
    requiredFields: ['gallery'],
    optionalFields: ['content.headings.gallery'],
    collectionLimits: [{ collection: 'gallery', min: 3, max: 30 }],
    themeTokenCoverage: ['surface', 'border'],
    surfaceContext: 'light',
    responsiveContract: { desktop: '4 columnas', tablet: '3 columnas', mobile: '2 columnas' },
    navigationOutputs: ['#galeria'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'gallery', ratio: '1:1', minWidth: 700, minHeight: 700, required: true }],
    required: false,
    fixed: false,
    motion: { entry: 'fade', stagger: true, interactions: ['scroll-reveal', 'stagger'], tier: 'reference' },
  }),
  declare({
    id: 'mn2-quotes-01',
    profile: 'minimal',
    sectionType: 'testimonials',
    sourceTemplateId: 'profile-minimal',
    name: 'Reseñas como columnas de texto',
    description: 'Tres columnas separadas por filetes, sin estrellas, sin avatar y sin tarjeta.',
    requiredFields: ['testimonials'],
    optionalFields: [],
    collectionLimits: [{ collection: 'testimonials', min: 2, max: 12 }],
    themeTokenCoverage: ['surfaceAlt', 'border', 'textOnLight'],
    surfaceContext: 'alternative',
    responsiveContract: { desktop: '3 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#opiniones'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade', stagger: true, interactions: ['scroll-reveal', 'stagger'], tier: 'reference', entryAlternatives: ['fade-up'] },
  }),
  declare({
    id: 'mn2-faq-01',
    profile: 'minimal',
    sectionType: 'faq',
    sourceTemplateId: 'profile-minimal',
    name: 'Preguntas a ancho completo con filetes',
    description: 'Lista a todo el ancho, chevron a la derecha y varias respuestas abiertas a la vez.',
    requiredFields: ['faqs'],
    optionalFields: ['content.headings.faq'],
    collectionLimits: [{ collection: 'faqs', min: 2, max: 14 }],
    themeTokenCoverage: ['surface', 'border', 'textOnLight'],
    surfaceContext: 'light',
    responsiveContract: { desktop: 'ancho completo', tablet: 'ancho completo', mobile: 'ancho completo' },
    navigationOutputs: ['#faq'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade', stagger: false, interactions: ['scroll-reveal', 'accordion'], tier: 'reference' },
  }),
  declare({
    id: 'mn2-contact-01',
    profile: 'minimal',
    sectionType: 'contact',
    sourceTemplateId: 'profile-minimal',
    name: 'Contacto como ficha de datos',
    description: 'Filas etiqueta/valor separadas por filetes: etiqueta pequeña en versalitas, valor grande.',
    requiredFields: ['business.phone'],
    optionalFields: ['business.email', 'business.address', 'business.openingHours', 'content.headings.contact'],
    collectionLimits: [],
    themeTokenCoverage: ['surface', 'border', 'textOnLight', 'textMutedOnLight'],
    surfaceContext: 'light',
    responsiveContract: { desktop: 'filas etiqueta/valor', tablet: 'filas', mobile: 'apilado' },
    navigationOutputs: ['#contacto'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: false, interactions: ['scroll-reveal'], tier: 'reference' },
  }),
  declare({
    id: 'mn2-final-01',
    profile: 'minimal',
    sectionType: 'finalCta',
    sourceTemplateId: 'profile-minimal',
    name: 'Cierre centrado y breve',
    description: 'Una frase centrada y una sola acción. Sin fondo ni decoración.',
    requiredFields: ['content.finalCta'],
    optionalFields: [],
    collectionLimits: [],
    themeTokenCoverage: ['surface', 'textOnLight'],
    surfaceContext: 'light',
    responsiveContract: { desktop: 'centrado', tablet: 'centrado', mobile: 'centrado' },
    navigationOutputs: [],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade', stagger: false, interactions: ['scroll-reveal'], tier: 'reference' },
  }),
  declare({
    id: 'mn2-footer-01',
    profile: 'minimal',
    sectionType: 'footer',
    sourceTemplateId: 'profile-minimal',
    name: 'Pie de una sola línea',
    description: 'Marca y contacto a un lado, enlaces legales al otro, y una franja fina de copyright.',
    requiredFields: ['business.legalName', 'content.legal'],
    optionalFields: [],
    collectionLimits: [],
    themeTokenCoverage: ['surface', 'border', 'textMutedOnLight'],
    surfaceContext: 'light',
    responsiveContract: { desktop: '2 bloques', tablet: '2 bloques', mobile: 'apilado' },
    navigationOutputs: ['/aviso-legal', '/privacidad', '/cookies'],
    requiredCompanions: ['header'],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: true,
    motion: { entry: 'none', stagger: false, interactions: [], tier: 'reference' },
  }),
];

/* ========================================================================== */
/*  CONVENCIONAL                                                              */
/* ========================================================================== */

const CONVENTIONAL: SectionVariant[] = [
  declare({
    id: 'cv2-header-01',
    profile: 'conventional',
    sectionType: 'header',
    sourceTemplateId: 'profile-conventional',
    name: 'Cabecera de dos filas con barra de utilidad',
    description: 'Arriba teléfono, horario y cobertura; abajo marca, navegación subrayada y botón de acción.',
    requiredFields: ['business.name', 'business.phone', 'navigation.items', 'navigation.primaryCta'],
    optionalFields: ['business.openingHours'],
    collectionLimits: [NAV_LIMIT],
    themeTokenCoverage: ['surface', 'surfaceInverse', 'brandPrimary', 'shadowCard'],
    surfaceContext: 'light',
    responsiveContract: { desktop: 'dos filas completas', tablet: 'utilidad + marca', mobile: 'drawer' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: ['footer'],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: true,
    motion: { entry: 'none', stagger: false, interactions: ['sticky-header', 'cta-micro'], tier: 'reference' },
  }),
  declare({
    id: 'cv2-hero-01',
    profile: 'conventional',
    sectionType: 'hero',
    sourceTemplateId: 'profile-conventional',
    name: 'Hero partido con ventajas y doble acción',
    description: 'Copy con lista de ventajas marcadas y dos botones a la izquierda; tarjeta de imagen elevada a la derecha.',
    requiredFields: ['content.hero.title', 'content.hero.paragraph', 'content.hero.primaryCta'],
    optionalFields: ['content.hero.image', 'content.hero.secondaryCta'],
    collectionLimits: [{ collection: 'content.hero.microBenefits', min: 0, max: 4 }],
    themeTokenCoverage: ['surface', 'brandPrimary', 'success', 'radiusCard', 'shadowFloat'],
    surfaceContext: 'light',
    responsiveContract: { desktop: '50/50', tablet: '50/50', mobile: 'copy → imagen' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: ['header'],
    conflicts: [],
    assetSlots: [{ key: 'hero', ratio: '4:3', minWidth: 1200, minHeight: 900, required: false }],
    required: true,
    fixed: false,
    motion: { entry: 'slide-right', stagger: false, interactions: ['scroll-reveal', 'cta-micro'], tier: 'reference', entryAlternatives: ['fade-up', 'zoom-in'] },
  }),
  declare({
    id: 'cv2-trust-01',
    profile: 'conventional',
    sectionType: 'benefits',
    sourceTemplateId: 'profile-conventional',
    name: 'Barra de confianza en color de marca',
    description: 'Franja horizontal con las garantías del negocio, justo debajo del hero.',
    requiredFields: ['content.benefits'],
    optionalFields: [],
    collectionLimits: [{ collection: 'content.benefits', min: 2, max: 6 }],
    themeTokenCoverage: ['brandPrimary', 'textOnBrand'],
    surfaceContext: 'brand',
    responsiveContract: { desktop: '4 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: [],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: true, interactions: ['scroll-reveal', 'stagger'], tier: 'reference', entryAlternatives: ['zoom-in'] },
  }),
  declare({
    id: 'cv2-services-01',
    profile: 'conventional',
    sectionType: 'services',
    sourceTemplateId: 'profile-conventional',
    name: 'Servicios en tarjetas con precio y acción',
    description: 'Rejilla de tres con imagen, inclusiones marcadas, precio visible y botón propio por tarjeta.',
    requiredFields: ['services', 'navigation.primaryCta'],
    optionalFields: ['content.headings.services'],
    collectionLimits: [{ collection: 'services', min: 2, max: 6 }],
    themeTokenCoverage: ['surfaceAlt', 'brandPrimary', 'success', 'radiusCard', 'shadowCard'],
    surfaceContext: 'alternative',
    responsiveContract: { desktop: '3 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#servicios'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'service', ratio: '4:3', minWidth: 900, minHeight: 675, required: false }],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: true, interactions: ['scroll-reveal', 'stagger', 'card-hover', 'cta-micro'], tier: 'reference', entryAlternatives: ['zoom-in', 'slide-right'] },
  }),
  declare({
    id: 'cv2-process-01',
    profile: 'conventional',
    sectionType: 'process',
    sourceTemplateId: 'profile-conventional',
    name: 'Proceso en cuatro tarjetas numeradas',
    description: 'Rejilla de cuatro con distintivo numérico en color de marca y conector entre tarjetas.',
    requiredFields: ['content.processSteps'],
    optionalFields: ['content.headings.process'],
    collectionLimits: [{ collection: 'content.processSteps', min: 2, max: 4 }],
    themeTokenCoverage: ['surfaceAlt', 'brandPrimary', 'radiusCard', 'shadowCard'],
    surfaceContext: 'alternative',
    responsiveContract: { desktop: '4 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#proceso'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: true, interactions: ['scroll-reveal', 'stagger', 'card-hover'], tier: 'reference', entryAlternatives: ['zoom-in', 'slide-right'] },
  }),
  declare({
    id: 'cv2-gallery-01',
    profile: 'conventional',
    sectionType: 'gallery',
    sourceTemplateId: 'profile-conventional',
    name: 'Galería en tarjetas con pie visible',
    description: 'Rejilla de tres con nombre del servicio y descripción bajo cada imagen.',
    requiredFields: ['gallery'],
    optionalFields: ['content.headings.gallery'],
    collectionLimits: [{ collection: 'gallery', min: 3, max: 30 }],
    themeTokenCoverage: ['surfaceAlt', 'radiusCard', 'shadowCard', 'brandPrimary'],
    surfaceContext: 'alternative',
    responsiveContract: { desktop: '3 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#galeria'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'gallery', ratio: '4:3', minWidth: 800, minHeight: 600, required: true }],
    required: false,
    fixed: false,
    motion: { entry: 'zoom-in', stagger: true, interactions: ['scroll-reveal', 'stagger', 'card-hover', 'image-zoom'], tier: 'reference', entryAlternatives: ['fade-up'] },
  }),
  declare({
    id: 'cv2-quotes-01',
    profile: 'conventional',
    sectionType: 'testimonials',
    sourceTemplateId: 'profile-conventional',
    name: 'Opiniones con nota media destacada',
    description: 'Media calculada con estrellas en la cabecera y reseñas en tarjetas de tres.',
    requiredFields: ['testimonials'],
    optionalFields: [],
    collectionLimits: [{ collection: 'testimonials', min: 2, max: 12 }],
    themeTokenCoverage: ['surface', 'brandPrimary', 'radiusCard', 'shadowCard'],
    surfaceContext: 'light',
    responsiveContract: { desktop: '3 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#opiniones'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: true, interactions: ['scroll-reveal', 'stagger', 'card-hover'], tier: 'reference', entryAlternatives: ['zoom-in'] },
  }),
  declare({
    id: 'cv2-faq-01',
    profile: 'conventional',
    sectionType: 'faq',
    sourceTemplateId: 'profile-conventional',
    name: 'Preguntas en panel con llamada final',
    description: 'Acordeón dentro de una tarjeta elevada y una línea de contacto debajo para lo no resuelto.',
    requiredFields: ['faqs', 'navigation.primaryCta'],
    optionalFields: ['content.headings.faq'],
    collectionLimits: [{ collection: 'faqs', min: 2, max: 12 }],
    themeTokenCoverage: ['surface', 'radiusCard', 'shadowCard', 'brandPrimary'],
    surfaceContext: 'light',
    responsiveContract: { desktop: 'panel centrado', tablet: 'panel', mobile: 'panel' },
    navigationOutputs: ['#faq'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: false, interactions: ['scroll-reveal', 'accordion', 'cta-micro'], tier: 'reference' },
  }),
  declare({
    id: 'cv2-contact-01',
    profile: 'conventional',
    sectionType: 'contact',
    sourceTemplateId: 'profile-conventional',
    name: 'Contacto en tarjetas con icono',
    description: 'Una tarjeta por vía —teléfono, correo, dirección y horario— con acción directa donde la hay.',
    requiredFields: ['business.phone'],
    optionalFields: ['business.email', 'business.address', 'business.openingHours', 'content.headings.contact'],
    collectionLimits: [],
    themeTokenCoverage: ['surfaceAlt', 'brandPrimary', 'radiusCard', 'shadowCard'],
    surfaceContext: 'alternative',
    responsiveContract: { desktop: '4 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#contacto'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: true, interactions: ['scroll-reveal', 'stagger', 'card-hover', 'cta-micro'], tier: 'reference', entryAlternatives: ['zoom-in'] },
  }),
  declare({
    id: 'cv2-final-01',
    profile: 'conventional',
    sectionType: 'finalCta',
    sourceTemplateId: 'profile-conventional',
    name: 'Cierre en color de marca con teléfono',
    description: 'Banda de marca con acción principal y el teléfono como alternativa inmediata.',
    requiredFields: ['content.finalCta', 'business.phone'],
    optionalFields: [],
    collectionLimits: [],
    themeTokenCoverage: ['brandPrimary', 'textOnBrand'],
    surfaceContext: 'brand',
    responsiveContract: { desktop: 'texto + acciones', tablet: 'apilado', mobile: 'apilado' },
    navigationOutputs: [],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
    motion: { entry: 'fade-up', stagger: false, interactions: ['scroll-reveal', 'cta-micro'], tier: 'reference' },
  }),
  declare({
    id: 'cv2-footer-01',
    profile: 'conventional',
    sectionType: 'footer',
    sourceTemplateId: 'profile-conventional',
    name: 'Pie de cuatro columnas con contacto',
    description: 'Marca y contacto, navegación, dirección y legal, sobre superficie oscura.',
    requiredFields: ['business.legalName', 'content.legal', 'navigation.items'],
    optionalFields: [],
    collectionLimits: [NAV_LIMIT],
    themeTokenCoverage: ['surfaceInverse', 'textOnDark', 'brandPrimary'],
    surfaceContext: 'dark',
    responsiveContract: { desktop: '4 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['/aviso-legal', '/privacidad', '/cookies'],
    requiredCompanions: ['header'],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: true,
    motion: { entry: 'none', stagger: false, interactions: [], tier: 'reference' },
  }),
];

export const PROFILE_VARIANTS: SectionVariant[] = [...PREMIUM, ...MINIMAL, ...CONVENTIONAL];
