import { useMemo, useRef, useState } from 'react';
import { activeItems, itemImage, itemList, itemText, type CollectionItem } from '../../collections';
import { getForm } from '../../forms';
import type { SectionComponent } from '../../registry';
import { useSite } from '../../context';
import { useActiveSection } from '../../hooks';
import { Accordion } from '../../components/Accordion';
import { BrandMark } from '../../components/BrandMark';
import { Icon } from '../../components/Icon';
import { MobileDrawer } from '../../components/MobileDrawer';
import { SiteForm } from '../../components/SiteForm';
import { Container, CtaButton, Picture, SectionShell } from '../../components/primitives';

const contactCta = (label = 'Contactar con el taller') => ({ label, kind: 'route' as const, target: '/contacto' });
const titleOf = (item: CollectionItem) => itemText(item, 'titulo', itemText(item, 'nombre'));

const Header: SectionComponent = ({ section }) => { const { config, runCta } = useSite(); const [open, setOpen] = useState(false); const trigger = useRef<HTMLButtonElement>(null); const items = useMemo(() => config.navigation.items.filter((x) => x.enabled).sort((a, b) => a.sortOrder - b.sortOrder), [config.navigation.items]); const active = useActiveSection(items); return <SectionShell anchor={section.anchor} as="header" className="ct-header"><Container><button type="button" className="ct-brand" onClick={() => runCta({ label: 'Inicio', kind: 'route', target: '/' })}><BrandMark icon="hammer" size={32} /><span><strong>{config.business.name}</strong><em>{config.business.tagline}</em></span></button><nav aria-label="Navegación principal">{items.slice(0, 9).map((item) => <button key={item.id} type="button" className={active === item.id ? 'is-active' : ''} onClick={() => runCta(item.cta)}>{item.label}</button>)}</nav><div className="ct-actions"><a href={`tel:${config.business.phone}`}>{config.business.phone}</a><button ref={trigger} type="button" className="ct-burger" aria-label="Abrir menú" aria-expanded={open} onClick={() => setOpen(true)}><Icon name="menu" size={23} /></button></div></Container><MobileDrawer open={open} onClose={() => setOpen(false)} items={items} activeId={active} triggerRef={trigger} footer={<CtaButton cta={contactCta()} full />} /></SectionShell>; };

const Hero: SectionComponent = ({ section }) => { const { config } = useSite(); const hero = config.content.hero; return <SectionShell anchor={section.anchor} className="ct-hero"><div className="ct-hero__media" data-wf-media-frame><Picture image={hero.image} loading="eager" /></div><Container><div className="ct-hero__copy" data-wf-entry="fade-up"><p className="ct-kicker">{hero.eyebrow}</p><h1>{hero.title}<em>{hero.titleHighlight}</em></h1><p>{hero.paragraph}</p><div><CtaButton cta={hero.primaryCta} variant="inverse" size="lg" /><CtaButton cta={hero.secondaryCta!} variant="link" size="lg" /></div></div><ul data-wf-card-row style={{ ['--wf-card-row-columns' as string]: 3 }}>{hero.microBenefits.map((item) => <li key={item.id} data-wf-card><strong>{item.label}</strong><span>{item.description}</span></li>)}</ul></Container></SectionShell>; };

const Manifesto: SectionComponent = ({ section }) => <SectionShell anchor={section.anchor} className="ct-section ct-manifesto"><Container><p className="ct-kicker">Nuestro taller</p><div><h2>No escondemos el proceso detrás de una imagen terminada.</h2><article><p>Una pieza a medida empieza mucho antes de cortar: al observar el espacio, preguntar por el uso y decidir qué merece protagonismo.</p><p>Esta template reserva lugar para contar el oficio con honestidad, documentar las pruebas y presentar a las personas reales que trabajan en cada fase.</p><CtaButton cta={{ label: 'Conocer el taller', kind: 'route', target: '/nuestro-taller' }} variant="secondary" /></article></div></Container></SectionShell>;

const Services: SectionComponent = ({ section }) => { const { config, runCta } = useSite(); const items = activeItems(config.collections ?? {}, 'servicios-carpinteria'); return <SectionShell anchor={section.anchor} className="ct-section ct-services"><Container><SectionTitle label="Servicios" title="De interior, cocina y pieza singular" /><div data-wf-card-row style={{ ['--wf-card-row-columns' as string]: 3 }}>{items.map((item, index) => <article key={item.id} data-wf-card><div data-wf-card-media><Picture image={itemImage(item, 'imagen')} /></div><div data-wf-card-body><span>0{index + 1}</span><h3>{itemText(item, 'titulo')}</h3><p>{itemText(item, 'resumen')}</p><ul>{itemList(item, 'beneficios').map((x) => <li key={x}>{x}</li>)}</ul></div><div data-wf-card-actions><button type="button" onClick={() => runCta({ label: 'Abrir servicio', kind: 'route', target: `/servicios/${itemText(item, 'slug')}` })}>Leer el servicio <Icon name="arrowRight" size={16} /></button></div></article>)}</div></Container></SectionShell>; };
function SectionTitle({ label, title }: { label: string; title: string }) { return <header className="ct-title" data-wf-entry="fade-up"><p className="ct-kicker">{label}</p><h2>{title}</h2></header>; }

const Process: SectionComponent = ({ section }) => { const { config } = useSite(); const items = activeItems(config.collections ?? {}, 'fases-proceso'); return <SectionShell anchor={section.anchor} className="ct-section ct-process"><Container><SectionTitle label="El proceso" title="Seis momentos, una misma responsabilidad" /><ol>{items.map((item, i) => <li key={item.id} data-wf-entry="fade-up"><div data-wf-media-frame><Picture image={itemImage(item, 'imagen')} /></div><span>{String(i + 1).padStart(2, '0')}</span><article><h3>{itemText(item, 'titulo')}</h3><p>{itemText(item, 'descripcion')}</p><em>{itemText(item, 'duracion')}</em></article></li>)}</ol></Container></SectionShell>; };

const Stories: SectionComponent = ({ section }) => { const { config, runCta } = useSite(); const items = activeItems(config.collections ?? {}, 'historias-taller'); return <SectionShell anchor={section.anchor} className="ct-section ct-stories"><Container><SectionTitle label="Historias del taller" title="Las decisiones también dejan huella" /><div data-wf-card-row style={{ ['--wf-card-row-columns' as string]: 3 }}>{items.map((item) => <article key={item.id} data-wf-card><div data-wf-card-media><Picture image={itemImage(item, 'imagen')} /></div><div data-wf-card-body><time>{itemText(item, 'fecha')}</time><h3>{itemText(item, 'titulo')}</h3><p>{itemText(item, 'entradilla')}</p></div><div data-wf-card-actions><button type="button" onClick={() => runCta({ label: 'Leer historia', kind: 'route', target: `/historias/${itemText(item, 'slug')}` })}>Leer historia <Icon name="arrowRight" size={16} /></button></div></article>)}</div></Container></SectionShell>; };

const Values: SectionComponent = ({ section }) => { const { config } = useSite(); const items = activeItems(config.collections ?? {}, 'valores-taller'); return <SectionShell anchor={section.anchor} className="ct-section ct-values"><Container><SectionTitle label="Valores" title="Principios que deben poder verse" /><div data-wf-card-row style={{ ['--wf-card-row-columns' as string]: 4 }}>{items.map((item, index) => <article key={item.id} data-wf-card><span>{String(index + 1).padStart(2, '0')}</span><div data-wf-card-body><h3>{itemText(item, 'titulo')}</h3><p>{itemText(item, 'descripcion')}</p></div></article>)}</div></Container></SectionShell>; };
const Final: SectionComponent = ({ section }) => { const { config } = useSite(); return <SectionShell anchor={section.anchor} className="ct-final"><Container><div data-wf-media-frame><Picture image={config.content.finalCta.image} /></div><article><p className="ct-kicker">Abrir conversación</p><h2>{config.content.finalCta.title}</h2><p>{config.content.finalCta.subtitle}</p><CtaButton cta={config.content.finalCta.cta} size="lg" /></article></Container></SectionShell>; };
const Footer: SectionComponent = ({ section }) => { const { config, runCta } = useSite(); return <SectionShell anchor={section.anchor} as="footer" className="ct-footer"><Container><div><BrandMark icon="hammer" size={34} inverse /><h2>{config.business.name}</h2><p>{config.content.footerTagline}</p></div><nav>{config.navigation.items.filter((x) => x.enabled).slice(0, 9).map((item) => <button key={item.id} type="button" onClick={() => runCta(item.cta)}>{item.label}</button>)}</nav><address><a href={`tel:${config.business.phone}`}>{config.business.phone}</a><a href={`mailto:${config.business.email}`}>{config.business.email}</a><span>{config.business.address.line1}<br />{config.business.address.city}</span></address><small>{config.content.footerSignature}</small></Container></SectionShell>; };

function PageHero({ label, title, text }: { label: string; title: string; text: string }) { return <div className="ct-page-hero"><Container><p className="ct-kicker">{label}</p><h1>{title}</h1><p>{text}</p></Container></div>; }
function Grid({ items, prefix }: { items: CollectionItem[]; prefix?: string }) { const { runCta } = useSite(); return <div className="ct-grid" data-wf-card-row style={{ ['--wf-card-row-columns' as string]: 3 }}>{items.map((item) => <article key={item.id} data-wf-card><div data-wf-card-media><Picture image={itemImage(item, 'imagen') ?? itemImage(item, 'foto')} /></div><div data-wf-card-body><h2>{titleOf(item)}</h2><p>{itemText(item, 'entradilla', itemText(item, 'resumen', itemText(item, 'descripcion', itemText(item, 'bio'))))}</p></div>{prefix ? <div data-wf-card-actions><button type="button" onClick={() => runCta({ label: 'Abrir ficha', kind: 'route', target: `${prefix}/${itemText(item, 'slug')}` })}>Abrir ficha <Icon name="arrowRight" size={16} /></button></div> : null}</article>)}</div>; }

const Page: SectionComponent = ({ section }) => { const { config, route } = useSite(); const c = config.collections ?? {}; const path = route.split('?')[0].replace(/\/+$/, '') || '/'; const [root, slug] = path.split('/').filter(Boolean);
  if (slug && ['historias', 'servicios', 'materiales', 'categorias', 'proyectos'].includes(root)) { const key = root === 'historias' ? 'historias-taller' : root === 'servicios' ? 'servicios-carpinteria' : root === 'categorias' ? 'categorias-proyecto' : root === 'proyectos' ? 'proyectos' : 'materiales'; const item = activeItems(c, key).find((x) => itemText(x, 'slug') === slug); return <SectionShell anchor={section.anchor} className="ct-page">{item ? <><PageHero label={root} title={titleOf(item)} text={itemText(item, 'entradilla', itemText(item, 'resumen', itemText(item, 'descripcion')))} /><Container className="ct-detail"><div data-wf-media-frame><Picture image={itemImage(item, 'imagen')} /></div><article><p>{itemText(item, 'relato', itemText(item, 'contenido', itemText(item, 'descripcion')))}</p>{root === 'proyectos' ? <dl><dt>Necesidad</dt><dd>{itemText(item, 'necesidad')}</dd><dt>Solución</dt><dd>{itemText(item, 'solucion')}</dd><dt>Resultado</dt><dd>{itemText(item, 'resultado')}</dd></dl> : null}{itemList(item, 'beneficios').length ? <ul>{itemList(item, 'beneficios').map((x) => <li key={x}>{x}</li>)}</ul> : null}<CtaButton cta={contactCta()} /></article></Container></> : <PageHero label="404" title="Ficha no encontrada" text="El contenido ya no está publicado." />}</SectionShell>; }
  if (path === '/nuestro-taller') return <SectionShell anchor={section.anchor} className="ct-page"><PageHero label="Nuestro taller" title="El lugar donde comprobamos las ideas" text="Una página preparada para contar capacidades reales sin inventar historia, certificaciones ni maquinaria." /><Container className="ct-story"><div data-wf-media-frame><Picture image={config.content.ambienceImage} /></div><article><h2>Oficio, método y contexto</h2><p>Completa este relato con el origen real del taller, su forma de organizar el trabajo y las capacidades que se puedan demostrar.</p><p>Los recursos visuales pueden mostrar banco, herramientas, muestras, pruebas y montaje, todos almacenados localmente.</p><CtaButton cta={{ label: 'Ver la galería', kind: 'route', target: '/galeria' }} variant="secondary" /></article></Container></SectionShell>;
  if (path === '/el-proceso') return <SectionShell anchor={section.anchor} className="ct-page"><PageHero label="El proceso" title="Cada fase evita una sorpresa posterior" text="De la escucha a la entrega, con decisiones visibles." /><Container className="ct-page-process">{activeItems(c, 'fases-proceso').map((item, i) => <article key={item.id}><span>{String(i + 1).padStart(2, '0')}</span><h2>{itemText(item, 'titulo')}</h2><p>{itemText(item, 'descripcion')}</p><em>{itemText(item, 'duracion')}</em></article>)}</Container></SectionShell>;
  if (path === '/contacto') { const form = getForm(config.forms ?? [], 'contactar-taller'); return <SectionShell anchor={section.anchor} className="ct-page"><PageHero label="Contacto" title="Cuéntanos qué necesita el espacio" text="Tipo, material, localidad y un mensaje suficiente para iniciar la conversación." /><Container className="ct-contact"><div>{form ? <SiteForm form={form} columns={2} /> : <p>Formulario no configurado.</p>}</div><aside><h2>También puedes llamar</h2><p>{config.business.phone}<br />{config.business.email}</p><h3>Visitas al taller</h3><p>{config.business.openingHours.map((x) => `${x.label}: ${x.value}`).join(' · ')}</p></aside></Container></SectionShell>; }
  if (path === '/preguntas') { const items = activeItems(c, 'preguntas-carpinteria'); return <SectionShell anchor={section.anchor} className="ct-page"><PageHero label="Preguntas" title="Antes de empezar" text="Información editable sobre alcance, materiales, montaje y cambios." /><Container><Accordion items={items.map((item) => ({ id: item.id, question: itemText(item, 'pregunta'), answer: itemText(item, 'respuesta') }))} mode="multiple" icon="chevron" /></Container></SectionShell>; }
  const listMap: Record<string, [string, string, string, string?]> = { '/servicios': ['servicios-carpinteria', 'Servicios', 'Trabajos que salen del taller', '/servicios'], '/materiales': ['materiales', 'Materiales', 'Conocer la materia antes de elegir', '/materiales'], '/historias': ['historias-taller', 'Historias', 'Decisiones contadas desde dentro', '/historias'], '/galeria': ['galeria-taller', 'Galería', 'Un diario visual del proceso'], '/equipo': ['equipo-taller', 'Equipo', 'Personas y responsabilidades'], '/valores': ['valores-taller', 'Valores', 'Principios convertidos en acciones'] };
  if (listMap[path]) { const [key, label, title, prefix] = listMap[path]; return <SectionShell anchor={section.anchor} className="ct-page"><PageHero label={label} title={title} text="Contenido suficiente, ordenable y gestionado desde el editor genérico." /><Container><Grid items={activeItems(c, key)} prefix={prefix} /></Container></SectionShell>; }
  const legal = config.content.legal; const doc = path === '/privacidad' ? legal.privacy : path === '/cookies' ? legal.cookies : legal.legalNotice; return <SectionShell anchor={section.anchor} className="ct-page"><PageHero label="Legal" title={doc.title} text="Información del responsable y condiciones de uso." /><Container className="ct-legal">{doc.body.split('\n\n').map((x, i) => <p key={i}>{x}</p>)}</Container></SectionShell>;
};

export const CARPINTERIA_TALLER_SECTIONS: Record<string, SectionComponent> = { 'ct-header-01': Header, 'ct-hero-01': Hero, 'ct-manifiesto-01': Manifesto, 'ct-servicios-01': Services, 'ct-proceso-01': Process, 'ct-historias-01': Stories, 'ct-valores-01': Values, 'ct-final-01': Final, 'ct-footer-01': Footer,
  'ct-page-taller-01': Page, 'ct-page-servicios-01': Page, 'ct-page-proceso-01': Page, 'ct-page-materiales-01': Page, 'ct-page-historias-01': Page, 'ct-page-galeria-01': Page, 'ct-page-equipo-01': Page, 'ct-page-valores-01': Page, 'ct-page-faq-01': Page, 'ct-page-contacto-01': Page, 'ct-page-legal-01': Page, 'ct-page-categorias-01': Page, 'ct-page-proyectos-01': Page };
