import { normalizeSemanticThemeTokens, type ThemeTokens } from './tokens';
import { FONT_STACKS } from './fonts';

export interface ThemeDefinition {
  id: string;
  templateId: string;
  name: string;
  description: string;
  version: string;
  /** Miniatura generada por el propio motor de temas (swatches), no una imagen. */
  swatches: string[];
  tokens: ThemeTokens;
}

/** Valores compartidos por todas las templates; cada tema los sobrescribe. */
const SHARED: ThemeTokens = {
  // El rosa de marca se oscurece lo justo para que el texto blanco del botón
  // primario supere 4.5:1 conservando la lectura «rosa intenso».
  brandPrimary: '#D62E63',
  brandPrimaryStrong: '#B31F4C',
  brandPrimaryContrast: '#FFFFFF',
  brandSecondary: '#FFC928',
  accent: '#44C9C6',
  accentAlt: '#A86BD5',
  accentTertiary: '#FF9F43',
  surface: '#FFFFFF',
  surfaceAlt: '#FFF9F2',
  surfaceMuted: '#F6F5F3',
  surfaceHighlight: '#FFD4E1',
  surfaceInverse: '#10172F',
  surfaceInverseSoft: '#1B2444',
  text: '#10172F',
  textMuted: '#526072',
  textInverse: '#FFFFFF',
  textMutedInverse: '#C7CEDD',
  textOnLight: '#10172F',
  textMutedOnLight: '#526072',
  textOnDark: '#FFFFFF',
  textMutedOnDark: '#C7CEDD',
  textOnBrand: '#FFFFFF',
  textOnCard: '#10172F',
  buttonText: '#FFFFFF',
  linkText: '#B31F4C',
  decorativeText: '#526072',
  border: '#EAE8E5',
  borderStrong: '#D3CFC9',
  success: '#157F4C',
  warning: '#95640A',
  danger: '#BE2B41',
  focus: '#0D8A87',
  focusInverse: '#5FD8D5',
  whatsapp: '#0D743B',
  star: '#F0A500',

  fontDisplay: FONT_STACKS.nunito,
  fontBody: FONT_STACKS.poppins,
  displayWeight: '800',
  bodyWeight: '400',
  displayTransform: 'none',
  displayLetterSpacing: '-0.02em',
  eyebrowTransform: 'uppercase',
  eyebrowLetterSpacing: '0.12em',
  h1Size: 'clamp(2.4rem, 3.6vw, 3.75rem)',
  h1SizeMobile: '2.4rem',
  h1LineHeight: '1.04',
  h2Size: 'clamp(1.65rem, 2.2vw, 2.05rem)',
  h3Size: '1.15rem',
  bodySize: '1rem',
  labelSize: '0.85rem',

  contentMax: '1480px',
  gutter: '32px',
  gutterTablet: '24px',
  gutterMobile: '18px',
  sectionSpacing: '72px',

  radiusCard: '16px',
  radiusButton: '10px',
  radiusInput: '10px',
  radiusImage: '12px',
  radiusPill: '999px',
  radiusModal: '18px',
  radiusContainer: '20px',

  shadowCard: '0 8px 24px rgba(16, 23, 47, 0.06)',
  shadowFloat: '0 14px 34px rgba(16, 23, 47, 0.12)',
  shadowOverlay: '0 24px 60px rgba(16, 23, 47, 0.24)',

  buttonPaddingY: '0.85rem',
  buttonPaddingX: '1.5rem',
  buttonWeight: '700',
  buttonTransform: 'none',
  buttonLetterSpacing: '0',
  buttonShadow: '0 6px 16px rgba(214, 46, 99, 0.28)',
  buttonGradient: 'none',

  cardStyle: 'elevated',
  cardBorderWidth: '1px',
  cardBackground: '#FFFFFF',
  cardGradient: 'none',
  cardBackdropFilter: 'none',
  cardHoverLift: '3px',
  surfaceGlow: 'none',

  heroBackground: '#FFFDF9',
  bandBackground: '#FFF9F2',
  gradientAccent: 'linear-gradient(120deg, #D62E63, #A86BD5)',
  decorPattern: 'paws',
  decorOpacity: '0.16',
  iconStyle: 'filled-circle',

  durationFast: '160ms',
  durationBase: '220ms',
  easing: 'cubic-bezier(0.22, 0.61, 0.36, 1)',
  motionPreset: 'balanced',
  animationStyle: 'suave',
  motionAccent: '#D62E63',
  staggerStep: '70ms',
  revealDistance: '18px',
  imageHoverScale: '1.025',
};

function theme(
  id: string,
  templateId: string,
  name: string,
  description: string,
  swatches: string[],
  tokens: Partial<ThemeTokens>,
): ThemeDefinition {
  const merged = { ...SHARED, ...tokens };
  const contextual = normalizeSemanticThemeTokens({
    ...merged,
    textOnLight: tokens.textOnLight ?? merged.text,
    textMutedOnLight: tokens.textMutedOnLight ?? merged.textMuted,
    textOnDark: tokens.textOnDark ?? merged.textInverse,
    textMutedOnDark: tokens.textMutedOnDark ?? merged.textMutedInverse,
    textOnBrand: tokens.textOnBrand ?? merged.brandPrimaryContrast,
    textOnCard: tokens.textOnCard ?? merged.text,
    buttonText: tokens.buttonText ?? merged.brandPrimaryContrast,
    // Los enlaces son texto normal (4.5:1), no decoración de marca. Cada tema
    // puede proporcionar una variante cromática explícita; el fallback seguro
    // es su propio texto principal.
    linkText: tokens.linkText ?? merged.text,
    decorativeText: tokens.decorativeText ?? merged.textMuted,
  }) as ThemeTokens;
  return { id, templateId, name, description, version: '2.0.0', swatches, tokens: contextual };
}

/* ------------------------------------------------------------------ *
 * Peludos Felices
 * ------------------------------------------------------------------ */

const pfColorido = theme(
  'pf-colorido-alegre',
  'canine-peludos-felices',
  'Colorido alegre',
  'Rosa intenso, amarillo y turquesa sobre blanco cálido. La lectura original de la template.',
  ['#D62E63', '#FFC928', '#44C9C6', '#A86BD5', '#FFF9F2'],
  {},
);

const pfSpa = theme(
  'pf-spa-elegante',
  'canine-peludos-felices',
  'Spa elegante',
  'Misma composición con paleta salvia y arena, iconos suaves y sombras discretas.',
  ['#5C8A6E', '#C7A87C', '#8FB3A3', '#F4F1EA', '#FFFFFF'],
  {
    brandPrimary: '#3F6B52',
    brandPrimaryStrong: '#2F5240',
    brandSecondary: '#C7A87C',
    accent: '#7FA894',
    accentAlt: '#A8926F',
    accentTertiary: '#D6BE95',
    surfaceAlt: '#F5F2EB',
    surfaceMuted: '#EFEBE2',
    surfaceHighlight: '#E4EDE6',
    text: '#1F2A24',
    textMuted: '#586158',
    border: '#DFD9CD',
    borderStrong: '#C6BDAC',
    focus: '#2F5240',
    focusInverse: '#8FB3A3',
    fontDisplay: FONT_STACKS.playfair,
    fontBody: FONT_STACKS.inter,
    displayWeight: '600',
    displayLetterSpacing: '-0.01em',
    radiusCard: '12px',
    radiusButton: '8px',
    shadowCard: '0 6px 18px rgba(31, 42, 36, 0.06)',
    buttonShadow: '0 6px 16px rgba(63, 107, 82, 0.24)',
    heroBackground: '#FBFAF6',
    bandBackground: '#F5F2EB',
    gradientAccent: 'linear-gradient(120deg, #3F6B52, #C7A87C)',
    decorPattern: 'organic',
    decorOpacity: '0.1',
    iconStyle: 'soft-circle',
    cardStyle: 'outlined',
  },
);

const pfPremium = theme(
  'pf-premium-oscuro',
  'canine-peludos-felices',
  'Premium oscuro',
  'Superficies grafito, acentos coral y dorado. Mantiene el hero recortado y el footer ondulado.',
  ['#FF5C8A', '#E7B44C', '#151A2C', '#232A44', '#F4F6FF'],
  {
    brandPrimary: '#FF5C8A',
    brandPrimaryStrong: '#E83F6C',
    brandPrimaryContrast: '#0C0F1C',
    brandSecondary: '#E7B44C',
    accent: '#4ECBD0',
    accentAlt: '#A98CFF',
    accentTertiary: '#FF9E6B',
    surface: '#1B2138',
    surfaceAlt: '#151A2C',
    surfaceMuted: '#232A44',
    surfaceHighlight: '#2A2140',
    surfaceInverse: '#0C0F1C',
    surfaceInverseSoft: '#151A2C',
    text: '#F4F6FF',
    textMuted: '#AEB6D0',
    textInverse: '#F4F6FF',
    textMutedInverse: '#AEB6D0',
    border: '#333B5C',
    borderStrong: '#47507A',
    success: '#45D483',
    warning: '#F0B84B',
    danger: '#FF7A8C',
    focus: '#4ECBD0',
    focusInverse: '#4ECBD0',
    star: '#E7B44C',
    cardBackground: '#232A44',
    cardStyle: 'inverse',
    shadowCard: '0 10px 28px rgba(0, 0, 0, 0.36)',
    shadowFloat: '0 18px 42px rgba(0, 0, 0, 0.46)',
    buttonShadow: '0 8px 20px rgba(255, 92, 138, 0.32)',
    heroBackground: '#151A2C',
    bandBackground: '#1B2138',
    gradientAccent: 'linear-gradient(120deg, #FF5C8A, #A98CFF)',
    decorOpacity: '0.14',
    iconStyle: 'filled-circle',
  },
);

/* ------------------------------------------------------------------ *
 * Pelos, Paz y Amor
 * ------------------------------------------------------------------ */

const ppaBase: Partial<ThemeTokens> = {
  brandPrimary: '#96682A',
  brandPrimaryStrong: '#7A5420',
  brandSecondary: '#D8B878',
  accent: '#BC8D43',
  accentAlt: '#C9B79A',
  accentTertiary: '#E3D3B8',
  surface: '#FFFFFF',
  surfaceAlt: '#FBF8F2',
  surfaceMuted: '#F2E9DD',
  surfaceHighlight: '#F6EFE2',
  surfaceInverse: '#221F19',
  surfaceInverseSoft: '#332E25',
  text: '#181713',
  textMuted: '#5F5A51',
  border: '#E6DED2',
  borderStrong: '#CFC2AE',
  focus: '#7A5420',
  focusInverse: '#D8B878',
  star: '#BC8D43',
  fontDisplay: FONT_STACKS.playfair,
  fontBody: FONT_STACKS.inter,
  displayWeight: '600',
  displayLetterSpacing: '-0.005em',
  h1Size: 'clamp(2.35rem, 3.6vw, 3.9rem)',
  h1LineHeight: '1.06',
  contentMax: '1440px',
  radiusCard: '8px',
  radiusButton: '6px',
  radiusInput: '6px',
  radiusImage: '8px',
  shadowCard: '0 6px 20px rgba(24, 23, 19, 0.05)',
  shadowFloat: '0 12px 30px rgba(24, 23, 19, 0.1)',
  buttonShadow: '0 5px 14px rgba(150, 104, 42, 0.22)',
  cardStyle: 'outlined',
  cardHoverLift: '2px',
  heroBackground: '#FBF8F2',
  bandBackground: '#FBF8F2',
  gradientAccent: 'linear-gradient(120deg, #BC8D43, #D8B878)',
  decorPattern: 'none',
  decorOpacity: '0.08',
  iconStyle: 'line',
};

const ppaNatural = theme(
  'ppa-natural-sereno',
  'canine-pelos-paz-amor',
  'Natural sereno',
  'Marfil, arena y dorado tostado. La lectura editorial original de la template.',
  ['#BC8D43', '#D8B878', '#FBF8F2', '#F2E9DD', '#181713'],
  ppaBase,
);

const ppaRosa = theme(
  'ppa-rosa-boutique',
  'canine-pelos-paz-amor',
  'Rosa boutique',
  'Rosa empolvado y malva sobre blanco roto, conservando la calma editorial.',
  ['#B2607A', '#E4B6C4', '#FDF6F7', '#F5E4E9', '#2A1B21'],
  {
    ...ppaBase,
    brandPrimary: '#A85572',
    brandPrimaryStrong: '#8A4257',
    brandSecondary: '#E4B6C4',
    accent: '#C97F97',
    accentAlt: '#D9A9B6',
    accentTertiary: '#EED3DA',
    surfaceAlt: '#FDF6F7',
    surfaceMuted: '#F5E4E9',
    surfaceHighlight: '#F9ECEF',
    surfaceInverse: '#2A1B21',
    surfaceInverseSoft: '#3D2830',
    text: '#2A1B21',
    textMuted: '#6B5058',
    border: '#EBD8DE',
    borderStrong: '#D8B9C3',
    focus: '#8A4257',
    focusInverse: '#E4B6C4',
    star: '#C97F97',
    buttonShadow: '0 5px 14px rgba(168, 85, 114, 0.22)',
    heroBackground: '#FDF6F7',
    bandBackground: '#FDF6F7',
    gradientAccent: 'linear-gradient(120deg, #B2607A, #E4B6C4)',
  },
);

const ppaNocturno = theme(
  'ppa-nocturno-calido',
  'canine-pelos-paz-amor',
  'Nocturno cálido',
  'Marrón profundo y dorado suave para una lectura de spa nocturno.',
  ['#D8B878', '#8A6C3C', '#211C15', '#2E2820', '#F6F0E4'],
  {
    ...ppaBase,
    brandPrimary: '#D8B878',
    brandPrimaryStrong: '#C0A063',
    brandPrimaryContrast: '#211C15',
    brandSecondary: '#8A6C3C',
    accent: '#C6A56A',
    accentAlt: '#9C8560',
    accentTertiary: '#6E5C40',
    surface: '#2A241C',
    surfaceAlt: '#211C15',
    surfaceMuted: '#332C22',
    surfaceHighlight: '#3B3327',
    surfaceInverse: '#161209',
    surfaceInverseSoft: '#211C15',
    text: '#F6F0E4',
    textMuted: '#C6BCA6',
    textInverse: '#F6F0E4',
    textMutedInverse: '#C6BCA6',
    border: '#453C2E',
    borderStrong: '#5C5140',
    success: '#5FCB8E',
    warning: '#EFC061',
    danger: '#EC8A85',
    focus: '#D8B878',
    focusInverse: '#D8B878',
    star: '#D8B878',
    cardBackground: '#332C22',
    cardStyle: 'inverse',
    shadowCard: '0 10px 26px rgba(0, 0, 0, 0.4)',
    buttonShadow: '0 6px 16px rgba(216, 184, 120, 0.24)',
    heroBackground: '#211C15',
    bandBackground: '#2A241C',
    gradientAccent: 'linear-gradient(120deg, #D8B878, #8A6C3C)',
  },
);

/* ------------------------------------------------------------------ *
 * Elegance
 * ------------------------------------------------------------------ */

const elBase: Partial<ThemeTokens> = {
  brandPrimary: '#AD8130',
  brandPrimaryStrong: '#C89C3C',
  brandPrimaryContrast: '#0B0C0B',
  brandSecondary: '#E0B85E',
  accent: '#C89536',
  accentAlt: '#8A6A28',
  accentTertiary: '#E9D6A8',
  surface: '#FFFFFF',
  surfaceAlt: '#F8F5EF',
  surfaceMuted: '#EFEAE0',
  surfaceHighlight: '#F1E7D2',
  surfaceInverse: '#0B0C0B',
  surfaceInverseSoft: '#171817',
  text: '#181715',
  textMuted: '#5B564D',
  textInverse: '#F8F4EB',
  textMutedInverse: '#C6C0B6',
  border: '#E2DCD0',
  borderStrong: '#8A6728',
  focus: '#8A6728',
  focusInverse: '#E0B85E',
  star: '#E0B85E',
  fontDisplay: FONT_STACKS.playfair,
  fontBody: FONT_STACKS.inter,
  displayWeight: '600',
  displayLetterSpacing: '-0.01em',
  eyebrowLetterSpacing: '0.2em',
  h1Size: 'clamp(2.3rem, 3.5vw, 3.65rem)',
  h1LineHeight: '1.08',
  contentMax: '1520px',
  radiusCard: '8px',
  radiusButton: '5px',
  radiusInput: '5px',
  radiusImage: '6px',
  shadowCard: '0 10px 26px rgba(11, 12, 11, 0.1)',
  shadowFloat: '0 16px 38px rgba(11, 12, 11, 0.2)',
  buttonWeight: '600',
  buttonTransform: 'uppercase',
  buttonLetterSpacing: '0.09em',
  buttonShadow: '0 8px 20px rgba(173, 129, 48, 0.28)',
  buttonGradient: 'linear-gradient(135deg, #C79B44, #AD8130)',
  cardStyle: 'outlined',
  cardHoverLift: '2px',
  heroBackground: '#0B0C0B',
  bandBackground: '#F8F5EF',
  gradientAccent: 'linear-gradient(120deg, #AD8130, #E0B85E)',
  decorPattern: 'none',
  decorOpacity: '0.12',
  iconStyle: 'gold-circle',
};

const elOroNegro = theme(
  'el-oro-negro',
  'canine-elegance',
  'Oro negro',
  'Negro cinematográfico con dorado cálido. La lectura premium original.',
  ['#AD8130', '#E0B85E', '#0B0C0B', '#F8F5EF', '#FFFFFF'],
  elBase,
);

const elMarfil = theme(
  'el-marfil-editorial',
  'canine-elegance',
  'Marfil editorial',
  'Antracita sustituido por marfil profundo y bronce; conserva alternancia y ritmo.',
  ['#8C6B3F', '#B99A6B', '#2B2721', '#F7F3EA', '#FFFFFF'],
  {
    ...elBase,
    brandPrimary: '#8C6B3F',
    brandPrimaryStrong: '#6E5330',
    brandPrimaryContrast: '#FFFFFF',
    brandSecondary: '#B99A6B',
    accent: '#8C6B3F',
    accentTertiary: '#E0D2B8',
    surfaceInverse: '#2B2721',
    surfaceInverseSoft: '#3A352C',
    surfaceAlt: '#F7F3EA',
    textInverse: '#F7F3EA',
    textMutedInverse: '#CDC5B4',
    borderStrong: '#8C6B3F',
    focus: '#6E5330',
    focusInverse: '#B99A6B',
    star: '#B99A6B',
    buttonGradient: 'linear-gradient(135deg, #A5824F, #8C6B3F)',
    buttonShadow: '0 8px 20px rgba(140, 107, 63, 0.26)',
    heroBackground: '#2B2721',
    bandBackground: '#F7F3EA',
    gradientAccent: 'linear-gradient(120deg, #8C6B3F, #B99A6B)',
  },
);

const elVioleta = theme(
  'el-violeta-imperial',
  'canine-elegance',
  'Violeta imperial',
  'Berenjena profundo con violeta claro y latón; mantiene el contraste alto de la base.',
  ['#B79AE8', '#7C4FD0', '#170F26', '#F6F2FC', '#FFFFFF'],
  {
    ...elBase,
    brandPrimary: '#8257D4',
    brandPrimaryStrong: '#6A40BC',
    brandPrimaryContrast: '#FFFFFF',
    brandSecondary: '#B79AE8',
    accent: '#8257D4',
    accentAlt: '#5F3AA8',
    accentTertiary: '#DCCDF6',
    surfaceInverse: '#170F26',
    surfaceInverseSoft: '#241735',
    surfaceAlt: '#F6F2FC',
    surfaceMuted: '#EAE1F7',
    surfaceHighlight: '#E5DAF8',
    text: '#1B1425',
    textMuted: '#5B5169',
    textInverse: '#F6F2FC',
    textMutedInverse: '#C6BAD8',
    border: '#E2DAEE',
    borderStrong: '#6F45C2',
    focus: '#6A40BC',
    focusInverse: '#B79AE8',
    star: '#C7A6F2',
    buttonGradient: 'linear-gradient(135deg, #A279EC, #7C4FD0)',
    buttonShadow: '0 8px 20px rgba(124, 79, 208, 0.3)',
    heroBackground: '#170F26',
    bandBackground: '#F6F2FC',
    gradientAccent: 'linear-gradient(120deg, #7C4FD0, #B79AE8)',
  },
);

/* ------------------------------------------------------------------ *
 * Peludos & Co.
 * ------------------------------------------------------------------ */

const pcoBase: Partial<ThemeTokens> = {
  brandPrimary: '#8A43D6',
  brandPrimaryStrong: '#7132B8',
  brandSecondary: '#B48AE8',
  accent: '#8A43D6',
  accentAlt: '#B48AE8',
  accentTertiary: '#E9BC3D',
  surface: '#FFFFFF',
  surfaceAlt: '#FAF7FE',
  surfaceMuted: '#F2E8FF',
  surfaceHighlight: '#F2E8FF',
  surfaceInverse: '#101B36',
  surfaceInverseSoft: '#1B2748',
  text: '#111A32',
  textMuted: '#5E6677',
  border: '#E4E2E8',
  borderStrong: '#CFC9DA',
  success: '#157F4C',
  focus: '#7132B8',
  focusInverse: '#B48AE8',
  whatsapp: '#0D743B',
  star: '#C99A0F',
  fontDisplay: FONT_STACKS.poppins,
  fontBody: FONT_STACKS.poppins,
  displayWeight: '700',
  displayLetterSpacing: '-0.025em',
  h1Size: 'clamp(2.3rem, 3.4vw, 3.55rem)',
  h1LineHeight: '1.05',
  radiusCard: '12px',
  radiusButton: '8px',
  radiusInput: '8px',
  radiusImage: '10px',
  shadowCard: '0 4px 14px rgba(17, 26, 50, 0.05)',
  shadowFloat: '0 10px 28px rgba(17, 26, 50, 0.1)',
  buttonShadow: '0 6px 16px rgba(138, 67, 214, 0.24)',
  cardStyle: 'outlined',
  cardHoverLift: '2px',
  heroBackground: '#FFFFFF',
  bandBackground: '#F7F2FE',
  gradientAccent: 'linear-gradient(120deg, #8A43D6, #B48AE8)',
  decorPattern: 'dots',
  decorOpacity: '0.1',
  iconStyle: 'soft-circle',
};

const pcoLavanda = theme(
  'pco-lavanda-profesional',
  'canine-peludos-and-co',
  'Lavanda profesional',
  'Blanco y lila de producto digital. La lectura original de la template.',
  ['#8A43D6', '#B48AE8', '#F2E8FF', '#101B36', '#FFFFFF'],
  pcoBase,
);

const pcoMenta = theme(
  'pco-menta-limpia',
  'canine-peludos-and-co',
  'Menta limpia',
  'Verde menta y azul frío; misma retícula, sensación clínica y luminosa.',
  ['#12907B', '#5EC6B4', '#E4F6F2', '#0E2A2B', '#FFFFFF'],
  {
    ...pcoBase,
    brandPrimary: '#0F7D6B',
    brandPrimaryStrong: '#0B6455',
    brandSecondary: '#5EC6B4',
    accent: '#0F7D6B',
    accentAlt: '#5EC6B4',
    accentTertiary: '#3E9FD6',
    surfaceAlt: '#F3FBF9',
    surfaceMuted: '#E4F6F2',
    surfaceHighlight: '#E4F6F2',
    surfaceInverse: '#0E2A2B',
    surfaceInverseSoft: '#173B3C',
    text: '#0F2426',
    textMuted: '#4F6567',
    border: '#DCE7E5',
    borderStrong: '#B9D2CE',
    focus: '#0B6455',
    focusInverse: '#5EC6B4',
    buttonShadow: '0 6px 16px rgba(15, 125, 107, 0.24)',
    bandBackground: '#F0FAF8',
    gradientAccent: 'linear-gradient(120deg, #12907B, #5EC6B4)',
  },
);

const pcoGrafito = theme(
  'pco-grafito-tecnologico',
  'canine-peludos-and-co',
  'Grafito tecnológico',
  'Superficies grafito con azul eléctrico; misma estructura, contraste invertido.',
  ['#5B8CFF', '#8AA9FF', '#151823', '#1F2434', '#EEF1FA'],
  {
    ...pcoBase,
    brandPrimary: '#5B8CFF',
    brandPrimaryStrong: '#4E79E6',
    brandPrimaryContrast: '#0C0F19',
    brandSecondary: '#8AA9FF',
    accent: '#5B8CFF',
    accentAlt: '#8AA9FF',
    accentTertiary: '#F0B84B',
    surface: '#1F2434',
    surfaceAlt: '#151823',
    surfaceMuted: '#272D40',
    surfaceHighlight: '#232B44',
    surfaceInverse: '#0C0F19',
    surfaceInverseSoft: '#151823',
    text: '#EEF1FA',
    textMuted: '#A7B0C6',
    textInverse: '#EEF1FA',
    textMutedInverse: '#A7B0C6',
    border: '#333A50',
    borderStrong: '#47506C',
    success: '#45D483',
    warning: '#F0B84B',
    danger: '#FF7A8C',
    focus: '#8AA9FF',
    focusInverse: '#8AA9FF',
    star: '#F0B84B',
    whatsapp: '#0D743B',
    cardBackground: '#272D40',
    cardStyle: 'inverse',
    shadowCard: '0 8px 22px rgba(0, 0, 0, 0.34)',
    buttonShadow: '0 6px 18px rgba(91, 140, 255, 0.3)',
    heroBackground: '#151823',
    bandBackground: '#1B2030',
    gradientAccent: 'linear-gradient(120deg, #5B8CFF, #8AA9FF)',
  },
);

/*
 * Cálido artesano (Peluquería canina MARCOS Arriaza).
 *
 * No es una de las tres paletas de fábrica: se construye desde las fotos
 * reales del local —ladrillo visto, madera, azulejo hidráulico, plantas—
 * para que la web deje de leerse como una copia genérica de Peludos & Co.
 * Terracota y madera en vez de lila de producto digital; tipografía Nunito
 * (más redonda y cercana) en vez de Poppins; movimiento "suave", a tono con
 * lo que repiten las reseñas: paciencia y calma, no urgencia.
 */
const pcoArriazaCalido = theme(
  'pco-arriaza-calido',
  'canine-peludos-and-co',
  'Cálido artesano',
  'Terracota, madera y ladrillo visto, tomados de las fotos reales del local. Cercano y artesanal, sin urgencia.',
  ['#B5533C', '#D4A24C', '#FBF6EE', '#2A211A', '#6E8F5C'],
  {
    ...pcoBase,
    brandPrimary: '#B5533C',
    brandPrimaryStrong: '#8B3E2C',
    brandSecondary: '#C98A3E',
    accent: '#6E8F5C',
    accentAlt: '#8B6B4A',
    accentTertiary: '#D4A24C',
    surface: '#FFFFFF',
    surfaceAlt: '#FBF6EE',
    surfaceMuted: '#F0E4D8',
    surfaceHighlight: '#E8EFE3',
    surfaceInverse: '#2A211A',
    surfaceInverseSoft: '#3A2E24',
    text: '#2A211A',
    textMuted: '#6B5D50',
    textInverse: '#FBF6EE',
    textMutedInverse: '#D8CCBE',
    border: '#E5D9C8',
    borderStrong: '#C9B79E',
    success: '#4C7F52',
    warning: '#95640A',
    danger: '#B0402C',
    focus: '#8B3E2C',
    focusInverse: '#D4A24C',
    star: '#D4A24C',
    whatsapp: '#0D743B',
    fontDisplay: FONT_STACKS.nunito,
    fontBody: FONT_STACKS.inter,
    displayWeight: '800',
    radiusCard: '16px',
    radiusButton: '10px',
    radiusImage: '14px',
    shadowCard: '0 6px 18px rgba(42, 33, 26, 0.10)',
    shadowFloat: '0 12px 30px rgba(42, 33, 26, 0.16)',
    buttonShadow: '0 6px 16px rgba(139, 62, 44, 0.28)',
    cardStyle: 'elevated',
    cardHoverLift: '3px',
    heroBackground: '#FBF6EE',
    bandBackground: '#F5EDE1',
    gradientAccent: 'linear-gradient(120deg, #B5533C, #D4A24C)',
    decorPattern: 'paws',
    decorOpacity: '0.08',
    iconStyle: 'soft-circle',
    motionPreset: 'calm',
    animationStyle: 'suave',
    motionAccent: '#B5533C',
  },
);

/* ------------------------------------------------------------------ *
 * PlagaControl · Respuesta rápida
 *
 * Los tres temas comparten datos, páginas, secciones, formularios y
 * colecciones. Cambian paleta, tipografía, forma, sombra e iconografía.
 * ------------------------------------------------------------------ */

const prTecnico = theme(
  'pr-tecnico',
  'plagas-respuesta-rapida',
  'Técnico',
  'Verdes oscuros, grafito y blanco. Lectura profesional y sobria, la del sector técnico.',
  ['#1F5D3F', '#123A28', '#2E9E68', '#2B3138', '#F4F6F4'],
  {
    brandPrimary: '#1F5D3F',
    brandPrimaryStrong: '#123A28',
    brandPrimaryContrast: '#FFFFFF',
    brandSecondary: '#2E9E68',
    accent: '#2E9E68',
    accentAlt: '#0F766E',
    accentTertiary: '#B08900',
    surface: '#FFFFFF',
    surfaceAlt: '#F4F6F4',
    surfaceMuted: '#EDF1EE',
    surfaceHighlight: '#DCEAE1',
    surfaceInverse: '#1B2220',
    surfaceInverseSoft: '#2B3138',
    text: '#1B2220',
    textMuted: '#55635C',
    border: '#DCE3DE',
    borderStrong: '#BAC7C0',
    focus: '#0F766E',
    focusInverse: '#6EE7C8',
    fontDisplay: FONT_STACKS.poppins,
    fontBody: FONT_STACKS.poppins,
    displayWeight: '700',
    displayLetterSpacing: '-0.015em',
    radiusCard: '10px',
    radiusButton: '8px',
    radiusInput: '8px',
    radiusImage: '8px',
    buttonShadow: '0 6px 16px rgb(31 93 63 / 26%)',
    iconStyle: 'outline-square',
    decorPattern: 'lines',
  },
);

const prNatural = theme(
  'pr-natural',
  'plagas-respuesta-rapida',
  'Natural',
  'Verde salvia, arena y tonos claros. Presentación preventiva y amable, menos agresiva.',
  ['#5C7F63', '#41603F', '#8FAE86', '#C9B99B', '#FBF9F4'],
  {
    brandPrimary: '#4E6F55',
    brandPrimaryStrong: '#3A5540',
    brandPrimaryContrast: '#FFFFFF',
    brandSecondary: '#8FAE86',
    accent: '#7A9A6E',
    accentAlt: '#A8894F',
    accentTertiary: '#C9B99B',
    surface: '#FFFFFF',
    surfaceAlt: '#FBF9F4',
    surfaceMuted: '#F3F0E8',
    surfaceHighlight: '#E6EDE1',
    surfaceInverse: '#2C332B',
    surfaceInverseSoft: '#3D453B',
    text: '#2C332B',
    textMuted: '#5F6B5C',
    border: '#E5E2D8',
    borderStrong: '#CFCBBC',
    focus: '#3A5540',
    focusInverse: '#B7D6A8',
    fontDisplay: FONT_STACKS.nunito,
    fontBody: FONT_STACKS.poppins,
    displayWeight: '700',
    displayLetterSpacing: '-0.01em',
    radiusCard: '18px',
    radiusButton: '999px',
    radiusInput: '12px',
    radiusImage: '16px',
    buttonShadow: '0 6px 18px rgb(78 111 85 / 22%)',
    iconStyle: 'soft-circle',
    decorPattern: 'organic',
  },
);

const prUrgente = theme(
  'pr-urgente',
  'plagas-respuesta-rapida',
  'Urgente',
  'Azul marino, negro controlado y acento cálido. Transmite disponibilidad inmediata sin parecer alarmista.',
  ['#132A4A', '#0B1B30', '#E2582A', '#F4A23A', '#F5F7FA'],
  {
    // El acento cálido se reserva a llamadas concretas: el azul mantiene la
    // sensación de servicio fiable y evita que la web resulte agresiva.
    brandPrimary: '#132A4A',
    brandPrimaryStrong: '#0B1B30',
    brandPrimaryContrast: '#FFFFFF',
    brandSecondary: '#1E4675',
    accent: '#C7451C',
    accentAlt: '#B8791B',
    accentTertiary: '#1E4675',
    surface: '#FFFFFF',
    surfaceAlt: '#F5F7FA',
    surfaceMuted: '#EDF1F6',
    surfaceHighlight: '#DCE5F0',
    surfaceInverse: '#0B1B30',
    surfaceInverseSoft: '#152B49',
    text: '#0B1B30',
    textMuted: '#4C5B70',
    border: '#DDE3EC',
    borderStrong: '#BCC6D6',
    focus: '#1E4675',
    focusInverse: '#7FB2F0',
    fontDisplay: FONT_STACKS.poppins,
    fontBody: FONT_STACKS.poppins,
    displayWeight: '800',
    displayTransform: 'none',
    displayLetterSpacing: '-0.025em',
    radiusCard: '14px',
    radiusButton: '10px',
    radiusInput: '10px',
    radiusImage: '12px',
    buttonShadow: '0 8px 20px rgb(199 69 28 / 28%)',
    iconStyle: 'filled-circle',
    decorPattern: 'dots',
  },
);

/* ------------------------------------------------------------------ *
 * Gestión Integral · Corporativa
 * ------------------------------------------------------------------ */

const coTecnico = theme(
  'co-tecnico',
  'plagas-corporativa',
  'Técnico',
  'Verde oscuro, grafito y blanco. Precisión y sobriedad para una lectura profesional.',
  ['#1E5A3C', '#0F3A26', '#2F9A66', '#2A3036', '#F3F6F4'],
  {
    brandPrimary: '#1E5A3C',
    brandPrimaryStrong: '#0F3A26',
    brandPrimaryContrast: '#FFFFFF',
    brandSecondary: '#2F9A66',
    accent: '#237A50',
    accentAlt: '#0E7490',
    accentTertiary: '#8A6408',
    surface: '#FFFFFF',
    surfaceAlt: '#F3F6F4',
    surfaceMuted: '#EBF0ED',
    surfaceHighlight: '#DAE9E0',
    surfaceInverse: '#171D1A',
    surfaceInverseSoft: '#2A3036',
    text: '#171D1A',
    textMuted: '#4C5A53',
    border: '#DAE1DC',
    borderStrong: '#B7C3BC',
    focus: '#0E7490',
    focusInverse: '#6FE3C0',
    fontDisplay: FONT_STACKS.poppins,
    fontBody: FONT_STACKS.inter,
    displayWeight: '700',
    displayLetterSpacing: '-0.018em',
    radiusCard: '8px',
    radiusButton: '6px',
    radiusInput: '6px',
    radiusImage: '6px',
    buttonShadow: '0 5px 14px rgb(30 90 60 / 24%)',
    heroBackground: '#F7F9F8',
    bandBackground: '#F3F6F4',
    gradientAccent: 'linear-gradient(120deg, #1E5A3C, #0E7490)',
    iconStyle: 'outline-square',
    decorPattern: 'lines',
    motionAccent: '#1E5A3C',
  },
);

const coNatural = theme(
  'co-natural',
  'plagas-corporativa',
  'Natural',
  'Verde salvia, arena y fondos claros. Comunicación preventiva, menos rotunda.',
  ['#4B6B55', '#37503F', '#8CAB8E', '#C8B89A', '#FAF8F3'],
  {
    brandPrimary: '#43614D',
    brandPrimaryStrong: '#33493B',
    brandPrimaryContrast: '#FFFFFF',
    brandSecondary: '#8CAB8E',
    accent: '#5C7A55',
    accentAlt: '#8A6C34',
    accentTertiary: '#A08A5F',
    surface: '#FFFFFF',
    surfaceAlt: '#FAF8F3',
    surfaceMuted: '#F2EFE7',
    surfaceHighlight: '#E5ECE0',
    surfaceInverse: '#2A312A',
    surfaceInverseSoft: '#3B443A',
    text: '#252B25',
    textMuted: '#525C50',
    border: '#E4E1D7',
    borderStrong: '#CDC9BA',
    focus: '#33493B',
    focusInverse: '#B4D4A6',
    fontDisplay: FONT_STACKS.nunito,
    fontBody: FONT_STACKS.inter,
    displayWeight: '700',
    displayLetterSpacing: '-0.008em',
    radiusCard: '16px',
    radiusButton: '999px',
    radiusInput: '12px',
    radiusImage: '14px',
    buttonShadow: '0 6px 16px rgb(67 97 77 / 20%)',
    heroBackground: '#FBFAF6',
    bandBackground: '#FAF8F3',
    gradientAccent: 'linear-gradient(120deg, #43614D, #A08A5F)',
    iconStyle: 'soft-circle',
    decorPattern: 'organic',
    motionAccent: '#43614D',
  },
);

const coUrgente = theme(
  'co-urgente',
  'plagas-corporativa',
  'Urgente',
  'Azul marino, blanco y acento cálido reservado a las llamadas a la acción.',
  ['#122845', '#0A1829', '#B33F19', '#1D4372', '#F4F7FA'],
  {
    brandPrimary: '#122845',
    brandPrimaryStrong: '#0A1829',
    brandPrimaryContrast: '#FFFFFF',
    brandSecondary: '#1D4372',
    accent: '#A93A16',
    accentAlt: '#8A5A11',
    accentTertiary: '#1D4372',
    surface: '#FFFFFF',
    surfaceAlt: '#F4F7FA',
    surfaceMuted: '#ECF0F6',
    surfaceHighlight: '#DBE4EF',
    surfaceInverse: '#0A1829',
    surfaceInverseSoft: '#142A48',
    text: '#0A1829',
    textMuted: '#44536A',
    border: '#DCE2EB',
    borderStrong: '#BAC5D4',
    focus: '#1D4372',
    focusInverse: '#7DB0EF',
    fontDisplay: FONT_STACKS.poppins,
    fontBody: FONT_STACKS.inter,
    displayWeight: '800',
    displayLetterSpacing: '-0.024em',
    radiusCard: '12px',
    radiusButton: '8px',
    radiusInput: '8px',
    radiusImage: '10px',
    buttonShadow: '0 7px 18px rgb(169 58 22 / 26%)',
    heroBackground: '#F8FAFC',
    bandBackground: '#F4F7FA',
    gradientAccent: 'linear-gradient(120deg, #122845, #A93A16)',
    iconStyle: 'filled-circle',
    decorPattern: 'dots',
    motionAccent: '#A93A16',
  },
);

/* ------------------------------------------------------------------ *
 * Casa Tranquila · Hogar
 * ------------------------------------------------------------------ */

const hgTecnico = theme(
  'hg-tecnico',
  'plagas-hogar',
  'Técnico',
  'Verde oscuro, grafito y blanco. La lectura más precisa de la template doméstica.',
  ['#1D5740', '#0E3826', '#2C8F60', '#2B3134', '#F2F6F3'],
  {
    brandPrimary: '#1D5740',
    brandPrimaryStrong: '#0E3826',
    brandPrimaryContrast: '#FFFFFF',
    brandSecondary: '#2C8F60',
    accent: '#207750',
    accentAlt: '#0E7490',
    accentTertiary: '#8A6408',
    surface: '#FFFFFF',
    surfaceAlt: '#F2F6F3',
    surfaceMuted: '#EAF0EC',
    surfaceHighlight: '#DCEAE2',
    surfaceInverse: '#161C19',
    surfaceInverseSoft: '#2B3134',
    text: '#161C19',
    textMuted: '#4B5953',
    border: '#D9E0DB',
    borderStrong: '#B6C2BB',
    focus: '#0E7490',
    focusInverse: '#6FE3C0',
    fontDisplay: FONT_STACKS.poppins,
    fontBody: FONT_STACKS.inter,
    displayWeight: '700',
    displayLetterSpacing: '-0.016em',
    radiusCard: '10px',
    radiusButton: '8px',
    radiusInput: '8px',
    radiusImage: '8px',
    radiusContainer: '12px',
    buttonShadow: '0 5px 14px rgb(29 87 64 / 24%)',
    heroBackground: '#F7FAF8',
    bandBackground: '#F2F6F3',
    gradientAccent: 'linear-gradient(120deg, #1D5740, #0E7490)',
    iconStyle: 'outline-square',
    decorPattern: 'lines',
    motionAccent: '#1D5740',
  },
);

const hgNatural = theme(
  'hg-natural',
  'plagas-hogar',
  'Natural',
  'Verde salvia, arena y fondos claros. El tono más cercano y preventivo del nicho.',
  ['#4A6952', '#37503F', '#8AAA8C', '#C9B99B', '#FBF9F4'],
  {
    brandPrimary: '#456150',
    brandPrimaryStrong: '#33493C',
    brandPrimaryContrast: '#FFFFFF',
    brandSecondary: '#8AAA8C',
    accent: '#5B7A56',
    accentAlt: '#8A6C34',
    accentTertiary: '#A58F63',
    surface: '#FFFFFF',
    surfaceAlt: '#FBF9F4',
    surfaceMuted: '#F3F0E8',
    surfaceHighlight: '#E7EEE3',
    surfaceInverse: '#2A312B',
    surfaceInverseSoft: '#3C453C',
    text: '#262C27',
    textMuted: '#515C53',
    border: '#E5E2D8',
    borderStrong: '#CEC9BB',
    focus: '#33493C',
    focusInverse: '#B7D7A9',
    fontDisplay: FONT_STACKS.nunito,
    fontBody: FONT_STACKS.inter,
    displayWeight: '700',
    displayLetterSpacing: '-0.006em',
    radiusCard: '20px',
    radiusButton: '999px',
    radiusInput: '14px',
    radiusImage: '18px',
    radiusContainer: '24px',
    buttonShadow: '0 6px 16px rgb(69 97 80 / 20%)',
    heroBackground: '#FCFBF7',
    bandBackground: '#FBF9F4',
    gradientAccent: 'linear-gradient(120deg, #456150, #A58F63)',
    iconStyle: 'soft-circle',
    decorPattern: 'organic',
    motionAccent: '#456150',
  },
);

const hgUrgente = theme(
  'hg-urgente',
  'plagas-hogar',
  'Urgente',
  'Azul marino, blanco y un acento cálido reservado a las llamadas a la acción.',
  ['#132844', '#0A1828', '#A93A16', '#1E4573', '#F5F8FB'],
  {
    brandPrimary: '#132844',
    brandPrimaryStrong: '#0A1828',
    brandPrimaryContrast: '#FFFFFF',
    brandSecondary: '#1E4573',
    accent: '#A93A16',
    accentAlt: '#8A5A11',
    accentTertiary: '#1E4573',
    surface: '#FFFFFF',
    surfaceAlt: '#F5F8FB',
    surfaceMuted: '#EDF1F7',
    surfaceHighlight: '#DEE7F1',
    surfaceInverse: '#0A1828',
    surfaceInverseSoft: '#152B49',
    text: '#0A1828',
    textMuted: '#45536A',
    border: '#DDE3EC',
    borderStrong: '#BBC6D5',
    focus: '#1E4573',
    focusInverse: '#7EB1F0',
    fontDisplay: FONT_STACKS.poppins,
    fontBody: FONT_STACKS.inter,
    displayWeight: '800',
    displayLetterSpacing: '-0.022em',
    radiusCard: '14px',
    radiusButton: '10px',
    radiusInput: '10px',
    radiusImage: '12px',
    radiusContainer: '16px',
    buttonShadow: '0 7px 18px rgb(169 58 22 / 26%)',
    heroBackground: '#F9FBFD',
    bandBackground: '#F5F8FB',
    gradientAccent: 'linear-gradient(120deg, #132844, #A93A16)',
    iconStyle: 'filled-circle',
    decorPattern: 'dots',
    motionAccent: '#A93A16',
  },
);

/* ------------------------------------------------------------------ *
 * Línea y Veta · Portfolio premium
 * ------------------------------------------------------------------ */

const cpArtesanal = theme('cp-artesanal', 'carpinteria-portfolio', 'Artesanal',
  'Roble, arcilla y marfil con tipografía editorial y superficies táctiles.',
  ['#744A2D', '#A5623A', '#D8C6AA', '#F5F0E7', '#29231E'], {
    brandPrimary: '#744A2D', brandPrimaryStrong: '#4E301D', brandSecondary: '#A5623A', accent: '#9A5A34', accentAlt: '#6C7455', accentTertiary: '#C3A477',
    surface: '#FFFCF7', surfaceAlt: '#F5F0E7', surfaceMuted: '#EDE4D6', surfaceHighlight: '#E4D3BC', surfaceInverse: '#29231E', surfaceInverseSoft: '#3D342C',
    text: '#29231E', textMuted: '#6C6156', border: '#DED2C1', borderStrong: '#BFAE98', focus: '#744A2D', focusInverse: '#E9C8A5',
    fontDisplay: FONT_STACKS.playfair, fontBody: FONT_STACKS.inter, displayWeight: '600', displayLetterSpacing: '-0.015em', radiusCard: '2px', radiusButton: '2px', radiusInput: '2px', radiusImage: '1px',
    shadowCard: '0 10px 30px rgb(72 48 31 / 8%)', buttonShadow: '0 8px 18px rgb(116 74 45 / 22%)', heroBackground: '#F5F0E7', bandBackground: '#EDE4D6',
    gradientAccent: 'linear-gradient(120deg, #744A2D, #A5623A)', iconStyle: 'outline-square', decorPattern: 'lines', motionAccent: '#A5623A',
  });

const cpArquitectonico = theme('cp-arquitectonico', 'carpinteria-portfolio', 'Arquitectónico',
  'Grafito, piedra y azul tinta; retícula precisa, radios mínimos y contraste técnico.',
  ['#20262C', '#425466', '#8B949C', '#EEF0F1', '#FFFFFF'], {
    brandPrimary: '#20262C', brandPrimaryStrong: '#101419', brandSecondary: '#425466', accent: '#315D78', accentAlt: '#776B59', accentTertiary: '#687780',
    surface: '#FFFFFF', surfaceAlt: '#EEF0F1', surfaceMuted: '#E3E6E8', surfaceHighlight: '#D6DDE1', surfaceInverse: '#171B1F', surfaceInverseSoft: '#292F35',
    text: '#171B1F', textMuted: '#596168', border: '#D8DDE0', borderStrong: '#AEB6BC', focus: '#315D78', focusInverse: '#8DC4E2',
    fontDisplay: FONT_STACKS.poppins, fontBody: FONT_STACKS.inter, displayWeight: '700', displayLetterSpacing: '-0.035em', radiusCard: '0px', radiusButton: '0px', radiusInput: '0px', radiusImage: '0px',
    shadowCard: 'none', buttonShadow: 'none', heroBackground: '#EEF0F1', bandBackground: '#E3E6E8', gradientAccent: 'linear-gradient(120deg, #20262C, #425466)',
    iconStyle: 'outline-square', decorPattern: 'lines', motionAccent: '#315D78',
  });

const cpContemporaneo = theme('cp-contemporaneo', 'carpinteria-portfolio', 'Contemporáneo',
  'Verde profundo, arena clara y acento cobre con capas suaves y fotografía envolvente.',
  ['#23433A', '#C96F46', '#9DAF9E', '#F2EEE6', '#172A25'], {
    brandPrimary: '#23433A', brandPrimaryStrong: '#172A25', brandSecondary: '#9DAF9E', accent: '#B85F38', accentAlt: '#496B61', accentTertiary: '#C5A66E',
    surface: '#FFFEFA', surfaceAlt: '#F2EEE6', surfaceMuted: '#E8E4DC', surfaceHighlight: '#DCE5DC', surfaceInverse: '#172A25', surfaceInverseSoft: '#29453D',
    text: '#172A25', textMuted: '#5D6964', border: '#D8D8CF', borderStrong: '#B8BDB3', focus: '#23433A', focusInverse: '#A8D7C8',
    fontDisplay: FONT_STACKS.nunito, fontBody: FONT_STACKS.inter, displayWeight: '800', displayLetterSpacing: '-0.025em', radiusCard: '20px', radiusButton: '999px', radiusInput: '12px', radiusImage: '18px',
    shadowCard: '0 12px 34px rgb(23 42 37 / 10%)', buttonShadow: '0 8px 20px rgb(35 67 58 / 24%)', heroBackground: '#F2EEE6', bandBackground: '#E8E4DC',
    gradientAccent: 'linear-gradient(120deg, #23433A, #B85F38)', iconStyle: 'soft-circle', decorPattern: 'organic', motionAccent: '#B85F38',
  });

const ccArtesanal = theme('cc-artesanal', 'carpinteria-configurador', 'Artesanal',
  'Arcilla y papel de taller: controles cuadrados, contraste cálido y ritmo pausado.',
  ['#7A4B30', '#B06A3F', '#D7B993', '#F7F1E8', '#2E251F'], {
    brandPrimary: '#7A4B30', brandPrimaryStrong: '#50301F', brandSecondary: '#B06A3F', accent: '#A65F36', accentAlt: '#697052', accentTertiary: '#C5A16F',
    surface: '#FFFCF8', surfaceAlt: '#F7F1E8', surfaceMuted: '#EEE3D4', surfaceHighlight: '#E7D3B8', surfaceInverse: '#2E251F', surfaceInverseSoft: '#43372E', text: '#2E251F', textMuted: '#6E6055',
    border: '#DED0BD', borderStrong: '#BDAA91', focus: '#7A4B30', focusInverse: '#E6C29D', fontDisplay: FONT_STACKS.playfair, fontBody: FONT_STACKS.inter,
    displayWeight: '600', displayLetterSpacing: '-0.012em', radiusCard: '4px', radiusButton: '4px', radiusInput: '4px', radiusImage: '2px', heroBackground: '#F7F1E8', bandBackground: '#EEE3D4',
    gradientAccent: 'linear-gradient(120deg, #7A4B30, #A65F36)', iconStyle: 'outline-square', decorPattern: 'lines', motionAccent: '#A65F36',
  });
const ccArquitectonico = theme('cc-arquitectonico', 'carpinteria-configurador', 'Arquitectónico',
  'Blanco técnico, negro y azul: módulos estrictos, jerarquía gráfica y precisión.',
  ['#161B20', '#2D617D', '#687681', '#F0F2F3', '#FFFFFF'], {
    brandPrimary: '#1C536F', brandPrimaryStrong: '#13384A', brandSecondary: '#687681', accent: '#2D617D', accentAlt: '#7B6A4C', accentTertiary: '#526C78',
    surface: '#FFFFFF', surfaceAlt: '#F0F2F3', surfaceMuted: '#E4E8EA', surfaceHighlight: '#D7E1E6', surfaceInverse: '#161B20', surfaceInverseSoft: '#282F35', text: '#161B20', textMuted: '#59636B',
    border: '#D9DEE1', borderStrong: '#ABB5BB', focus: '#1C536F', focusInverse: '#85C8E7', fontDisplay: FONT_STACKS.poppins, fontBody: FONT_STACKS.inter,
    displayWeight: '800', displayLetterSpacing: '-0.035em', radiusCard: '0px', radiusButton: '0px', radiusInput: '0px', radiusImage: '0px', shadowCard: 'none', buttonShadow: 'none', heroBackground: '#F0F2F3', bandBackground: '#E4E8EA',
    gradientAccent: 'linear-gradient(120deg, #161B20, #1C536F)', iconStyle: 'outline-square', decorPattern: 'lines', motionAccent: '#2D617D',
  });
const ccContemporaneo = theme('cc-contemporaneo', 'carpinteria-configurador', 'Contemporáneo',
  'Azul petróleo y coral con módulos redondeados, capas suaves y respuesta más dinámica.',
  ['#164E55', '#D1674C', '#75A4A0', '#F4F1EA', '#143236'], {
    brandPrimary: '#164E55', brandPrimaryStrong: '#10383D', brandSecondary: '#75A4A0', accent: '#C25940', accentAlt: '#497E78', accentTertiary: '#C6A568',
    surface: '#FFFEFB', surfaceAlt: '#F4F1EA', surfaceMuted: '#E6ECE8', surfaceHighlight: '#D7E7E3', surfaceInverse: '#143236', surfaceInverseSoft: '#214A4E', text: '#143236', textMuted: '#5A6968',
    border: '#D5DEDA', borderStrong: '#AEBDB7', focus: '#164E55', focusInverse: '#9AD8D3', fontDisplay: FONT_STACKS.nunito, fontBody: FONT_STACKS.inter,
    displayWeight: '800', displayLetterSpacing: '-0.025em', radiusCard: '18px', radiusButton: '999px', radiusInput: '12px', radiusImage: '16px', shadowCard: '0 12px 30px rgb(20 50 54 / 10%)',
    heroBackground: '#F4F1EA', bandBackground: '#E6ECE8', gradientAccent: 'linear-gradient(120deg, #164E55, #C25940)', iconStyle: 'soft-circle', decorPattern: 'organic', motionAccent: '#C25940',
  });

const ctArtesanal = theme('ct-artesanal', 'carpinteria-taller', 'Artesanal', 'Madera tostada, lino y carbón con textura cálida y tipografía de libro.', ['#6B4329', '#A86439', '#D2B48C', '#F3ECE1', '#282019'], { brandPrimary: '#6B4329', brandPrimaryStrong: '#452919', brandSecondary: '#A86439', accent: '#D0A06C', accentAlt: '#6E7656', accentTertiary: '#BD8D5C', surface: '#FFFCF7', surfaceAlt: '#F3ECE1', surfaceMuted: '#E9DDCD', surfaceHighlight: '#DFCCB3', surfaceInverse: '#282019', surfaceInverseSoft: '#3D3127', text: '#282019', textMuted: '#6A5D52', border: '#DDCFBD', borderStrong: '#BBA88F', focus: '#6B4329', focusInverse: '#E5BC8C', fontDisplay: FONT_STACKS.playfair, fontBody: FONT_STACKS.inter, displayWeight: '600', displayLetterSpacing: '-0.012em', radiusCard: '2px', radiusButton: '2px', radiusInput: '2px', radiusImage: '1px', heroBackground: '#F3ECE1', bandBackground: '#E9DDCD', gradientAccent: 'linear-gradient(120deg, #6B4329, #A86439)', iconStyle: 'outline-square', decorPattern: 'lines', motionAccent: '#A86439' });
const ctArquitectonico = theme('ct-arquitectonico', 'carpinteria-taller', 'Arquitectónico', 'Carbón, hormigón y latón apagado; composición rigurosa sin ornamento.', ['#1C2023', '#4B5961', '#9B8561', '#ECEEEE', '#FFFFFF'], { brandPrimary: '#283D48', brandPrimaryStrong: '#18252C', brandSecondary: '#60717A', accent: '#AA8A58', accentAlt: '#536A73', accentTertiary: '#8A7655', surface: '#FFFFFF', surfaceAlt: '#ECEEEE', surfaceMuted: '#E0E4E5', surfaceHighlight: '#D2DADD', surfaceInverse: '#1C2023', surfaceInverseSoft: '#2D3438', text: '#1C2023', textMuted: '#586166', border: '#D5DADC', borderStrong: '#AAB2B6', focus: '#283D48', focusInverse: '#91BDD0', fontDisplay: FONT_STACKS.poppins, fontBody: FONT_STACKS.inter, displayWeight: '700', displayLetterSpacing: '-0.035em', radiusCard: '0px', radiusButton: '0px', radiusInput: '0px', radiusImage: '0px', shadowCard: 'none', heroBackground: '#ECEEEE', bandBackground: '#E0E4E5', gradientAccent: 'linear-gradient(120deg, #1C2023, #536A73)', iconStyle: 'outline-square', decorPattern: 'lines', motionAccent: '#AA8A58' });
const ctContemporaneo = theme('ct-contemporaneo', 'carpinteria-taller', 'Contemporáneo', 'Verde bosque, terracota y crema con fotografía suave y superficies envolventes.', ['#24483C', '#C66B46', '#8CA795', '#F5F0E7', '#172E27'], { brandPrimary: '#24483C', brandPrimaryStrong: '#172E27', brandSecondary: '#8CA795', accent: '#D1835E', accentAlt: '#53786B', accentTertiary: '#C3A36B', surface: '#FFFEFA', surfaceAlt: '#F5F0E7', surfaceMuted: '#E6ECE5', surfaceHighlight: '#D8E4DC', surfaceInverse: '#172E27', surfaceInverseSoft: '#29483E', text: '#172E27', textMuted: '#5B6963', border: '#D7DED8', borderStrong: '#AFBDB5', focus: '#24483C', focusInverse: '#A7D5C5', fontDisplay: FONT_STACKS.nunito, fontBody: FONT_STACKS.inter, displayWeight: '800', displayLetterSpacing: '-0.025em', radiusCard: '18px', radiusButton: '999px', radiusInput: '12px', radiusImage: '17px', shadowCard: '0 12px 32px rgb(23 46 39 / 10%)', heroBackground: '#F5F0E7', bandBackground: '#E6ECE5', gradientAccent: 'linear-gradient(120deg, #24483C, #C66B46)', iconStyle: 'soft-circle', decorPattern: 'organic', motionAccent: '#C66B46' });


/* --------------------------------- Estudio -------------------------------- */
/*
 * Estudio no usa serif de lujo ni sans redondeada: usa una grotesca apretada
 * como display, que es lo que le da el aire de estudio de diseño y lo separa
 * de Playfair (Elegance, Pelos Paz y Amor) y de Nunito (Peludos Felices).
 * Radios a cero y sombras a ninguna: la estructura es el filete.
 */
const esBase: Partial<ThemeTokens> = {
  fontDisplay: FONT_STACKS.inter,
  fontBody: FONT_STACKS.inter,
  displayWeight: '500',
  displayLetterSpacing: '-0.035em',
  h1Size: 'clamp(2.7rem, 8.2vw, 6.6rem)',
  h1LineHeight: '0.98',
  contentMax: '1380px',
  radiusCard: '0px',
  radiusButton: '0px',
  radiusInput: '0px',
  radiusImage: '0px',
  radiusContainer: '0px',
  shadowCard: 'none',
  shadowFloat: 'none',
  cardStyle: 'flat',
  cardBorderWidth: '1px',
  decorPattern: 'none',
  iconStyle: 'line',
  buttonTransform: 'none',
  buttonLetterSpacing: '0.02em',
};

const esTinta = theme('es-tinta-papel', 'canine-estudio', 'Tinta y papel', 'Papel cálido, tinta casi negra y un solo acento ocre. La lectura de estudio por defecto.', ['#171614', '#8A6A3B', '#FBFAF7', '#EFEBE3', '#FFFFFF'], { ...esBase, brandPrimary: '#8A6A3B', brandPrimaryStrong: '#6B5129', brandSecondary: '#C0A87C', accent: '#8A6A3B', accentAlt: '#B7A88C', accentTertiary: '#D9CFBB', surface: '#FBFAF7', surfaceAlt: '#EFEBE3', surfaceMuted: '#E7E2D8', surfaceHighlight: '#F3F0E9', surfaceInverse: '#171614', surfaceInverseSoft: '#26241F', text: '#171614', textMuted: '#5E5A52', border: '#DCD7CB', borderStrong: '#B8B1A2', focus: '#6B5129', focusInverse: '#C0A87C', heroBackground: '#FBFAF7', bandBackground: '#EFEBE3', motionAccent: '#8A6A3B' });

const esHueso = theme('es-hueso-oliva', 'canine-estudio', 'Hueso y oliva', 'Papel hueso frío con acento oliva profundo. Más sobrio y más botánico.', ['#1A1D18', '#4F6337', '#FAFAF8', '#ECEEE7', '#FFFFFF'], { ...esBase, brandPrimary: '#4F6337', brandPrimaryStrong: '#3B4A29', brandSecondary: '#8FA274', accent: '#4F6337', accentAlt: '#9AA98A', accentTertiary: '#C9D2BE', surface: '#FAFAF8', surfaceAlt: '#ECEEE7', surfaceMuted: '#E3E7DC', surfaceHighlight: '#F1F3EC', surfaceInverse: '#1A1D18', surfaceInverseSoft: '#2A2E25', text: '#1A1D18', textMuted: '#585D50', border: '#D9DDD1', borderStrong: '#B2B8A7', focus: '#3B4A29', focusInverse: '#8FA274', heroBackground: '#FAFAF8', bandBackground: '#ECEEE7', motionAccent: '#4F6337' });

const esCarbon = theme('es-carbon-cobre', 'canine-estudio', 'Carbón y cobre', 'Papel gris frío, tinta carbón y acento cobre. La versión más urbana de la familia.', ['#15171A', '#A75E38', '#F8F9FA', '#EAECEF', '#FFFFFF'], { ...esBase, brandPrimary: '#A75E38', brandPrimaryStrong: '#834729', brandSecondary: '#C9907A', accent: '#A75E38', accentAlt: '#C3907A', accentTertiary: '#DFC7BA', surface: '#F8F9FA', surfaceAlt: '#EAECEF', surfaceMuted: '#E1E4E8', surfaceHighlight: '#F0F1F3', surfaceInverse: '#15171A', surfaceInverseSoft: '#232629', text: '#15171A', textMuted: '#565B62', border: '#D8DBDF', borderStrong: '#AFB4BA', focus: '#834729', focusInverse: '#C3907A', heroBackground: '#F8F9FA', bandBackground: '#EAECEF', motionAccent: '#A75E38' });

const OFFICIAL_THEMES: ThemeDefinition[] = [
  pfColorido,
  pfSpa,
  pfPremium,
  ppaNatural,
  ppaRosa,
  ppaNocturno,
  elOroNegro,
  elMarfil,
  elVioleta,
  pcoLavanda,
  pcoMenta,
  pcoGrafito,
  pcoArriazaCalido,
  esTinta,
  esHueso,
  esCarbon,
  prTecnico,
  prNatural,
  prUrgente,
  coTecnico,
  coNatural,
  coUrgente,
  hgTecnico,
  hgNatural,
  hgUrgente,
  cpArtesanal,
  cpArquitectonico,
  cpContemporaneo,
  ccArtesanal,
  ccArquitectonico,
  ccContemporaneo,
  ctArtesanal,
  ctArquitectonico,
  ctContemporaneo,
];

const VISUAL_PRESETS: Array<Partial<ThemeTokens>> = [
  {
    cardStyle: 'flat',
    cardBorderWidth: '1px',
    shadowCard: 'none',
    shadowFloat: '0 8px 22px rgb(16 23 47 / 10%)',
    cardGradient: 'none',
    cardBackdropFilter: 'none',
    surfaceGlow: 'none',
    motionPreset: 'calm',
    durationBase: '180ms',
    revealDistance: '10px',
    imageHoverScale: '1.015',
  },
  {
    cardStyle: 'elevated',
    cardBorderWidth: '1px',
    shadowCard: '0 10px 28px rgb(16 23 47 / 10%)',
    shadowFloat: '0 18px 42px rgb(16 23 47 / 16%)',
    cardGradient: 'none',
    cardBackdropFilter: 'none',
    surfaceGlow: 'radial-gradient(circle at 15% 0%, color-mix(in srgb, var(--wf-brand-primary) 12%, transparent), transparent 42%)',
    motionPreset: 'balanced',
    durationBase: '240ms',
    revealDistance: '18px',
    imageHoverScale: '1.025',
  },
  {
    cardStyle: 'elevated',
    cardBorderWidth: '1px',
    shadowCard: '0 14px 36px rgb(8 12 26 / 16%)',
    shadowFloat: '0 24px 54px rgb(8 12 26 / 24%)',
    cardGradient: 'linear-gradient(145deg, color-mix(in srgb, var(--wf-card-background) 92%, white), color-mix(in srgb, var(--wf-card-background) 86%, var(--wf-brand-primary)))',
    cardBackdropFilter: 'blur(12px) saturate(118%)',
    surfaceGlow: 'radial-gradient(circle at 82% 10%, color-mix(in srgb, var(--wf-accent) 18%, transparent), transparent 38%)',
    motionPreset: 'expressive',
    durationBase: '300ms',
    revealDistance: '24px',
    imageHoverScale: '1.04',
  },
];

/** Tres acabados perceptiblemente distintos por template, sin alterar estructura. */
export const THEMES: ThemeDefinition[] = OFFICIAL_THEMES.map((definition, index) => ({
  ...definition,
  tokens: { ...definition.tokens, ...VISUAL_PRESETS[index % 3] },
}));

/**
 * Familia de animación y color de los efectos por tema.
 *
 * Se aplica después de construir los temas para no repetir los tokens dentro de
 * cada literal: el estilo acompaña al carácter del tema y el acento sigue a su
 * propio color de marca, de modo que ningún efecto animado desentona.
 */
const MOTION_BY_THEME: Record<string, { style: ThemeTokens['animationStyle']; accent: string }> = {
  'pf-colorido-alegre': { style: 'cinetico', accent: '#D62E63' },
  'pf-spa-elegante': { style: 'suave', accent: '#3F6B52' },
  'pf-premium-oscuro': { style: 'brillo', accent: '#FF5C8A' },
  'ppa-natural-sereno': { style: 'suave', accent: '#96682A' },
  'ppa-rosa-boutique': { style: 'elevacion', accent: '#A85572' },
  'ppa-nocturno-calido': { style: 'brillo', accent: '#D8B878' },
  'el-oro-negro': { style: 'brillo', accent: '#AD8130' },
  'el-marfil-editorial': { style: 'suave', accent: '#8C6B3F' },
  'el-violeta-imperial': { style: 'elevacion', accent: '#8257D4' },
  'pco-lavanda-profesional': { style: 'elevacion', accent: '#8A43D6' },
  'pco-menta-limpia': { style: 'suave', accent: '#0F7D6B' },
  'pco-grafito-tecnologico': { style: 'cinetico', accent: '#5B8CFF' },
  'pco-arriaza-calido': { style: 'suave', accent: '#B5533C' },
  // Estudio: movimiento contenido; el gesto es la máscara, no el rebote.
  'es-tinta-papel': { style: 'suave', accent: '#8A6A3B' },
  'es-hueso-oliva': { style: 'suave', accent: '#4F6337' },
  'es-carbon-cobre': { style: 'suave', accent: '#A75E38' },
};

for (const definition of THEMES) {
  const motion = MOTION_BY_THEME[definition.id];
  if (!motion) continue;
  definition.tokens.animationStyle = motion.style;
  // Si el tema no declara acento propio, hereda su color de marca.
  definition.tokens.motionAccent = motion.accent || definition.tokens.brandPrimary;
}

const THEME_INDEX = new Map(THEMES.map((t) => [t.id, t]));

export function getTheme(themeId: string): ThemeDefinition | undefined {
  return THEME_INDEX.get(themeId);
}

export function getThemesForTemplate(templateId: string): ThemeDefinition[] {
  return THEMES.filter((t) => t.templateId === templateId);
}

/**
 * Resuelve la cascada documentada: tokens de template → tema global →
 * override de página → ajustes de token del proyecto.
 */
export function resolveEffectiveTheme(
  globalThemeId: string,
  pageOverrideId: string | null,
  fallbackTemplateId: string,
): ThemeDefinition {
  const page = pageOverrideId ? THEME_INDEX.get(pageOverrideId) : undefined;
  if (page) return page;
  const global = THEME_INDEX.get(globalThemeId);
  if (global) return global;
  const first = getThemesForTemplate(fallbackTemplateId)[0];
  if (first) return first;
  return THEMES[0];
}
