import { inferSurfaceContext, type SectionComponent, type SectionVariant } from './registry';
import { PELUDOS_FELICES_SECTIONS } from './templates/peludosFelices';
import { PELOS_PAZ_AMOR_SECTIONS } from './templates/pelosPazAmor';
import { ELEGANCE_SECTIONS } from './templates/elegance';
import { PELUDOS_AND_CO_SECTIONS } from './templates/peludosAndCo';
import { COMMON_PAGE_SECTIONS } from './templates/pages';
// Estudio: quinta familia canina, tipográfica y de retícula.
import { ESTUDIO_SECTIONS } from './templates/estudio';
import { PLAGAS_RESPUESTA_RAPIDA_SECTIONS } from './templates/plagas/respuestaRapida';
import { PLAGAS_CORPORATIVA_SECTIONS } from './templates/plagas/corporativa';
import { PLAGAS_HOGAR_SECTIONS } from './templates/plagas/hogar';
import { CARPINTERIA_PORTFOLIO_SECTIONS } from './templates/carpinteria/portfolio';
import { CARPINTERIA_CONFIGURADOR_SECTIONS } from './templates/carpinteria/configurador';
import { CARPINTERIA_TALLER_SECTIONS } from './templates/carpinteria/taller';
import { PLAGAS_RESPUESTA_RAPIDA_VARIANTS } from './contracts/plagas';
import { PLAGAS_CORPORATIVA_VARIANTS } from './contracts/plagasCorporativa';
import { PLAGAS_HOGAR_VARIANTS } from './contracts/plagasHogar';
import { CARPINTERIA_PORTFOLIO_VARIANTS } from './contracts/carpinteriaPortfolio';
import { CARPINTERIA_CONFIGURADOR_VARIANTS } from './contracts/carpinteriaConfigurador';
import { CARPINTERIA_TALLER_VARIANTS } from './contracts/carpinteriaTaller';
// Biblioteca compartida: no pertenece a ningún nicho.
import { ESTUDIO_VARIANTS } from './contracts/estudio';
import { SHARED_VARIANTS } from './contracts/shared';
import { SHARED_TEAM_SECTIONS } from './templates/shared/team';
import { SHARED_CATALOG_SECTIONS } from './templates/shared/catalog';
// Familias visuales: Premium, Minimalista y Convencional, cada una con su propia
// composición. Son el catálogo de referencia del generador.
import { PROFILE_VARIANTS } from './contracts/profiles';
import { PROFILE_SECTIONS } from './templates/shared/profiles';
// Segunda generación: resultados, reserva propia y segundas composiciones.
import { PROFILE_B_VARIANTS } from './contracts/profiles-b';
import { PROFILE_SECTIONS_B } from './templates/shared/profiles-b';

export const SECTION_COMPONENTS: Record<string, SectionComponent> = {
  ...PELUDOS_FELICES_SECTIONS,
  ...PELOS_PAZ_AMOR_SECTIONS,
  ...ELEGANCE_SECTIONS,
  ...PELUDOS_AND_CO_SECTIONS,
  ...ESTUDIO_SECTIONS,
  ...COMMON_PAGE_SECTIONS,
  ...PLAGAS_RESPUESTA_RAPIDA_SECTIONS,
  ...PLAGAS_CORPORATIVA_SECTIONS,
  ...PLAGAS_HOGAR_SECTIONS,
  ...CARPINTERIA_PORTFOLIO_SECTIONS,
  ...CARPINTERIA_CONFIGURADOR_SECTIONS,
  ...CARPINTERIA_TALLER_SECTIONS,
  ...SHARED_TEAM_SECTIONS,
  ...SHARED_CATALOG_SECTIONS,
  ...PROFILE_SECTIONS,
  ...PROFILE_SECTIONS_B,
};

const NICHE = 'peluqueria-canina';

function variant(v: Omit<SectionVariant, 'nicheId' | 'schemaVersion' | 'surfaceContext'> & { schemaVersion?: string; surfaceContext?: SectionVariant['surfaceContext'] }): SectionVariant {
  return {
    nicheId: NICHE,
    schemaVersion: v.schemaVersion ?? '1.0.0',
    layoutContract: {
      containment: v.sectionType === 'header' ? 'document' : 'section',
      overflow: v.sectionType === 'header' ? 'visible' : 'clip',
    },
    surfaceContext: v.surfaceContext ?? inferSurfaceContext(v),
    ...v,
  } as SectionVariant;
}

const RESPONSIVE_STACK = { desktop: 'multi-columna', tablet: '2 columnas', mobile: '1 columna' };

/**
 * Contratos de las variantes implementadas. El Creador Web valida contra esto
 * antes de permitir combinar bloques de distintas templates del mismo nicho.
 */
export const SECTION_VARIANTS: SectionVariant[] = [
  ...CARPINTERIA_PORTFOLIO_VARIANTS,
  ...CARPINTERIA_CONFIGURADOR_VARIANTS,
  ...CARPINTERIA_TALLER_VARIANTS,
  /* ---------------------------- Peludos Felices --------------------------- */
  variant({
    id: 'pf-header-01',
    sectionType: 'header',
    sourceTemplateId: 'canine-peludos-felices',
    name: 'Header alegre con WhatsApp',
    description: 'Barra blanca, navegación centrada, bloque de WhatsApp y CTA rosa.',
    requiredFields: ['business.name', 'navigation.items', 'navigation.primaryCta', 'business.whatsapp'],
    optionalFields: ['business.logo'],
    collectionLimits: [{ collection: 'navigation.items', min: 3, max: 8 }],
    themeTokenCoverage: ['brandPrimary', 'surface', 'text', 'textMuted', 'border', 'whatsapp'],
    responsiveContract: { desktop: 'logo · nav · acciones', tablet: 'logo · acciones', mobile: 'drawer' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: ['footer'],
    conflicts: [],
    assetSlots: [{ key: 'logo', ratio: 'libre', minWidth: 240, minHeight: 80 }],
    required: true,
    fixed: true,
  }),
  variant({
    id: 'pf-hero-01',
    sectionType: 'hero',
    sourceTemplateId: 'canine-peludos-felices',
    name: 'Hero recortado con mancha',
    description: 'Dos columnas 46/54, perro recortado sobre forma orgánica y microbeneficios.',
    requiredFields: ['content.hero.title', 'content.hero.paragraph', 'content.hero.primaryCta', 'content.hero.image'],
    optionalFields: ['content.hero.note', 'content.hero.secondaryCta'],
    collectionLimits: [{ collection: 'content.hero.microBenefits', min: 2, max: 4 }],
    themeTokenCoverage: ['brandPrimary', 'brandSecondary', 'heroBackground', 'text', 'textMuted'],
    responsiveContract: { desktop: '2 columnas', tablet: '2 columnas', mobile: 'texto sobre foto' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: ['booking'],
    conflicts: [],
    assetSlots: [{ key: 'hero', ratio: '4:5', minWidth: 1600, minHeight: 2000 }],
    required: true,
    fixed: false,
  }),
  variant({
    id: 'pf-services-01',
    sectionType: 'services',
    sourceTemplateId: 'canine-peludos-felices',
    name: 'Cinco servicios con icono circular',
    description: 'Cards centradas con icono de color, sin precio visible y modal de detalle.',
    requiredFields: ['services'],
    optionalFields: ['content.headings.services'],
    collectionLimits: [{ collection: 'services', min: 3, max: 6 }],
    themeTokenCoverage: ['brandPrimary', 'accent', 'accentAlt', 'surfaceAlt', 'radiusCard'],
    responsiveContract: { desktop: '5 columnas', tablet: '3 columnas', mobile: '2 → 1 columna' },
    navigationOutputs: ['#servicios', '/servicios/{slug}'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pf-packages-01',
    sectionType: 'packages',
    sourceTemplateId: 'canine-peludos-felices',
    name: 'Franja partida paquetes + ventajas',
    description: 'Tres paquetes sobre rosa pálido junto al bloque “Por qué elegirnos”.',
    requiredFields: ['packages', 'content.benefits'],
    optionalFields: ['content.ambienceImage'],
    collectionLimits: [
      { collection: 'packages', min: 2, max: 4 },
      { collection: 'content.benefits', min: 3, max: 5 },
    ],
    themeTokenCoverage: ['brandPrimary', 'brandSecondary', 'accent', 'surfaceHighlight'],
    responsiveContract: RESPONSIVE_STACK,
    navigationOutputs: ['#paquetes', '#por-que-elegirnos'],
    requiredCompanions: ['booking'],
    conflicts: ['plans'],
    assetSlots: [{ key: 'benefitsPhoto', ratio: '4:5', minWidth: 1200, minHeight: 1500 }],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pf-testimonials-01',
    sectionType: 'testimonials',
    sourceTemplateId: 'canine-peludos-felices',
    name: 'Franja partida reseñas + galería',
    description: 'Cuatro reseñas compactas junto a una galería de cuatro fotos cuadradas.',
    requiredFields: ['testimonials', 'gallery'],
    optionalFields: ['contact.socialLinks'],
    collectionLimits: [
      { collection: 'testimonials', min: 2, max: 6 },
      { collection: 'gallery', min: 4, max: 8 },
    ],
    themeTokenCoverage: ['brandPrimary', 'star', 'surface', 'surfaceAlt'],
    responsiveContract: RESPONSIVE_STACK,
    navigationOutputs: ['#resenas', '#galeria'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'gallery', ratio: '1:1', minWidth: 1000, minHeight: 1000 }],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pf-testimonials-02',
    sectionType: 'testimonials',
    sourceTemplateId: 'canine-peludos-felices',
    name: 'Reseñas en carrusel',
    description: 'Variante de una sola card con scroll-snap y paginación, sin galería adjunta.',
    requiredFields: ['testimonials'],
    optionalFields: [],
    collectionLimits: [{ collection: 'testimonials', min: 1, max: 8 }],
    themeTokenCoverage: ['brandPrimary', 'star', 'surfaceAlt'],
    responsiveContract: { desktop: '1 card', tablet: '1 card', mobile: '1 card' },
    navigationOutputs: ['#resenas'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pf-booking-01',
    sectionType: 'booking',
    sourceTemplateId: 'canine-peludos-felices',
    name: 'Franja operativa reserva + contacto + mapa + FAQ',
    description: 'Cuatro áreas juntas antes del footer, con solicitud pendiente en dos pasos.',
    requiredFields: ['booking', 'business.phone', 'business.email', 'business.address', 'faqs', 'contact.mapLinkUrl'],
    optionalFields: ['contact.socialLinks'],
    collectionLimits: [{ collection: 'faqs', min: 3, max: 8 }],
    themeTokenCoverage: ['accent', 'brandPrimary', 'surface', 'border'],
    responsiveContract: { desktop: '4 columnas', tablet: '2 columnas', mobile: 'reserva → contacto → mapa → FAQ' },
    navigationOutputs: ['#reserva', '#contacto', '#faq'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: false,
  }),
  variant({
    id: 'pf-footer-01',
    sectionType: 'footer',
    sourceTemplateId: 'canine-peludos-felices',
    name: 'Footer rosa ondulado',
    description: 'Cuatro columnas, borde superior ondulado y franja legal.',
    requiredFields: ['business.legalName', 'content.legal', 'navigation.items'],
    optionalFields: ['contact.socialLinks'],
    collectionLimits: [],
    themeTokenCoverage: ['brandPrimary', 'surfaceHighlight', 'text', 'textMuted'],
    responsiveContract: RESPONSIVE_STACK,
    navigationOutputs: ['/aviso-legal', '/privacidad', '/cookies'],
    requiredCompanions: ['header'],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: true,
  }),

  /* --------------------------- Pelos, Paz y Amor -------------------------- */
  variant({
    id: 'ppa-header-01',
    sectionType: 'header',
    sourceTemplateId: 'canine-pelos-paz-amor',
    name: 'Header editorial dorado',
    description: 'Logo lineal, navegación centrada, CTA dorado y WhatsApp circular.',
    requiredFields: ['business.name', 'navigation.items', 'business.whatsapp'],
    optionalFields: ['business.logo'],
    collectionLimits: [{ collection: 'navigation.items', min: 3, max: 8 }],
    themeTokenCoverage: ['brandPrimary', 'surface', 'border', 'whatsapp'],
    responsiveContract: { desktop: 'logo · nav · acciones', tablet: 'logo · acciones', mobile: 'drawer' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: ['footer'],
    conflicts: [],
    assetSlots: [{ key: 'logo', ratio: 'libre', minWidth: 240, minHeight: 80 }],
    required: true,
    fixed: true,
  }),
  variant({
    id: 'ppa-hero-01',
    sectionType: 'hero',
    sourceTemplateId: 'canine-pelos-paz-amor',
    name: 'Hero fotográfico a sangre',
    description: 'Fotografía luminosa a toda anchura con copy sobre velo marfil a la izquierda.',
    requiredFields: ['content.hero.title', 'content.hero.paragraph', 'content.hero.image'],
    optionalFields: ['content.hero.eyebrow', 'content.hero.secondaryCta'],
    collectionLimits: [{ collection: 'content.hero.microBenefits', min: 2, max: 4 }],
    themeTokenCoverage: ['brandPrimary', 'surfaceAlt', 'text', 'textMuted'],
    responsiveContract: { desktop: 'overlay 43%', tablet: 'overlay 62%', mobile: 'foto + bloque marfil' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: ['booking'],
    conflicts: [],
    assetSlots: [{ key: 'hero', ratio: '2:1', minWidth: 2400, minHeight: 1200 }],
    required: true,
    fixed: false,
  }),
  variant({
    id: 'ppa-services-01',
    sectionType: 'services',
    sourceTemplateId: 'canine-pelos-paz-amor',
    name: 'Cuatro servicios altos con lista',
    description: 'Cards altas con inclusiones marcadas, precio desde y botón de reserva.',
    requiredFields: ['services'],
    optionalFields: ['content.pricingNote'],
    collectionLimits: [{ collection: 'services', min: 4, max: 4 }],
    themeTokenCoverage: ['brandPrimary', 'border', 'surface'],
    responsiveContract: { desktop: '4 columnas', tablet: '2×2', mobile: '1 columna' },
    navigationOutputs: ['#servicios'],
    requiredCompanions: ['booking'],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'ppa-transformations-01',
    sectionType: 'transformations',
    sourceTemplateId: 'canine-pelos-paz-amor',
    name: 'Comparadores arrastrables',
    description: 'Bloque editorial lateral y tres comparadores antes/después con slider accesible.',
    requiredFields: ['transformations'],
    optionalFields: ['content.headings.transformations'],
    collectionLimits: [{ collection: 'transformations', min: 3, max: 6 }],
    themeTokenCoverage: ['brandPrimary', 'surfaceAlt', 'radiusImage'],
    responsiveContract: { desktop: 'editorial + 3', tablet: 'apilado', mobile: 'carrusel' },
    navigationOutputs: ['#transformaciones', '/galeria?categoria=transformaciones'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'transformation', ratio: '1:1', minWidth: 1200, minHeight: 1200 }],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'ppa-process-01',
    sectionType: 'process',
    sourceTemplateId: 'canine-pelos-paz-amor',
    name: 'Proceso de cuatro pasos con línea',
    description: 'Círculos marfil con iconos lineales y conector punteado decorativo.',
    requiredFields: ['content.processSteps'],
    optionalFields: [],
    collectionLimits: [{ collection: 'content.processSteps', min: 3, max: 5 }],
    themeTokenCoverage: ['brandPrimary', 'surfaceAlt', 'borderStrong'],
    responsiveContract: { desktop: '4 columnas', tablet: '2×2', mobile: 'lista numerada' },
    navigationOutputs: ['#proceso'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'ppa-testimonials-01',
    sectionType: 'testimonials',
    sourceTemplateId: 'canine-pelos-paz-amor',
    name: 'Mosaico testimonios + equipo + motivos + ambiente',
    description: 'Cuatro áreas verticales con fondos alternos, tal y como define la referencia.',
    requiredFields: ['testimonials', 'team', 'content.benefits', 'content.ambienceImage'],
    optionalFields: [],
    collectionLimits: [
      { collection: 'testimonials', min: 1, max: 6 },
      { collection: 'team', min: 2, max: 4 },
      { collection: 'content.benefits', min: 3, max: 6 },
    ],
    themeTokenCoverage: ['brandPrimary', 'surface', 'surfaceAlt', 'star'],
    responsiveContract: RESPONSIVE_STACK,
    navigationOutputs: ['#testimonios', '#equipo'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [
      { key: 'team', ratio: '4:3', minWidth: 1000, minHeight: 750 },
      { key: 'ambience', ratio: '3:4', minWidth: 1200, minHeight: 1600 },
    ],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'ppa-faq-01',
    sectionType: 'faq',
    sourceTemplateId: 'canine-pelos-paz-amor',
    name: 'FAQ en rejilla 3×2',
    description: 'Seis acordeones con chevron; permite varias respuestas abiertas.',
    requiredFields: ['faqs'],
    optionalFields: [],
    collectionLimits: [{ collection: 'faqs', min: 4, max: 9 }],
    themeTokenCoverage: ['border', 'surface', 'brandPrimary'],
    responsiveContract: { desktop: '3 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#faq'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'ppa-footer-01',
    sectionType: 'footer',
    sourceTemplateId: 'canine-pelos-paz-amor',
    name: 'Footer marfil con franja dorada',
    description: 'Cuatro columnas y barra inferior en color de marca.',
    requiredFields: ['business.legalName', 'content.legal'],
    optionalFields: ['contact.socialLinks'],
    collectionLimits: [],
    themeTokenCoverage: ['brandPrimary', 'surfaceAlt', 'textMuted'],
    responsiveContract: RESPONSIVE_STACK,
    navigationOutputs: ['#contacto', '/aviso-legal', '/privacidad'],
    requiredCompanions: ['header'],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: true,
  }),

  /* -------------------------------- Elegance ------------------------------ */
  variant({
    id: 'el-header-01',
    surfaceContext: 'dark',
    sectionType: 'header',
    sourceTemplateId: 'canine-elegance',
    name: 'Header translúcido sobre hero',
    description: 'Integrado en la imagen oscura; se vuelve sólido al hacer scroll.',
    requiredFields: ['business.name', 'navigation.items'],
    optionalFields: ['business.logo'],
    collectionLimits: [{ collection: 'navigation.items', min: 3, max: 8 }],
    themeTokenCoverage: ['brandPrimary', 'surfaceInverse', 'textInverse'],
    responsiveContract: { desktop: 'logo · nav · CTA', tablet: 'logo · CTA', mobile: 'drawer oscuro' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: ['hero', 'footer'],
    conflicts: [],
    assetSlots: [{ key: 'logo', ratio: 'libre', minWidth: 240, minHeight: 80 }],
    required: true,
    fixed: true,
  }),
  variant({
    id: 'el-hero-01',
    surfaceContext: 'image',
    sectionType: 'hero',
    sourceTemplateId: 'canine-elegance',
    name: 'Hero cinematográfico oscuro',
    description: 'Imagen a sangre con velo oscuro, CTA dorado, botón de vídeo y cuatro garantías.',
    requiredFields: ['content.hero.title', 'content.hero.paragraph', 'content.hero.image'],
    optionalFields: ['content.hero.videoCta'],
    collectionLimits: [{ collection: 'content.hero.microBenefits', min: 4, max: 4 }],
    themeTokenCoverage: ['brandPrimary', 'surfaceInverse', 'textInverse', 'textMutedInverse'],
    responsiveContract: { desktop: 'overlay 46%', tablet: 'overlay 66%', mobile: 'foto 4:5 + copy' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: ['header'],
    conflicts: [],
    assetSlots: [{ key: 'hero', ratio: '16:7', minWidth: 2800, minHeight: 1250 }],
    required: true,
    fixed: false,
  }),
  variant({
    id: 'el-services-01',
    surfaceContext: 'light',
    sectionType: 'services',
    sourceTemplateId: 'canine-elegance',
    name: 'Servicios con retrato lateral',
    description: 'Cuatro cards horizontales con foto 42 % e icono dorado sobre círculo negro.',
    requiredFields: ['services'],
    optionalFields: [],
    collectionLimits: [{ collection: 'services', min: 4, max: 4 }],
    themeTokenCoverage: ['brandPrimary', 'surfaceInverse', 'surface', 'border'],
    responsiveContract: { desktop: '4 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#servicios', '/servicios', '/servicios/{slug}'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'service', ratio: '4:5', minWidth: 900, minHeight: 1125 }],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'el-plans-01',
    surfaceContext: 'light',
    sectionType: 'plans',
    sourceTemplateId: 'canine-elegance',
    name: 'Planes mensuales + perfil de mascota',
    description: 'Franja 50/50 con tres planes sobre negro y el mockup del perfil digital.',
    requiredFields: ['plans', 'content.petProfile'],
    optionalFields: [],
    collectionLimits: [{ collection: 'plans', min: 2, max: 4 }],
    themeTokenCoverage: ['brandPrimary', 'surfaceInverse', 'surfaceInverseSoft', 'surfaceAlt'],
    responsiveContract: { desktop: '50/50', tablet: 'apilado', mobile: 'planes en carrusel' },
    navigationOutputs: ['#planes', '#perfil-mascota', '/perfil-mascota/crear'],
    requiredCompanions: [],
    conflicts: ['packages'],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'el-process-01',
    surfaceContext: 'light',
    sectionType: 'process',
    sourceTemplateId: 'canine-elegance',
    name: 'Proceso con números y flechas',
    description: 'Cuatro pasos horizontales con numeración dorada y flechas decorativas.',
    requiredFields: ['content.processSteps'],
    optionalFields: [],
    collectionLimits: [{ collection: 'content.processSteps', min: 4, max: 4 }],
    themeTokenCoverage: ['brandPrimary', 'surface', 'textMuted'],
    responsiveContract: { desktop: '4 columnas', tablet: '2×2', mobile: '1 columna' },
    navigationOutputs: ['#proceso'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'el-testimonials-01',
    surfaceContext: 'dark',
    sectionType: 'testimonials',
    sourceTemplateId: 'canine-elegance',
    name: 'Testimonios sobre negro',
    description: 'Carrusel de tres cards antracita con avatar grande y estrellas doradas.',
    requiredFields: ['testimonials'],
    optionalFields: [],
    collectionLimits: [{ collection: 'testimonials', min: 3, max: 8 }],
    themeTokenCoverage: ['brandPrimary', 'surfaceInverse', 'textInverse', 'star'],
    responsiveContract: { desktop: '3 visibles', tablet: '2 visibles', mobile: '1 visible' },
    navigationOutputs: ['#testimonios'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'testimonial', ratio: '1:1', minWidth: 640, minHeight: 640 }],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'el-gallery-01',
    surfaceContext: 'light',
    sectionType: 'gallery',
    sourceTemplateId: 'canine-elegance',
    name: 'Galería de seis fotografías',
    description: 'Una fila de seis imágenes 4:3 coherentes con lightbox accesible.',
    requiredFields: ['gallery'],
    optionalFields: [],
    collectionLimits: [{ collection: 'gallery', min: 6, max: 12 }],
    themeTokenCoverage: ['surface', 'radiusImage', 'brandPrimary'],
    responsiveContract: { desktop: '6 columnas', tablet: '3×2', mobile: 'carrusel' },
    navigationOutputs: ['#galeria', '/galeria'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'gallery', ratio: '4:3', minWidth: 1200, minHeight: 900 }],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'el-finalcta-01',
    surfaceContext: 'brand',
    sectionType: 'finalCta',
    sourceTemplateId: 'canine-elegance',
    name: 'CTA dorado final',
    description: 'Franja dorada con huella, texto, botón negro y perro recortado al borde.',
    requiredFields: ['content.finalCta'],
    optionalFields: ['content.finalCta.image'],
    collectionLimits: [],
    themeTokenCoverage: ['brandPrimary', 'brandPrimaryContrast', 'buttonGradient'],
    responsiveContract: { desktop: 'horizontal', tablet: 'horizontal', mobile: 'apilado sin perro' },
    navigationOutputs: [],
    requiredCompanions: ['booking'],
    conflicts: [],
    assetSlots: [{ key: 'ctaDog', ratio: 'libre', minWidth: 1200, minHeight: 700 }],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'el-footer-01',
    surfaceContext: 'dark',
    sectionType: 'footer',
    sourceTemplateId: 'canine-elegance',
    name: 'Footer antracita con newsletter',
    description: 'Cinco columnas, newsletter validado y WhatsApp flotante.',
    requiredFields: ['business.legalName', 'content.legal', 'content.newsletter'],
    optionalFields: ['contact.socialLinks'],
    collectionLimits: [],
    themeTokenCoverage: ['brandPrimary', 'surfaceInverseSoft', 'textInverse'],
    responsiveContract: RESPONSIVE_STACK,
    navigationOutputs: ['#contacto', '/privacidad', '/aviso-legal', '/cookies'],
    requiredCompanions: ['header'],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: true,
  }),

  /* ------------------------------ Peludos & Co. --------------------------- */
  variant({
    id: 'pco-header-01',
    sectionType: 'header',
    sourceTemplateId: 'canine-peludos-and-co',
    name: 'Header con teléfono visible',
    description: 'Barra blanca con navegación centrada, teléfono y CTA lila.',
    requiredFields: ['business.name', 'business.phone', 'navigation.items'],
    optionalFields: ['business.logo'],
    collectionLimits: [{ collection: 'navigation.items', min: 3, max: 8 }],
    themeTokenCoverage: ['brandPrimary', 'surface', 'border'],
    responsiveContract: { desktop: 'logo · nav · acciones', tablet: 'logo · acciones', mobile: 'drawer' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: ['footer'],
    conflicts: [],
    assetSlots: [{ key: 'logo', ratio: 'libre', minWidth: 240, minHeight: 80 }],
    required: true,
    fixed: true,
  }),
  variant({
    id: 'pco-hero-01',
    sectionType: 'hero',
    sourceTemplateId: 'canine-peludos-and-co',
    name: 'Hero partido con badge de reseñas',
    description: 'Mitades casi iguales, degradado en el titular y badge de valoración configurable.',
    requiredFields: ['content.hero.title', 'content.hero.paragraph', 'content.hero.image'],
    optionalFields: ['content.hero.ratingBadge'],
    collectionLimits: [{ collection: 'content.hero.microBenefits', min: 3, max: 4 }],
    themeTokenCoverage: ['brandPrimary', 'gradientAccent', 'surfaceMuted', 'surface'],
    responsiveContract: { desktop: '50/50', tablet: '50/50', mobile: 'copy → foto → badge' },
    navigationOutputs: ['#inicio'],
    requiredCompanions: ['booking'],
    conflicts: [],
    assetSlots: [{ key: 'hero', ratio: '4:5', minWidth: 1800, minHeight: 2250 }],
    required: true,
    fixed: false,
  }),
  variant({
    id: 'pco-services-01',
    sectionType: 'services',
    sourceTemplateId: 'canine-peludos-and-co',
    name: 'Cinco servicios compactos con precio',
    description: 'Cards finas con icono lila, descripción de dos líneas y “Desde X €”.',
    requiredFields: ['services'],
    optionalFields: [],
    collectionLimits: [{ collection: 'services', min: 4, max: 6 }],
    themeTokenCoverage: ['brandPrimary', 'surfaceMuted', 'border'],
    responsiveContract: { desktop: '5 columnas', tablet: '3 columnas', mobile: '1 columna' },
    navigationOutputs: ['#servicios', '/servicios'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pco-packages-01',
    sectionType: 'packages',
    sourceTemplateId: 'canine-peludos-and-co',
    name: 'Paquetes con foto recortada',
    description: 'Tres cards horizontales con perro recortado y lista lateral de valor.',
    requiredFields: ['packages', 'content.packagesSideBenefits'],
    optionalFields: [],
    collectionLimits: [{ collection: 'packages', min: 3, max: 3 }],
    themeTokenCoverage: ['brandPrimary', 'surfaceMuted', 'surface'],
    responsiveContract: { desktop: '3 + lateral', tablet: '3 columnas', mobile: '1 columna' },
    navigationOutputs: ['#paquetes'],
    requiredCompanions: ['booking'],
    conflicts: ['plans'],
    assetSlots: [{ key: 'package', ratio: '4:5', minWidth: 800, minHeight: 1000 }],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pco-process-01',
    sectionType: 'process',
    sourceTemplateId: 'canine-peludos-and-co',
    name: 'Proceso lineal lila',
    description: 'Cuatro pasos con iconos en círculo y conectores punteados.',
    requiredFields: ['content.processSteps'],
    optionalFields: [],
    collectionLimits: [{ collection: 'content.processSteps', min: 4, max: 4 }],
    themeTokenCoverage: ['brandPrimary', 'surface', 'borderStrong'],
    responsiveContract: { desktop: '4 columnas', tablet: '2×2', mobile: '1 columna' },
    navigationOutputs: ['#proceso'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pco-benefits-01',
    sectionType: 'benefits',
    sourceTemplateId: 'canine-peludos-and-co',
    name: 'Cinco ventajas equidistantes',
    description: 'Fila independiente con iconos de acento suave y una línea explicativa.',
    requiredFields: ['content.benefits'],
    optionalFields: [],
    collectionLimits: [{ collection: 'content.benefits', min: 4, max: 6 }],
    themeTokenCoverage: ['brandPrimary', 'accentTertiary', 'surface', 'border'],
    responsiveContract: { desktop: '5 columnas', tablet: '3 columnas', mobile: 'lista' },
    navigationOutputs: ['#por-que-elegirnos'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pco-testimonials-01',
    sectionType: 'testimonials',
    sourceTemplateId: 'canine-peludos-and-co',
    name: 'Reseña estrecha + comparaciones fijas',
    description: 'Testimonio al 26 % y tres comparadores partidos fijos al 74 %.',
    requiredFields: ['testimonials', 'transformations'],
    optionalFields: [],
    collectionLimits: [
      { collection: 'testimonials', min: 1, max: 6 },
      { collection: 'transformations', min: 3, max: 6 },
    ],
    themeTokenCoverage: ['brandPrimary', 'surfaceMuted', 'star'],
    responsiveContract: { desktop: '26/74', tablet: 'apilado', mobile: 'apilado' },
    navigationOutputs: ['#testimonios', '#transformaciones'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'transformation', ratio: '1:1', minWidth: 900, minHeight: 900 }],
    required: false,
    fixed: false,
  }),
  variant({
    id: 'pco-booking-01',
    sectionType: 'booking',
    sourceTemplateId: 'canine-peludos-and-co',
    name: 'Reserva rápida horizontal',
    description: 'Card ancha con intro del 28 % y formulario en cuatro columnas.',
    requiredFields: ['booking'],
    optionalFields: ['business.whatsapp'],
    collectionLimits: [],
    themeTokenCoverage: ['brandPrimary', 'surface', 'surfaceMuted'],
    responsiveContract: { desktop: 'intro + 4 columnas', tablet: '2 columnas', mobile: '1 columna' },
    navigationOutputs: ['#reserva'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: false,
  }),
  variant({
    id: 'pco-footer-01',
    sectionType: 'footer',
    sourceTemplateId: 'canine-peludos-and-co',
    name: 'Footer azul noche de cinco columnas',
    description: 'Marca, enlaces, servicios, información y contacto con etiqueta de zona.',
    requiredFields: ['business.legalName', 'content.legal', 'business.openingHours'],
    optionalFields: ['contact.socialLinks'],
    collectionLimits: [],
    themeTokenCoverage: ['surfaceInverse', 'textInverse', 'brandSecondary'],
    responsiveContract: RESPONSIVE_STACK,
    navigationOutputs: ['#contacto', '/aviso-legal', '/privacidad', '/cookies'],
    requiredCompanions: ['header'],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: true,
  }),

  /* ------------------------ Páginas secundarias comunes -------------------- */
  variant({
    id: 'common-pricing-01',
    sectionType: 'packages',
    sourceTemplateId: 'common',
    name: 'Página de tarifas',
    description: 'Paquetes y planes con comparativa, condiciones y CTA.',
    requiredFields: ['packages'],
    optionalFields: [],
    collectionLimits: [],
    themeTokenCoverage: ['surface', 'text', 'brandPrimary'],
    responsiveContract: { desktop: '2 columnas', tablet: '1 columna', mobile: '1 columna' },
    navigationOutputs: ['/precios'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'package', ratio: '4:3', minWidth: 900, minHeight: 675 }],
    required: true,
    fixed: true,
  }),
  variant({
    id: 'common-contact-01',
    sectionType: 'contact',
    sourceTemplateId: 'common',
    name: 'Página de contacto',
    description: 'Datos, horarios, mapa y formulario de solicitud.',
    requiredFields: ['business'],
    optionalFields: [],
    collectionLimits: [],
    themeTokenCoverage: ['surface', 'text', 'brandPrimary'],
    responsiveContract: { desktop: '2 columnas', tablet: '1 columna', mobile: '1 columna' },
    navigationOutputs: ['/contacto'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'ambience', ratio: '4:5', minWidth: 1200, minHeight: 1500 }],
    required: true,
    fixed: true,
  }),
  variant({
    id: 'common-booking-01',
    sectionType: 'booking',
    sourceTemplateId: 'common',
    name: 'Página de reserva',
    description: 'Formulario completo de reserva con resumen lateral.',
    requiredFields: ['booking'],
    optionalFields: [],
    collectionLimits: [],
    themeTokenCoverage: ['surface', 'text', 'brandPrimary'],
    responsiveContract: { desktop: '2 columnas', tablet: '1 columna', mobile: '1 columna' },
    navigationOutputs: ['/reservar'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: true,
  }),
  variant({
    id: 'common-testimonials-01',
    sectionType: 'testimonials',
    sourceTemplateId: 'common',
    name: 'Página de opiniones',
    description: 'Reseñas completas con valoración.',
    requiredFields: ['testimonials'],
    optionalFields: [],
    collectionLimits: [],
    themeTokenCoverage: ['surface', 'text', 'brandPrimary'],
    responsiveContract: { desktop: '2 columnas', tablet: '1 columna', mobile: '1 columna' },
    navigationOutputs: ['/opiniones'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'testimonial', ratio: '1:1', minWidth: 320, minHeight: 320 }],
    required: true,
    fixed: true,
  }),
  variant({
    id: 'common-faq-01',
    sectionType: 'faq',
    sourceTemplateId: 'common',
    name: 'Página de preguntas',
    description: 'Preguntas frecuentes en acordeón accesible.',
    requiredFields: ['faqs'],
    optionalFields: [],
    collectionLimits: [],
    themeTokenCoverage: ['surface', 'text', 'brandPrimary'],
    responsiveContract: { desktop: '2 columnas', tablet: '1 columna', mobile: '1 columna' },
    navigationOutputs: ['/preguntas'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: true,
  }),
  variant({
    id: 'common-petprofile-create-01',
    sectionType: 'petProfile',
    sourceTemplateId: 'common',
    name: 'Alta de perfil de mascota',
    description: 'Formulario de alta separado de la reserva de cita.',
    requiredFields: ['content.petProfile'],
    optionalFields: [],
    collectionLimits: [],
    themeTokenCoverage: ['surface', 'text', 'brandPrimary'],
    responsiveContract: { desktop: '2 columnas', tablet: '1 columna', mobile: '1 columna' },
    navigationOutputs: ['/perfil-mascota/crear'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: true,
  }),
  variant({
    id: 'common-legal-01',
    sectionType: 'contact',
    sourceTemplateId: 'common',
    name: 'Página legal',
    description: 'Aviso legal, privacidad o cookies según la ruta activa.',
    requiredFields: ['content.legal'],
    optionalFields: [],
    collectionLimits: [],
    themeTokenCoverage: ['surface', 'text', 'textMuted'],
    responsiveContract: { desktop: '1 columna', tablet: '1 columna', mobile: '1 columna' },
    navigationOutputs: [],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: true,
  }),
  variant({
    id: 'common-services-01',
    sectionType: 'services',
    sourceTemplateId: 'common',
    name: 'Página de servicios',
    description: 'Listado completo o detalle de un servicio según la ruta.',
    requiredFields: ['services'],
    optionalFields: [],
    collectionLimits: [{ collection: 'services', min: 1, max: 12 }],
    themeTokenCoverage: ['surface', 'brandPrimary'],
    responsiveContract: { desktop: '2 columnas', tablet: '1 columna', mobile: '1 columna' },
    navigationOutputs: ['/servicios'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'service', ratio: '4:3', minWidth: 900, minHeight: 675 }, { key: 'hero', ratio: '4:5', minWidth: 1600, minHeight: 2000 }],
    required: true,
    fixed: true,
  }),
  variant({
    id: 'common-gallery-01',
    sectionType: 'gallery',
    sourceTemplateId: 'common',
    name: 'Página de galería',
    description: 'Galería completa o filtro de transformaciones.',
    requiredFields: ['gallery'],
    optionalFields: ['transformations'],
    collectionLimits: [{ collection: 'gallery', min: 3, max: 24 }, { collection: 'transformations', min: 0, max: 12 }],
    themeTokenCoverage: ['surface', 'radiusImage'],
    responsiveContract: { desktop: '4 columnas', tablet: '3 columnas', mobile: '2 columnas' },
    navigationOutputs: ['/galeria'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'gallery', ratio: '4:3', minWidth: 1200, minHeight: 900 }, { key: 'transformation', ratio: '1:1', minWidth: 900, minHeight: 900 }],
    required: true,
    fixed: true,
  }),
  variant({
    id: 'common-about-01',
    sectionType: 'benefits',
    sourceTemplateId: 'common',
    name: 'Página sobre nosotros',
    description: 'Página editorial derivada del contenido del negocio y sus ventajas.',
    requiredFields: ['business.name', 'content.benefits'],
    optionalFields: [],
    collectionLimits: [{ collection: 'team', min: 0, max: 12 }],
    themeTokenCoverage: ['surface', 'text'],
    responsiveContract: { desktop: '1 columna', tablet: '1 columna', mobile: '1 columna' },
    navigationOutputs: ['/sobre-nosotros'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [{ key: 'ambience', ratio: '4:5', minWidth: 1200, minHeight: 1500 }, { key: 'team', ratio: '4:5', minWidth: 900, minHeight: 1125 }],
    required: true,
    fixed: true,
  }),
  variant({
    id: 'common-petprofile-01',
    sectionType: 'petProfile',
    sourceTemplateId: 'common',
    name: 'Alta de perfil de mascota',
    description: 'Formulario de alta con verificación por enlace de un solo uso.',
    requiredFields: ['booking'],
    optionalFields: [],
    collectionLimits: [],
    themeTokenCoverage: ['surface', 'brandPrimary'],
    responsiveContract: { desktop: '2 columnas', tablet: '1 columna', mobile: '1 columna' },
    navigationOutputs: ['/perfil-mascota/crear'],
    requiredCompanions: [],
    conflicts: [],
    assetSlots: [],
    required: true,
    fixed: true,
  }),
  /* -------------------------------- Estudio ------------------------------- */
  ...ESTUDIO_VARIANTS,
  /* --------------------------- Control de plagas -------------------------- */
  ...PLAGAS_RESPUESTA_RAPIDA_VARIANTS,
  ...PLAGAS_CORPORATIVA_VARIANTS,
  ...PLAGAS_HOGAR_VARIANTS,
  /* --------------------------- Biblioteca compartida ---------------------- */
  ...SHARED_VARIANTS,
  /* --------------------------- Familias visuales -------------------------- */
  ...PROFILE_VARIANTS,
  ...PROFILE_B_VARIANTS,
];

const VARIANT_INDEX = new Map(SECTION_VARIANTS.map((v) => [v.id, v]));

export function getVariant(id: string): SectionVariant | undefined {
  return VARIANT_INDEX.get(id);
}

export function getVariantsByType(sectionType: string): SectionVariant[] {
  return SECTION_VARIANTS.filter((v) => v.sectionType === sectionType && v.sourceTemplateId !== 'common');
}
